set(CONFIG_TIMER_EVENT true)
set(CONFIG_CRYPTO_SUPPORT_EC25519 true)
set(CONFIG_CRYPTO_SUPPORT_X509 true)
set(CONFIG_CRYPTO_ECC_WRAPPER true)
set(CONFIG_CRYPTO_AES_WRAPPER true)

include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/${CHIP_NAME}/modules/modules.cmake)
