/*
 * Copyright (C) 2022 Huawei Technologies Co., Ltd.
 * Licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *     http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
 * PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#ifndef PERMSRV_TA_PERMISSION_CONFIG
#define PERMSRV_TA_PERMISSION_CONFIG

#include "tee_defines.h"
#include "tee_reserve.h"

static const TEE_UUID g_tui_permsrv[] = {
#ifdef CONFIG_TA_PERMISSION_SET_TERMINAL
    TEE_SERVICE_CCB,
    TEE_SERVICE_CFCA,
    TEE_SERVICE_BAK,
    TEE_SERVICE_IFAA,
    TEE_SERVICE_EID_U3,
    TEE_SERVICE_EID_U1,
    TEE_SERVICE_U_TA_1,
    TEE_SERVICE_U_TA_2,
    TEE_SERVICE_U_TA_3,
    TEE_SERVICE_U_TA_4,
    TEE_SERVICE_U_TA_5,
    TEE_SERVICE_U_TA_6,
    TEE_SERVICE_U_TA_7,
    TEE_SERVICE_U_TA_8,
    TEE_SERVICE_U_TA_9,
    TEE_SERVICE_U_TA_10,
    TEE_SERVICE_U_TA_11,
    TEE_SERVICE_U_TA_12,
    TEE_SERVICE_U_TA_13,
    TEE_SERVICE_U_TA_14,
    TEE_SERVICE_U_TA_16,
    TEE_SERVICE_U_TA_17,
    TEE_SERVICE_U_TA_18,
    TEE_SERVICE_U_TA_19,
    TEE_SERVICE_U_TA_20,
    TEE_SERVICE_U_TA_21,
    TEE_SERVICE_U_TA_22,
    TEE_SERVICE_U_TA_23,
    TEE_SERVICE_U_TA_24,
    TEE_SERVICE_U_TA_26,
    TEE_SERVICE_U_TA_27,
    TEE_SERVICE_U_TA_28,
    TEE_SERVICE_U_TA_29,
    TEE_SERVICE_U_TA_30,
    TEE_SERVICE_U_TA_0,
#endif
};

static const TEE_UUID g_sem_reserved_permsrv[] = {
#ifdef CONFIG_TA_PERMISSION_SET_TERMINAL
    TEE_SERVICE_U_TA_1,
    TEE_SERVICE_U_TA_2,
    TEE_SERVICE_U_TA_3,
    TEE_SERVICE_U_TA_4,
    TEE_SERVICE_U_TA_5,
    TEE_SERVICE_U_TA_6,
    TEE_SERVICE_U_TA_7,
    TEE_SERVICE_U_TA_8,
    TEE_SERVICE_U_TA_9,
    TEE_SERVICE_U_TA_10,
    TEE_SERVICE_U_TA_11,
    TEE_SERVICE_U_TA_12,
    TEE_SERVICE_U_TA_13,
    TEE_SERVICE_U_TA_14,
    TEE_SERVICE_U_TA_16,
    TEE_SERVICE_U_TA_17,
    TEE_SERVICE_U_TA_18,
    TEE_SERVICE_U_TA_19,
    TEE_SERVICE_U_TA_20,
    TEE_SERVICE_U_TA_21,
    TEE_SERVICE_U_TA_22,
    TEE_SERVICE_U_TA_23,
    TEE_SERVICE_U_TA_24,
    TEE_SERVICE_U_TA_25,
    TEE_SERVICE_U_TA_26,
    TEE_SERVICE_U_TA_27,
    TEE_SERVICE_U_TA_28,
    TEE_SERVICE_U_TA_29,
    TEE_SERVICE_U_TA_30,
    TEE_SERVICE_CCB,
    TEE_SERVICE_CFCA,
    TEE_SERVICE_BAK,
    TEE_SERVICE_WALLET,
    TEE_SERVICE_IFAA,
    TEE_SERVICE_EID_U3,
    TEE_SERVICE_EID_U1,
    TEE_SERVICE_PANPAY,
    TEE_SERVICE_U_TA_0,
    TEE_SERVICE_WEAVER,
#endif
};

#endif
