set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_ORLANDO)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x14808000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x15000000)
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DFEATURE_SE
    -DCONFIG_HISEE_14_CHANNEL_IPC
    -DTEE_SUPPORT_FILE_ENCRY
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_AI
    -DTEE_SUPPORT_SECIDENTIFICATION
)
set(GATEKEEPER_ITRATION_TIMES 400)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)