#ifndef _HISI_SECLOCK_H_
#define _HISI_SECLOCK_H_


typedef enum SECBOOT_LOCKSTATE_TAG {
	SECBOOT_LSTATE_LOCKED = 0,
	SECBOOT_LSTATE_UNLOCKED = 1,
	SECBOOT_LSTATE_RELOCKED = 2,
} SECBOOT_LOCKSTATE;

#endif
