set(CONFIG_TA_32BIT  true)
set(CONFIG_TIMER_EVENT true)
set(CONFIG_TIMER_EVENT true)
set(CONFIG_CRYPTO_SUPPORT_EC25519 true)
set(CONFIG_CRYPTO_SUPPORT_X509 true)
set(CONFIG_CRYPTO_ECC_WRAPPER true)
set(CONFIG_CRYPTO_AES_WRAPPER true)
set(CONFIG_TA_SIGN_KEY_CBG true)
set(CONFIG_SIGN_KEY_RELEASE_DEBUG_ISOLATION true)

list(APPEND PRODUCT_RELEASE_64 mspcore rot weaver art biometric sec_flash_client vltmm chinadrm)
list(APPEND PRODUCT_RELEASE_32 mspcore rot weaver art biometric sec_flash_client vltmm chinadrm)
if ("${CONFIG_DX_ENABLE}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_32 dx_cc7)
endif()

if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 storage.elf antiroot.elf kds.elf secboot.elf)
else()
    list(APPEND PRODUCT_RELEASE_64 storage.elf antiroot.elf kds.elf secboot.elf)
    list(APPEND PRODUCT_RELEASE_32 storage.elf antiroot.elf kds.elf secboot.elf)
endif()

list(APPEND BOOTFS_FILES_IN_PREBUILD taloader.elf)

if ("${CONFIG_TA_32BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_32 tarunner.elf)
endif()

if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
    list(APPEND PRODUCT_APPS_32 storage.elf antiroot.elf kds.elf secboot.elf)
endif()
if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_64 storage.elf antiroot.elf kds.elf secboot.elf)
endif()

if ("${CONFIG_KEYMASTER_32BIT}" STREQUAL "true" OR "${CONFIG_KEYMASTER_64BIT}" STREQUAL "true")
    if ("${CONFIG_KEYMASTER_64BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 keymaster.elf)
        list(APPEND PRODUCT_APPS_64 keymaster.elf)
    endif()
    if ("${CONFIG_KEYMASTER_32BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 keymaster.elf)
        list(APPEND PRODUCT_APPS_64 keymaster.elf)
        list(APPEND PRODUCT_RELEASE_32 keymaster.elf)
        list(APPEND PRODUCT_APPS_32 keymaster.elf)
    endif()
endif()

if ("${CONFIG_GATEKEEPER_32BIT}" STREQUAL "true" OR "${CONFIG_GATEKEEPER_64BIT}" STREQUAL "true")
    if ("${CONFIG_GATEKEEPER_64BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 gatekeeper.elf)
        list(APPEND PRODUCT_APPS_64 gatekeeper.elf)
    endif()
    if ("${CONFIG_GATEKEEPER_32BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 gatekeeper.elf)
        list(APPEND PRODUCT_APPS_64 gatekeeper.elf)
        list(APPEND PRODUCT_RELEASE_32 gatekeeper.elf)
        list(APPEND PRODUCT_APPS_32 gatekeeper.elf)
    endif()
endif()

if ("${CONFIG_ANTIROOT}" STREQUAL "true")
    if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 antiroot.elf)
    else()
        list(APPEND PRODUCT_RELEASE_64 antiroot.elf)
        list(APPEND PRODUCT_RELEASE_32 antiroot.elf)
    endif()

    if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
        list(APPEND PRODUCT_APPS_32 antiroot.elf)
    endif()
    if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
        list(APPEND PRODUCT_APPS_64 antiroot.elf)
    endif()
endif()

if ("${CONFIG_SE_SERVICE_32BIT}" STREQUAL "true" OR "${CONFIG_SE_SERVICE_64BIT}" STREQUAL "true")
    if ("${CONFIG_SE_SERVICE_64BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 se_service.elf)
        list(APPEND PRODUCT_APPS_64 se_service.elf)
    endif()
    if ("${CONFIG_SE_SERVICE_32BIT}" STREQUAL "true")
        list(APPEND PRODUCT_RELEASE_64 se_service.elf)
        list(APPEND PRODUCT_APPS_64 se_service.elf)
        list(APPEND PRODUCT_RELEASE_32 se_service.elf)
        list(APPEND PRODUCT_APPS_32 se_service.elf)
    endif()
endif()
