TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_MT6885
TRUSTEDCORE_PHY_TEXT_BASE := 0x70008000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x70800000
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_ATTESTATION_TA
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY_V2
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY
GATEKEEPER_ITRATION_TIMES := 0
DERIVE_ROOT_INTERNAL_ITRATIONS := 0