set(CONFIG_TUI_32BIT true)
set(CONFIG_TUI_MTK_DRIVER true)
set(CONFIG_TA_64BIT true)
set(CONFIG_SSA_64BIT true)
set(CONFIG_GTASK_64BIT true)
set(CONFIG_RPMB_64BIT true)
set(CONFIG_ATTESTATION_TA true)
set(CONFIG_GATEKEEPER_64BIT true)
set(CONFIG_KEYMASTER_64BIT true)
set(CONFIG_PERMSRV_64BIT true)
set(CONFIG_PLATDRV_64BIT false)
set(CONFIG_TIMER_EVENT true)
set(CONFIG_SOFT_RTC_TICK true)
set(CONFIG_DRV_TIMER_64BIT false)
set(CONFIG_DRV_64BIT false)
set(CONFIG_TIMER_FREERUNNING_FIQ_DISABLE true)
set(CONFIG_GMLIB_IMPORT true)
set(CONFIG_DX_ENABLE true)
set(CONFIG_HUK_SERVICE_64BIT true)
set(CONFIG_SE_SERVICE_32BIT true)
set(CONFIG_HUK_PLAT_COMPATIBLE true)
set(CONFIG_M_DRIVER true)
set(CONFIG_ARM64_PAN true)
set(CONFIG_ANTIROOT true)
set(CONFIG_SEM true)
set(TEE_SUPPORT_FILE_ENCRY_V2 true)

if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 kds.elf file_encry.elf antiroot.elf)
else()
    list(APPEND PRODUCT_RELEASE_64 kds.elf file_encry.elf antiroot.elf)
    list(APPEND PRODUCT_RELEASE_32 kds.elf file_encry.elf antiroot.elf)
endif()

if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
    list(APPEND PRODUCT_APPS_32 kds.elf file_encry.elf antiroot.elf)
endif()
if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_64 kds.elf file_encry.elf antiroot.elf)
endif()
