/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: teecall policy after delete public teecalls.
 * Author: wangxiaochu  wangxiaochu@huawei.com
 * Create: 2020-10
 */

#ifndef MTK_TEECALL_POLICY_H
#define MTK_TEECALL_POLICY_H

static const cap_teecall_t g_teecall_cap[AC_SID_NUM] = {
    [AC_ARRAY_IDX_BUILTIN(KEYMASTER)]  = { TEECALL_SET_KM_ROT_GROUP_PERMISSION | TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX_BUILTIN(GATEKEEPER)] = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX_BUILTIN(RPMB)]       = { TEECALL_RPMB_GENERIC_PERMISSION },
    [AC_ARRAY_IDX_BUILTIN(TUI)]        = { 0 },
    [AC_ARRAY_IDX_BUILTIN(SSA)]        = { 0 },
    [AC_ARRAY_IDX_BUILTIN(STORAGE)]    = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX_BUILTIN(ANTIROOT)] =   { 0 },
    [AC_ARRAY_IDX_BUILTIN(SEM)]        = { 0 },
    [AC_ARRAY_IDX_BUILTIN(README)]     = { 0 },
    [AC_ARRAY_IDX_BUILTIN(PERF)]       = { 0 },
    [AC_ARRAY_IDX_BUILTIN(FILEMGR)]    = { 0 },
    /* builtin end */
    [AC_ARRAY_IDX(TEE_SERVICE_GLOBAL)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_RPMB)]          = { TEECALL_RPMB_GENERIC_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_TUI)]           = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_STORAGE)]       = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_CRYPT)]         = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_EFUSE)]         = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_HDCP)]          = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_BAK)]           = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_KEYMASTER)]     = { TEECALL_GET_KM_ROT_GROUP_PERMISSION |
                                                  TEECALL_SET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_REET)]          = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_GATEKEEPER)]    = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },

    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_8)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_CCB)]           = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_SKYTONE_UI)]    = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_PLAYREADY_DRM)] = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_5)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_WALLET)]  = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_4)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_ALIPAY)]        = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_6)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_RPMBKEY)]       = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_2)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_3)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_CRYPTOSMS)]     = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_MMZ)]           = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_PKI)]           = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_HARDWARECHECK)] = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_FIDO)]          = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_0)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_IFAA)]          = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_SSA)]           = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_SIGNTOOL)]      = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_7)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_FINGERPRINT)]   = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_WIDEVINE_DRM)]  = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_UDFINGERPRINT)] = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_DTV)]           = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_SEM)]           = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_1)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_9)]        = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_ANTITHEFT)]     = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_WECHAT)]        = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_IMAXCRYPTO)]    = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_KDS)]           = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_FINGERPRINT_COATING_CHECK)]     = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_ANTIROOT)]      = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_FACE_REC)]              = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_EID_U3)]                = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_EID_U1)]                = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_FINGERPRINT_SAVEIMAGE)] = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_U_TA_10)]               = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_CFCA)]                  = { 0 },
    [AC_ARRAY_IDX(TEE_FINGERPRINT_SENSOR_CHECK)]      = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_CHINADRM)]              = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_VOICE_REC)]             = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_REMOTE_PIN)]                    = { TEECALL_GET_KM_ROT_GROUP_PERMISSION },
#ifdef DEF_ENG
    [AC_ARRAY_IDX(TEE_SERVICE_ECHO)]           = { TEECALL_ALL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_UT)]             = { TEECALL_ALL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SEVICE_VIDEO_TEST)]      = { TEECALL_ALL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(HM_TEEOS_TEST)]              = { TEECALL_ALL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_KERNELMEMUSAGE)] = { TEECALL_ALL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_TIMER_UT)]       = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_HELLOWORLD)]     = { TEECALL_GENERAL_GROUP_PERMISSION },
    [AC_ARRAY_IDX(TEE_SERVICE_ENDORSEMENT)]    = { 0 },
    [AC_ARRAY_IDX(TEE_SERVICE_PERMCTRL_UT)]    = { TEECALL_GENERAL_GROUP_PERMISSION },
#endif
};

#include "public_teecall.h"

#endif
