
WITH_LINGXIAO_PLATFORM := 4
WITH_CHIP_HI5651T := 16

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_LINGXIAO_PLATFORM
	PLATFORM_NAME := lingxiao
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := router

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI5651T=$(WITH_CHIP_HI5651T) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_LINGXIAO_PLATFORM=$(WITH_LINGXIAO_PLATFORM)

