# platform compile rules
# Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
#
ifneq ($(strip $(TARGET_BOARD_PLATFORM)), )
include $(PLATFORM_DIR)/../mk/plat/$(TARGET_BOARD_PLATFORM)/plat.mk

ifeq ($(strip $(PRODUCT_NAME)), )
include $(PLATFORM_DIR)/$(PLATFORM_NAME)/$(CHIP_NAME)/chip.mk
include $(PLATFORM_DIR)/$(PLATFORM_NAME)/common/chip.mk
else
include $(PLATFORM_DIR)/$(PLATFORM_NAME)/$(PRODUCT_NAME)/$(CHIP_NAME)/chip.mk
include $(PLATFORM_DIR)/$(PLATFORM_NAME)/$(PRODUCT_NAME)/common/chip.mk
endif

TRUSTEDCORE_PLATFORM_FLAGS += \
    -DTRUSTEDCORE_PHY_TEXT_BASE=$(TRUSTEDCORE_PHY_TEXT_BASE) \
    -DTRUSTEDCORE_PHY_IMAGE_LOAD_BASE=$(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE) \
    -DTRUSTEDCORE_CHIP_CHOOSE=$(TRUSTEDCORE_CHIP_CHOOSE) \
    -DTRUSTEDCORE_PLATFORM_CHOOSE=$(TRUSTEDCORE_PLATFORM_CHOOSE)
endif
