

export CFG_HI_TEE_CHIP_TYPE := hi3751v900

#export CFG_HI_TEE_NPU_SUPPORT := y
export CFG_HI_TEE_SMMU_SUPPORT := y
export CFG_HI_TEE_SEC_MMZ_SUPPORT := y
export CFG_HI_TEE_COMMON_SUPPORT := y
export CFG_HI_TEE_KLAD_SUPPORT := y
export CFG_HI_TEE_KEYSLOT_SUPPORT := y
export CFG_HI_TEE_CIPHER_SUPPORT := y
export CFG_HI_TEE_OTP_SUPPORT := y
export CFG_HI_TEE_SSM_SUPPORT := y
export CFG_HI_TEE_MAILBOX_SUPPORT := y
export CFG_HI_TEE_DYNAMIC_TA_LOAD := y
export CFG_HI_TEE_LOG_SUPPORT := y
export CFG_TEE_RPMB_SUPPORT := y
