
TRUSTEDCORE_DEVCHIP_CFLAGS += -fno-short-enums -fstack-protector-all -Wstack-protector -ffreestanding

ifeq ($(strip $(CFG_HI_TEE_WERROR_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -Werror -Wall
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -DCHIP_TYPE_$(CFG_HI_TEE_CHIP_TYPE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCHIP_TYPE_NAME=$(CFG_HI_TEE_CHIP_TYPE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DSDK_VERSION=$(CFG_HI_SDK_VERSION)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DSOS_VERSION=$(SOS_VERSION)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DSOS_MSID=$(SOS_MSID)

ifeq ($(strip $(CFG_HI_TEE_ATF_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_ATF_SUPPORT
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DATF_MEM_SIZE=$(ATF_MEM_SIZE)
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_OS_MEM_SIZE=$(TRUSTEDCORE_OS_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_MMZ_MEM_SIZE=$(TRUSTEDCORE_SEC_MMZ_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_SMMU_MMZ_MEM_SIZE=$(TRUSTEDCORE_SEC_SMMU_MMZ_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE=$(TRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_VMCU_MEM_SIZE=$(TRUSTEDCORE_VMCU_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_ADSP_MEM_SIZE=$(TRUSTEDCORE_ADSP_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_VQ6_MEM_SIZE=$(TRUSTEDCORE_VQ6_MEM_SIZE)

TRUSTEDCORE_DEVCHIP_ASFLAGS += $(TRUSTEDCORE_DEVCHIP_CFLAGS)

$(info TRUSTEDCORE_DEVCHIP_CFLAGS=$(TRUSTEDCORE_DEVCHIP_CFLAGS))
