if ("${CFG_HI_TEE_STB_PLATFORM_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_STB_PLATFORM_SUPPORT)
endif()

if ("${CFG_HI_TEE_FPGA_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_FPGA_SUPPORT)
endif()

if ("${CFG_HI_TEE_DEBUG_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_DEBUG_SUPPORT)
endif()

if ("${CFG_HI_TEE_IO_LOW_ADDR_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_IO_LOW_ADDR_SUPPORT)
endif()

if ("${CFG_HI_TEE_DEMO_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_DEMO_SUPPORT)
endif()

if ("${CFG_HI_TEE_LOG_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_LOG_SUPPORT)
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_LOG_LEVEL=0)
endif()

if ("${CFG_HI_TEE_SEC_MMZ_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_SEC_MMZ_SUPPORT)
endif()

if ("${CFG_HI_TEE_SMMU_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_SMMU_SUPPORT)
endif()

if ("${CFG_HI_TEE_DEMUX_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_DEMUX_SUPPORT)
endif()

if ("${CFG_HI_TEE_TSR2RCIPHER_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_TSR2RCIPHER_SUPPORT)
endif()

if ("${CFG_HI_TEE_PVR_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_PVR_SUPPORT)
endif()

if ("${CFG_HI_TEE_VFMW_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_VFMW_SUPPORT)
endif()

if ("${CFG_HI_TEE_AVPLAY_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_AVPLAY_SUPPORT)
endif()

if ("${CFG_HI_TEE_CIPHER_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_CIPHER_SUPPORT)
endif()

if ("${CFG_HI_TEE_HDMITX_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_HDMITX_SUPPORT)
endif()

if ("${CFG_HI_TEE_HDMITX_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_HDMIRX_SUPPORT)
endif()

if ("${CFG_HI_TEE_OTP_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_OTP_SUPPORT)
endif()

if ("${CFG_HI_TEE_KEYSLOT_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_KEYSLOT_SUPPORT)
endif()

if ("${CFG_HI_TEE_KLAD_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_KLAD_SUPPORT)
endif()

if ("${CFG_HI_TEE_ADVCA_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_ADVCA_TYPE=$(CFG_HI_TEE_ADVCA_TYPE))
endif()

if ("${CFG_HI_TEE_ADVCA_FUNCTION_RELEASE}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_ADVCA_FUNCTION_RELEASE)
endif()

if ("${CFG_HI_TEE_NAGRA_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_NAGRA_SUPPORT)
endif()

if ("${CFG_HI_TEE_SUMA_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_SUMA_SUPPORT)
endif()

if ("${CFG_HI_TEE_IRDETO_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_IRDETO_SUPPORT)
endif()

if ("${CFG_HI_TEE_VMX_ULTRA_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_VMX_ULTRA_SUPPORT)
endif()

if ("${CFG_HI_TEE_COMMON_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_COMMON_SUPPORT)
endif()

if ("${CFG_HI_TEE_PLAYREADY_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_PLAYREADY_SUPPORT)
endif()

if ("${CFG_HI_TEE_WIDEVINE_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_WIDEVINE_SUPPORT)
endif()

if ("${CFG_HI_TEE_CHINADRM_KEY_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_CHINADRM_KEY_SUPPORT)
endif()

if ("${CFG_HI_TEE_EMPTYDRM_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_EMPTYDRM_SUPPORT)
endif()

if ("${CFG_HI_TEE_KEYMASTER_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_KEYMASTER_SUPPORT)
endif()

if ("${CFG_HI_TEE_GATEKEEPER_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_GATEKEEPER_SUPPORT)
endif()

if ("${CFG_HI_TEE_SSM_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_SSM_SUPPORT)
endif()

if ("${CFG_HI_TEE_SSM_TEST_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_SSM_TEST_SUPPORT)
endif()

if ("${CFG_HI_TEE_DYNAMIC_TA_LOAD}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_DYNAMIC_TA_LOAD)
endif()

if ("${CFG_HI_TEE_NPU_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_NPU_SUPPORT)
endif()

if ("${CFG_HI_TEE_NPU_TEST_SUPPORT}" STREQUAL "y")
    list(APPEND TEE_C_FLAGS -DCFG_HI_TEE_NPU_TEST_SUPPORT)
endif()
