ifeq ($(strip $(CFG_HI_TEE_STB_PLATFORM_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_STB_PLATFORM_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_FPGA_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_FPGA_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_DEBUG_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_DEBUG_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_IO_LOW_ADDR_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_IO_LOW_ADDR_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_DEMO_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_DEMO_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_LOG_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_LOG_SUPPORT
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_LOG_LEVEL=0
endif

ifeq ($(strip $(CFG_HI_TEE_SEC_MMZ_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_SEC_MMZ_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_SMMU_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_SMMU_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_DEMUX_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_DEMUX_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_TSR2RCIPHER_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_TSR2RCIPHER_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_PVR_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_PVR_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_VFMW_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_VFMW_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_AVPLAY_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_AVPLAY_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_CIPHER_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_CIPHER_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_TEST_CIPHER_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_TEST_CIPHER_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_HDMITX_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DCFG_HI_TEE_HDMITX_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_HDMIRX_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_HDMIRX_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_OTP_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_OTP_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_KEYSLOT_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_KEYSLOT_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_KLAD_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_KLAD_SUPPORT
endif

ifeq ($(CFG_HI_TEE_ADVCA_SUPPORT),y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_ADVCA_TYPE=$(CFG_HI_TEE_ADVCA_TYPE)
endif

ifeq ($(strip $(CFG_HI_TEE_ADVCA_FUNCTION_RELEASE)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_ADVCA_FUNCTION_RELEASE
endif

ifeq ($(strip $(FG_HI_TEE_NAGRA_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_NAGRA_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_SUMA_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_SUMA_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_IRDETO_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_IRDETO_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_VMX_ULTRA_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_VMX_ULTRA_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_COMMON_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_COMMON_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_PLAYREADY_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_PLAYREADY_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_WIDEVINE_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_WIDEVINE_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_CHINADRM_KEY_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_CHINADRM_KEY_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_EMPTYDRM_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_EMPTYDRM_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_KEYMASTER_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_KEYMASTER_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_GATEKEEPER_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_GATEKEEPER_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_SSM_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_SSM_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_SSM_TEST_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_SSM_TEST_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_DYNAMIC_TA_LOAD)) ,y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_DYNAMIC_TA_LOAD
endif

ifeq ($(strip $(CFG_HI_TEE_NPU_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_NPU_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_NPU_TEST_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_NPU_TEST_SUPPORT
endif
