set(CONFIG_TA_64BIT false)
set(CONFIG_TA_32BIT true)
set(CONFIG_SSA_64BIT false)
set(CONFIG_GTASK_64BIT false)
set(CONFIG_RPMB_64BIT false)
set(CONFIG_SEM false)
set(CONFIG_ATTESTATION_TA false)
set(CONFIG_GATEKEEPER false)
set(CONFIG_KEYMASTER false)
set(CONFIG_ANTIROOT false)
set(CONFIG_SECISP false)
set(CONFIG_HISI_TIMER true)
set(CONFIG_PERMSRV_64BIT false)
set(CONFIG_PLATDRV_64BIT false)
set(CONFIG_DRV_TIMER_64BIT false)
set(CONFIG_DRV_64BIT false)
set(ENABLE_TA_LOAD_WHITE_BOX_KEY true)
set(CONFIG_HUK_PLAT_COMPATIBLE true)
set(CONFIG_HUK_SERVICE_32BIT true)
set(CONFIG_CIPHER_ENABLE true)
set(CONFIG_HISI_TIMER true)
set(CONFIG_TIMER_PERMISSION_DISABLE true)
set(CONFIG_TERMINAL_DRV_SUPPORT y)

set(BLOCKLIST libdevchip_api smmu otp cc_driver)

include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/${CHIP_NAME}/choose_config.cmake)

list(APPEND PRODUCT_RELEASE_64 devchip_api)
list(APPEND PRODUCT_RELEASE_32 devchip_api)

if ("${CFG_HI_TEE_COMMON_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_common.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_common.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_common.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_common.elf)
endif()
if ("${CFG_HI_TEE_DEMO_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 kms.elf)
list(APPEND PRODUCT_RELEASE_32 kms.elf)
list(APPEND PRODUCT_APPS_32 kms.elf)
list(APPEND PRODUCT_APPS_64 kms.elf)
endif()
if ("${CFG_HI_TEE_DEMUX_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_dmx.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_dmx.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_dmx.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_dmx.elf)
endif()
if ("${CFG_HI_TEE_HDMIRX_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_hdmirx.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_hdmirx.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_hdmirx.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_hdmirx.elf)
endif()
if ("${CFG_HI_TEE_HDMITX_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_hdmitx.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_hdmitx.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_hdmitx.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_hdmitx.elf)
endif()
if ("${CFG_HI_TEE_KEYSLOT_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_keyslot.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_keyslot.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_keyslot.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_keyslot.elf)
endif()
if ("${CFG_HI_TEE_KLAD_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_klad.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_klad.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_klad.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_klad.elf)
endif()
if ("${CFG_HI_TEE_NPU_TEST_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_npu_test.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_npu_test.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_npu_test.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_npu_test.elf)
endif()
if ("${CFG_HI_TEE_OTP_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_otp.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_otp.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_otp.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_otp.elf)
endif()
if ("${CFG_HI_TEE_PVR_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_pvr.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_pvr.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_pvr.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_pvr.elf)
endif()
if ("${CFG_HI_TEE_SMMU_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 smmu_task.elf)
list(APPEND PRODUCT_RELEASE_32 smmu_task.elf)
list(APPEND PRODUCT_APPS_32 smmu_task.elf)
list(APPEND PRODUCT_APPS_64 smmu_task.elf)
endif()
if ("${CFG_HI_TEE_SSM_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_ssm.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_ssm.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_ssm.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_ssm.elf)
endif()
if ("${CFG_HI_TEE_SSM_TEST_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_ssm_test.elf)
list(APPEND PRODUCT_RELEASE_64 task_hisi_ssm_test.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_ssm_test_2.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_ssm_test_2.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_ssm_test.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_ssm_test.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_ssm_test_2.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_ssm_test_2.elf)
endif()
if ("${CFG_HI_TEE_TEST_CIPHER_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_test_cipher.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_test_cipher.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_test_cipher.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_test_cipher.elf)
endif()
if ("${CFG_HI_TEE_VFMW_SUPPORT}" STREQUAL "y")
list(APPEND PRODUCT_RELEASE_64 task_hisi_vfmw.elf)
list(APPEND PRODUCT_RELEASE_32 task_hisi_vfmw.elf)
list(APPEND PRODUCT_APPS_32 task_hisi_vfmw.elf)
list(APPEND PRODUCT_APPS_64 task_hisi_vfmw.elf)
endif()

#list(APPEND PRODUCT_APPS_32 smmu_task.elf)
#list(APPEND PRODUCT_APPS_64 smmu_task.elf)
#list(APPEND PRODUCT_RELEASE_64 devchip_api)
#list(APPEND PRODUCT_RELEASE_32 devchip_api)
#include($(TOPDIR)/vendor/huanglong/devchip_apps/Makefile)

#list(APPEND PRODUCT_RELEASE_32 devchip_apps)
