
set(WITH_HUANGLONG_PLATFORM     "2")
set(WITH_CHIP_HI3716MV430N      "29")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_HUANGLONG_PLATFORM)
set(PLATFORM_NAME "huanglong")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "STB")
set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI3716MV430N=${WITH_CHIP_HI3716MV430N}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_HUANGLONG_PLATFORM=${WITH_HUANGLONG_PLATFORM}
)


