/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: plat_cfg defines
 * Create: 2020-03
 */
#include "plat_cfg.h"
#include "plat_cfg_public.h"
#include <plat_features.h>
#include "uart_register.h"

#ifndef __aarch64__
#error "Only aarch64 is supported!"
#endif

struct platform_info g_plat_cfg = {
    /* To config, set TRUSTEDCORE_PHY_TEXT_BASE in var.mkvalue is assigned in boot_kernel_on_current_cpu function */
    .phys_region_start = 0,
    /* 48 MB */
    .phys_region_size = TEEOS_MEM_SIZE,
    .uart_addr = UART_ADDR,
    .uart_type = UART_ENABLE_FLAG | PL011_TYPE,
    .shmem_offset = SHMEM_OFFSET,
    .shmem_size = SHMEM_SIZE,

    .gic_config = {
        .version = GIC_V3_VERSION,
        .v3 = {
            .dist = { REG_BASE_GIC_DIS, REG_BASE_GIC_DIS + GIC_DIST_PAGENUM * PAGE_SIZE },
            .redist_num = GIC_REDIST_NUM,
            .redist_stride = GIC_REDIST_MEMSIZE,
            .redist = {
                { REG_BASE_GIC_REDIS, REG_BASE_GIC_REDIS + GIC_REDIST_PAGENUM * PAGE_SIZE }
            }
        }
    },

    .spi_num_for_notify = SPI_NUM_FOR_NOTIFY,
    .plat_features = PLAT_DEF_ENG,
    /* at most PLAT_MAX_DEVIO_REGIONS (128) regions */
    .plat_io_regions = {
        { TIMER1_BASE,                TIMER1_BASE + TIMER1_BASE_SIZE },
        { REG_BASE_DDRC_PADDR,        REG_BASE_DDRC_PADDR + REG_SIZE_DDRC },
        { REG_BASE_TEE_CTRL_PADDR,    REG_BASE_TEE_CTRL_PADDR + REG_SIZE_TEE_CTRL },
        { REG_BASE_RNG_PADDR,         REG_BASE_RNG_PADDR + REG_SIZE_RNG },
        { REG_BASE_SPACC_PADDR,       REG_BASE_SPACC_PADDR + REG_SIZE_SPACC },
        { REG_BASE_KLAD_PADDR,        REG_BASE_KLAD_PADDR + REG_SIZE_KLAD },
        { REG_BASE_RKP_PADDR,         REG_BASE_RKP_PADDR + REG_SIZE_RKP },
        { REG_BASE_CERT_PADDR,        REG_BASE_CERT_PADDR + REG_SIZE_CERT },
        { REG_BASE_OTP_PADDR,         REG_BASE_OTP_PADDR + REG_SIZE_OTP },
        { REG_BASE_OTP_SHADOW_PADDR,  REG_BASE_OTP_SHADOW_PADDR + REG_SIZE_OTP_SHADOW },
        { REG_BASE_PKE_PADDR,         REG_BASE_PKE_PADDR + REG_SIZE_PKE },
        { REG_BASE_SYSRES_PADDR,      REG_BASE_SYSRES_PADDR + REG_SIZE_SYSRES },
        { REG_BASE_MDC0CFG,           REG_BASE_MDC0CFG + REG_SIZE_MDC0CFG },
        { REG_BASE_MDC0STA,           REG_BASE_MDC0STA + REG_SIZE_MDC0STA },
        { REG_BASE_MAILBOX_VMCU,      REG_BASE_MAILBOX_VMCU + REG_SIZE_MAILBOX_VMCU },
        { REG_BASE_MAILBOX_HPP,       REG_BASE_MAILBOX_HPP + REG_SIZE_MAILBOX_HPP },
        { REG_BASE_CRG,               REG_BASE_CRG + REG_SIZE_CRG },
        { REG_BASE_DMX,               REG_BASE_DMX + REG_SIZE_DMX },
        { REG_BASE_MDSC,              REG_BASE_MDSC + REG_SIZE_MDSC },
        { REG_BASE_DMX_IOMMU_TAG,     REG_BASE_DMX_IOMMU_TAG + REG_SIZE_DMX_IOMMU_TAG },
        { REG_BASE_TSCIPHER,          REG_BASE_TSCIPHER + REG_SIZE_TSCIPHER },
        { REG_BASE_TSCIPHER_IOMMU_TAG, REG_BASE_TSCIPHER_IOMMU_TAG + REG_SIZE_TSCIPHER_IOMMU_TAG },
        { REG_BASE_VMCU_IOMMU_TAG,    REG_BASE_VMCU_IOMMU_TAG + REG_SIZE_VMCU_IOMMU_TAG },
        { REG_BASE_VEDU_IOMMU_TAG,    REG_BASE_VEDU_IOMMU_TAG + REG_SIZE_VEDU_IOMMU_TAG },
        { REG_BASE_VICAP_IOMMU_TAG,   REG_BASE_VICAP_IOMMU_TAG + REG_SIZE_VICAP_IOMMU_TAG },
        { REG_BASE_VDH_IOMMU_TAG,     REG_BASE_VDH_IOMMU_TAG + REG_SIZE_VDH_IOMMU_TAG },
        { REG_BASE_VPSS_MAC_MMU_CTRL, REG_BASE_VPSS_MAC_MMU_CTRL + REG_SIZE_VPSS_MAC_MMU_CTRL },
        { REG_BASE_VPSS_IOMMU_TAG,    REG_BASE_VPSS_IOMMU_TAG + REG_SIZE_VPSS_IOMMU_TAG },
        { REG_BASE_VDP0_IOMMU_TAG,    REG_BASE_VDP0_IOMMU_TAG + REG_SIZE_VDP0_IOMMU_TAG },
        { REG_BASE_VDP1_IOMMU_TAG,    REG_BASE_VDP1_IOMMU_TAG + REG_SIZE_VDP1_IOMMU_TAG },
        { REG_BASE_VDP2_IOMMU_TAG,    REG_BASE_VDP2_IOMMU_TAG + REG_SIZE_VDP2_IOMMU_TAG },
        { REG_BASE_VDP_VID0_BASE_TAG, REG_BASE_VDP_VID0_BASE_TAG + REG_SIZE_VDP_VID0_BASE_TAG },
        { REG_BASE_VDP_VID1_BASE_TAG, REG_BASE_VDP_VID1_BASE_TAG + REG_SIZE_VDP_VID1_BASE_TAG },
        { PASTC_BSE_REG_PADDR,        PASTC_BSE_REG_PADDR + PASTC_BSE_SIZE },
        { REG_BASE_GFX2D_IOMMU_TAG,   REG_BASE_GFX2D_IOMMU_TAG + REG_SIZE_GFX2D_IOMMU_TAG },
        { REG_BASE_GPU,               REG_BASE_GPU + REG_SIZE_GPU },
        { REG_BASE_JPEGD_IOMMU_TAG,   REG_BASE_JPEGD_IOMMU_TAG + REG_SIZE_JPEGD_IOMMU_TAG },
        { REG_BASE_JPEGE_IOMMU_TAG,   REG_BASE_JPEGE_IOMMU_TAG + REG_SIZE_JPEGE_IOMMU_TAG },
        { REG_BASE_HDMITX0_PWD_TAG,   REG_BASE_HDMITX0_PWD_TAG + REG_SIZE_HDMITX0_PWD_TAG },
        { REG_BASE_HDMITX0_AON_TAG,   REG_BASE_HDMITX0_AON_TAG + REG_SIZE_HDMITX0_AON_TAG },
        { REG_BASE_HDMITX0_PHY_TAG,   REG_BASE_HDMITX0_PHY_TAG + REG_SIZE_HDMITX0_PHY_TAG },
        { REG_BASE_HDMITX1_PWD_TAG,   REG_BASE_HDMITX1_PWD_TAG + REG_SIZE_HDMITX1_PWD_TAG },
        { REG_BASE_HDMITX1_AON_TAG,   REG_BASE_HDMITX1_AON_TAG + REG_SIZE_HDMITX1_AON_TAG },
        { REG_BASE_HDMITX1_PHY_TAG,   REG_BASE_HDMITX1_PHY_TAG + REG_SIZE_HDMITX1_PHY_TAG },
        { REG_BASE_HDMIRX_CTRL0,      REG_BASE_HDMIRX_CTRL0 + REG_SIZE_HDMIRX_CTRL0 },
        { REG_BASE_HDMIRX_CTRL1,      REG_BASE_HDMIRX_CTRL1 + REG_SIZE_HDMIRX_CTRL1 },
        { REG_BASE_SYS_CTRL_PADDR,    REG_BASE_SYS_CTRL_PADDR + REG_SIZE_SYS_CTRL },
        { REG_BASE_NPU,               REG_BASE_NPU + REG_SIZE_NPU },
        { REG_BASE_GPIO_21,           REG_BASE_GPIO_21 + REG_SIZE_GPIO_21 },
        { REG_BASE_SYS_PERI,          REG_BASE_SYS_PERI + REG_SIZE_SYS_PERI },
        { REG_BASE_SYS_PMC,           REG_BASE_SYS_PMC + REG_SIZE_SYS_PMC },
        { 0, 0 }
}

};
