
WITH_HIGENERIC_PLATFORM := 7
WITH_CHIP_MIAMICW := 12

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_HIGENERIC_PLATFORM
	PLATFORM_NAME := higeneric
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := watch

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_MIAMICW=$(WITH_CHIP_MIAMICW) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_HIGENERIC_PLATFORM=$(WITH_HIGENERIC_PLATFORM)

