
set(WITH_CT_PLATFORM  "9")
set(WITH_CHIP_HI1213         "37")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_CT_PLATFORM)
set(PLATFORM_NAME "ct")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "ct")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI1213=${WITH_CHIP_HI1213}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_CT_PLATFORM=${WITH_CT_PLATFORM}
)

