/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: record the register mmap information.
 * Create: 2020-12-29
 */
#ifndef PLATDRV_IO_MAP_H
#define PLATDRV_IO_MAP_H

#include <plat_cfg.h>
#include <platdrv.h>
#include <mspe_ddr_layout.h>

struct ioaddr_t g_ioaddrs[] = {
    { HI_TSP_REG_BASE, HI_TSP_REG_SIZE },   /* HI_TSP_REG_BASE    2M */
    { SOC_ACPU_SCTRL_BASE_ADDR,    REG_BASE_SCTRL_SIZE },
    { EICC_PERI_REGBASE_ADDR, EICC_PERI_REGBASE_ADDR_SIZE },
    { EICC_MDM0_REGBASE_ADDR, EICC_MDM0_REGBASE_ADDR_SIZE },
    { MDM_LPMCU_TCM_ADDR, MDM_LPMCU_TCM_ADDR_SIZE },
    { SOC_ACPU_PERI_CRG_BASE_ADDR, REG_BASE_PERI_CRG_SIZE },
    { SOC_ACPU_PCTRL_BASE_ADDR, REG_BASE_PCTRL_SIZE }, /* PCTRL_BASE */
    { SOC_ACPU_MEDIA1_CRG_BASE_ADDR, REG_BASE_MEDIA1_CRG_SIZE }, /* MEDIA1_CRG_BASE */
    { SOC_ACPU_SYS_CNT_BASE_ADDR, SOC_ACPU_SYS_CNT_BASE_ADDR_SIZE },
    { SOC_ACPU_PMC_BASE_ADDR, SOC_ACPU_PMC_BASE_ADDR_SIZE },
    { SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR_SIZE },

    { SOC_ACPU_DMC_0_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR_SIZE },
    { SOC_ACPU_HIEPS_BASE_ADDR, SOC_ACPU_HIEPS_BASE_ADDR_SIZE },
    { MSPE_DDR_REGION_IO_BASE, MSPE_DDR_REGION_IO_SIZE },
    /* file encry */
#ifdef TEE_SUPPORT_FILE_ENCRY
    { SOC_ACPU_UFS_HCI_BASE_ADDR, SOC_ACPU_UFS_HCI_BASE_ADDR_SIZE },
#endif
    { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR_SIZE },
    { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
    { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR_SIZE },
    { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR_SIZE },
    { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR_SIZE },
    { SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO27_BASE_ADDR, SOC_ACPU_GPIO27_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO28_BASE_ADDR, SOC_ACPU_GPIO28_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO26_BASE_ADDR, SOC_ACPU_GPIO26_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO31_BASE_ADDR, SOC_ACPU_GPIO31_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO32_BASE_ADDR, SOC_ACPU_GPIO32_BASE_ADDR_SIZE },
    { SOC_ACPU_IOMCU_CONFIG_BASE_ADDR, SOC_ACPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
    { SOC_ACPU_AO_TZPC_BASE_ADDR, SOC_ACPU_AO_TZPC_BASE_ADDR_SIZE },
    /* DSS Reg Map */
    { DSS_BASE, DSS_BASE_SIZE },
    /* DSS GPIO Map */
    { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO1_BASE_ADDR, SOC_ACPU_GPIO1_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO2_BASE_ADDR, SOC_ACPU_GPIO2_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO3_BASE_ADDR, SOC_ACPU_GPIO3_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO23_BASE_ADDR, SOC_ACPU_GPIO23_BASE_ADDR_SIZE },
    { SOC_ACPU_GPIO25_BASE_ADDR, SOC_ACPU_GPIO25_BASE_ADDR_SIZE },
    { SMMUV3_SDMA_BASE_ADDR, SMMUV3_SDMA_BASE_ADDR_SIZE },
    { TS_DOORBELL_BASE_ADDR, TS_DOORBELL_BASE_ADDR_SIZE },
    { TS_SRAM_BASE_ADDR, TS_SRAM_BASE_ADDR_SIZE },
};

#endif
