TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_HI3670
TRUSTEDCORE_PHY_TEXT_BASE := 0x1CE08000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x1D600000
TRUSTEDCORE_PLATFORM_FLAGS += -DFEATURE_SE
GATEKEEPER_ITRATION_TIMES := 125
DERIVE_ROOT_INTERNAL_ITRATIONS := 4
