
set(WITH_QEMU_PLATFORM     "8")
set(WITH_CHIP_XINGTIAN     "31")
set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_QEMU_PLATFORM)
set(PLATFORM_NAME "qemu")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "qemu")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_XINGTIAN=${WITH_CHIP_XINGTIAN}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_QEMU_PLATFORM=${WITH_QEMU_PLATFORM}
)

