
WITH_TI_PLATFORM := 11
WITH_CHIP_TDA4 := 1

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_TI_PLATFORM
	PLATFORM_NAME := ti
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
         PRODUCT_NAME  := mdc
export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_TDA4=$(WITH_CHIP_TDA4) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_TI_PLATFORM=$(WITH_TI_PLATFORM)

