
set(WITH_KUNPENG_PLATFORM     "3")
set(WITH_CHIP_HI1620          "15")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_KUNPENG_PLATFORM)
set(PLATFORM_NAME "kunpeng")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "kunpeng")


set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI1620=${WITH_CHIP_HI1620}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_KUNPENG_PLATFORM=${WITH_KUNPENG_PLATFORM}
)


