TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_BURBANK
TRUSTEDCORE_PHY_TEXT_BASE := 0x13208000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x13A00000
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY_V3
TRUSTEDCORE_PLATFORM_FLAGS += -DCC_POWER_IN_SECOS
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_HIAI
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_HIAI_DYN_ION
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_VLTMM_SRV
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_MODEM_DYN_LOAD
GATEKEEPER_ITRATION_TIMES := 0
DERIVE_ROOT_INTERNAL_ITRATIONS := 0

ifeq ($(es_low_freq), true)
TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_ES_LOW_FREQ
$(warning "the chip is CONFIG_ES_LOW_FREQ")
endif
