set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_BURBANK
set(TRUSTEDCORE_PHY_TEXT_BASE 0x13208000
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13A00000
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_FILE_ENCRY
    -DTEE_SUPPORT_FILE_ENCRY_V3
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_VLTMM_SRV
)
set(GATEKEEPER_ITRATION_TIMES 0)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 0)