/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Description: the error number definition for secure flash module
 * Author : security-bsp
 * Create : 2019/8/30
 */
#ifndef __SECUREFLASH_ERRNO_H__
#define __SECUREFLASH_ERRNO_H__

#define SECURE_FLASH_RET_SUCC    0x0
#define SECURE_FLASH_BASE_DERIVED_BINDING_KEY 0x20

#define SECURE_FLASH_RET_ERR_1   0x1
#define SECURE_FLASH_RET_ERR_2   0x2
#define SECURE_FLASH_RET_ERR_3   0x3
#define SECURE_FLASH_RET_ERR_4   0x4
#define SECURE_FLASH_RET_ERR_5   0x5
#define SECURE_FLASH_RET_ERR_6   0x6
#define SECURE_FLASH_RET_ERR_7   0x7
#define SECURE_FLASH_RET_ERR_8   0x8
#define SECURE_FLASH_RET_ERR_9   0x9
#define SECURE_FLASH_RET_ERR_10  0xA
#define SECURE_FLASH_RET_DEVICE_ABSENCE  0xB
#define SECURE_FLASH_RET_ROOTKEY_DERIVED_ERR 0x0C

#define SECURE_FLASH_RET_BASE      0x85000000
#define SECURE_FLASH_RET_DISTANCE  0x2000
#define SECURE_FLASH_MODID_MASK    0x3
#define SECURE_FLASH_RET_DISTANCE_MASK  0x1FFF

enum secure_flash_module_layer_id {
    SECURE_STORAGE_LAYER_ID = 0,
    FACTORY_TEST_LAYER_ID = 1,
    DATA_LINK_LAYER_ID = 2,
    APPLICATION_LAYER_ID = 3
};

#define SECURE_FLASH_ERRCODE(mod_id, err) \
(((err) != SECURE_FLASH_RET_SUCC) ?\
 (SECURE_FLASH_RET_BASE + ((mod_id) & SECURE_FLASH_MODID_MASK) * SECURE_FLASH_RET_DISTANCE +\
 ((err) & SECURE_FLASH_RET_DISTANCE_MASK)) : SECURE_FLASH_RET_SUCC)

#define FACTORY_TEST_LAYER_ERRCODE(err) \
SECURE_FLASH_ERRCODE(FACTORY_TEST_LAYER_ID, (err))

#endif

