/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: plat_cfg defines
 * Create: 2020-03
 */
#include "plat_cfg.h"
#include "plat_cfg_public.h"
#include <plat_features.h>
#include <hisi_platform.h>
#include "uart_register.h"
#ifndef __aarch64__
#error "Only aarch64 is supported!"
#endif

struct platform_info g_plat_cfg = {

    /* value is assigned in boot_kernel_on_current_cpu function */
    .phys_region_start    = 0,
    .phys_region_size     = TEEOS_MEM_SIZE,
    .uart_addr = UART_ADDR,
    .uart_type = UART_DISABLE_FLAG | PL011_TYPE,
    .shmem_offset = SHMEM_OFFSET,
    .shmem_size           = SHMEM_SIZE,
/*
 * refer to device/hisi/customize/dtsi/arm64/kirin980/kirin980_memory.dtsi
 * and trustedcore_hm/libs/libplatdrv/platform/libthirdparty_drv/include/atf_memory.h
 */
    .protected_regions = { { PROTECTED_REGION_START1, PROTECTED_REGION_END1 },
                           { PROTECTED_REGION_START2, PROTECTED_REGION_END2 } },

    .gic_config = {
        .version = GIC_V3_VERSION,
        .v3 = {
            .dist = { GIC_V3_DIST_ADDR, GIC_V3_DIST_ADDR + GIC_DIST_PAGENUM * PAGE_SIZE },
            .redist_num = GIC_REDIST_NUM,
            .redist_stride = GIC_REDIST_MEMSIZE,
            .redist = {
                { GIC_V3_REDIST_ADDR, GIC_V3_REDIST_ADDR + GIC_REDIST_PAGENUM * PAGE_SIZE }
            }
        }
    },

    .spi_num_for_notify    = SPI_NUM,

    .plat_features = PLAT_DEF_ENG
#ifdef CONFIG_ARM64_PAN
    | PLAT_ENABLE_PAN
#endif
    ,
    /* at most PLAT_MAX_DEVIO_REGIONS (128) regions, the first region should be UART6 */
    .plat_io_regions = {
        /* .start,     .end */
        { TIMER1_BASE, TIMER1_BASE + TIMER1_BASE_SIZE },
        { TIMER7_BASE, TIMER7_BASE + TIMER7_BASE_SIZE },
        { RTC_BASE_ADDR, RTC_BASE_ADDR + RTC_BASE_ADDR_SIZE },
        { REG_BASE_SCTRL, REG_BASE_SCTRL + REG_BASE_SCTRL_SIZE },
        { REG_BASE_PERI_CRG, REG_BASE_PERI_CRG + REG_BASE_PERI_CRG_SIZE },
        { REG_BASE_PCTRL, REG_BASE_PCTRL + REG_BASE_PCTRL_SIZE },
        { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR  + SOC_ACPU_DMSS_BASE_ADDR_SIZE },
        { DSS_BASE, DSS_BASE + DSS_BASE_SIZE },
        { PCTRL_BASE, PCTRL_BASE + PCTRL_BASE_SIZE },
        { MMBUF_CFG_BASE, MMBUF_CFG_BASE + MMBUF_CFG_BASE_SIZE },
        { NOC_DSS_BASE, NOC_DSS_BASE + NOC_DSS_BASE_SIZE },
        { PMC_BASE, PMC_BASE + PMC_BASE_SIZE },
        { GPIO_SPI, GPIO_SPI + GPIO_SPI_SIZE },
        { TZPC, TZPC + TZPC_SIZE },
        { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR + SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
        { CRG_BASE, CRG_BASE + CRG_BASE_SIZE },
        { SOC_ACPU_GPIO6_BASE_ADDR, SOC_ACPU_GPIO6_BASE_ADDR + SOC_ACPU_GPIO6_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO25_BASE_ADDR, SOC_ACPU_GPIO25_BASE_ADDR + SOC_ACPU_GPIO25_BASE_ADDR_SIZE },
        { SOC_ACPU_ISP_CORE_CFG_BASE_ADDR, SOC_ACPU_ISP_CORE_CFG_BASE_ADDR  + SOC_ACPU_ISP_CORE_CFG_BASE_ADDR_SIZE },
        { MEDIA_CRG_BASE_ADDR, MEDIA_CRG_BASE_ADDR + MEDIA_CRG_BASE_ADDR_SIZE },
        { HIFI_CFG_BASE_ADDR, HIFI_CFG_BASE_ADDR + HIFI_CFG_BASE_ADDR_SIZE },
        { HI_IPCM_REGBASE_ADDR, HI_IPCM_REGBASE_ADDR + HI_IPCM_REGBASE_ADDR_SIZE },
        { HI_SYSCTRL_BASE_ADDR, HI_SYSCTRL_BASE_ADDR + HI_SYSCTRL_BASE_ADDR_SIZE },
        { HI_WDT_BASE_ADDR_VIRT, HI_WDT_BASE_ADDR_VIRT + HI_WDT_BASE_ADDR_VIRT_SIZE },
        { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR + SOC_ACPU_SCTRL_BASE_ADDR_SIZE },
        { SECBOOT_XX, SECBOOT_XX + SECBOOT_XX_SIZE },
        { RESET_PIN_GPIO_ADDR, RESET_PIN_GPIO_ADDR + RESET_PIN_GPIO_ADDR_SIZE },
        { FINGERPRINT_XX, FINGERPRINT_XX + FINGERPRINT_XX_SIZE },
        { SOC_ACPU_CSSYS_APB_BASE_ADDR, SOC_ACPU_CSSYS_APB_BASE_ADDR + SOC_ACPU_CSSYS_APB_BASE_ADDR_SIZE },
        { SOC_ACPU_I2C7_BASE_ADDR, SOC_ACPU_I2C7_BASE_ADDR + SOC_ACPU_I2C7_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR + SOC_ACPU_SPI1_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO01_DIRECT_BASE_ADDR, SOC_ACPU_GPIO01_DIRECT_BASE_ADDR + SOC_ACPU_GPIO01_DIRECT_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO16_BASE_ADDR, SOC_ACPU_GPIO16_BASE_ADDR + SOC_ACPU_GPIO16_BASE_ADDR_SIZE },
        { CAMBRICON_X1, CAMBRICON_X1 + CAMBRICON_X1_SIZE },
        { CAMBRICON_X2, CAMBRICON_X2 + CAMBRICON_X2_SIZE },
        { DX_BASE_CC, DX_BASE_CC + DX_BASE_CC_SIZE },
        { DX_BASE_ATLANTA, DX_BASE_ATLANTA + DX_BASE_ATL_SIZE },
        { HISEE_MBOX_BASE_ADDR, HISEE_MBOX_BASE_ADDR + HISEE_MBOX_BASE_ADDR_SIZE },
        { HISEE_IPC_BASE_ADDR, HISEE_IPC_BASE_ADDR + HISEE_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_VENC_BASE_ADDR, SOC_ACPU_VENC_BASE_ADDR + SOC_ACPU_VENC_BASE_ADDR_SIZE },
        { SOC_ACPU_VDEC_BASE_ADDR, SOC_ACPU_VDEC_BASE_ADDR + SOC_ACPU_VDEC_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR + SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_CONFIG_BASE_ADDR, SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + SOC_ACPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_DMAC_BASE_ADDR, SOC_ACPU_IOMCU_DMAC_BASE_ADDR + SOC_ACPU_IOMCU_DMAC_BASE_ADDR_SIZE },
#ifdef TEE_SUPPORT_FILE_ENCRY
        { SOC_ACPU_UFS_CFG_BASE_ADDR, SOC_ACPU_UFS_CFG_BASE_ADDR + SOC_ACPU_UFS_CFG_BASE_ADDR_SIZE },
#endif

        { HDCP13_ADDR, HDCP13_ADDR + HDCP13_ADDR_SIZE },
        { HDCP22_ADDR, HDCP22_ADDR + HDCP22_ADDR_SIZE },
        { SOC_ACPU_GPIO4_BASE_ADDR, SOC_ACPU_GPIO4_BASE_ADDR + SOC_ACPU_GPIO4_BASE_ADDR_SIZE },
        { SENSORHUB_IPC_BASE_ADDR, SENSORHUB_IPC_BASE_ADDR + SENSORHUB_IPC_BASE_ADDR_SIZE },
        { SOC_IVP_IMAGE_BASE_ADDR, SOC_IVP_IMAGE_BASE_ADDR + SOC_IVP_IMAGE_BASE_ADDR_SIZE },

        { SOCP_BASE_ADDR, SOCP_BASE_ADDR + SOCP_BASE_ADDR_SIZE },

         /* this is terminator */
        { 0, 0 }
}

};
