
set(WITH_BALONG_PLATFORM     "5")
set(WITH_CHIP_HI6965        "34")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_BALONG_PLATFORM)
set(PLATFORM_NAME "balong")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "balong")


set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI6965=${WITH_CHIP_HI6965}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_BALONG_PLATFORM=${WITH_BALONG_PLATFORM}
)


