set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_KIRIN990)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x22808000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x23000000)
set(GATEKEEPER_ITRATION_TIMES 400)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)
if ("${chip_type}" STREQUAL "cs2")
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
        -DWITH_KIRIN990_CS2
    )
else()
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
        -DWITH_KIRIN990_CS
    )
endif()

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DCONFIG_PRODUCT_ARMPC
    -DTEE_SUPPORT_FILE_ENCRY
    -DCONFIG_HISEE_14_CHANNEL_IPC
    -DCC_POWER_IN_SECOS
)
