# platform compile rules
# Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.

TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_KIRIN990
TRUSTEDCORE_PHY_TEXT_BASE := 0x22808000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x23000000
GATEKEEPER_ITRATION_TIMES := 400
DERIVE_ROOT_INTERNAL_ITRATIONS := 4
ifneq ($(chip_type),cs2)
TRUSTEDCORE_PLATFORM_FLAGS += -DWITH_KIRIN990_CS
else
TRUSTEDCORE_PLATFORM_FLAGS += -DWITH_KIRIN990_CS2
endif

TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_PRODUCT_ARMPC
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY
TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_HISEE_14_CHANNEL_IPC
TRUSTEDCORE_PLATFORM_FLAGS += -DCC_POWER_IN_SECOS
