
set(WITH_HIGENERIC_PLATFORM     "7")
set(WITH_CHIP_LEXINGTON        "28")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_HIGENERIC_PLATFORM)
set(PLATFORM_NAME "higeneric")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "phone")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_LEXINGTON=${WITH_CHIP_LEXINGTON}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_HIGENERIC_PLATFORM=${WITH_HIGENERIC_PLATFORM}
)

