TARGETS := libgic.a

CFILES += libgic/gic_v2.c libgic/gic_v3.c
CFLAGS += -fstack-protector-strong

LDFLAGS += -r

CFLAGS += -Wall -Wextra -Werror

override CFLAGS := $(filter-out -march=armv8-a+nofp, $(CFLAGS)) -march=armv8-a

libs-y += libgic
include ${KERNEL_ROOT_PATH}/module.mk
