TARGETS := libversion.a

CFILES += libversion/tee_version.c
CFLAGS += -fstack-protector-strong

LDFLAGS += -r

CFLAGS += -Wall -Wextra -Werror

override CFLAGS := $(filter-out -march=armv8-a+nofp, $(CFLAGS)) -march=armv8-a

libs-y += libversion
include ${KERNEL_ROOT_PATH}/module.mk
