TARGETS := libuart.a

CFILES := libuart/io_output.c \
          libuart/uart_register.c \
          libuart/pl011/pl011.c \
          libuart/pl011_general/pl011_general.c \
          libuart/pl011_v500/pl011_v500.c \
          libuart/uart_lpc/uart_lpc.c

CFLAGS += -fstack-protector-strong

LDFLAGS += -r

CFLAGS += -Wall -Wextra -Werror

override CFLAGS := $(filter-out -march=armv8-a+nofp, $(CFLAGS)) -march=armv8-a

libs-y += libuart
include ${KERNEL_ROOT_PATH}/module.mk

