set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_LAGUNA
set(TRUSTEDCORE_PHY_TEXT_BASE 0x13008000
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13800000
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DTEE_SUPPORT_FILE_ENCRY
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_MODEM_DYN_LOAD
)
set(GATEKEEPER_ITRATION_TIMES 0)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 0)
