set(CONFIG_TUI_32BIT true)
set(CONFIG_TA_64BIT false)
set(CONFIG_SSA_64BIT false)
set(CONFIG_GTASK_64BIT false)
set(CONFIG_PERMSRV_64BIT false)
set(CONFIG_RPMB_64BIT false)
set(CONFIG_SEM true)
set(CONFIG_BIO true)
set(CONFIG_ROT true)
set(CONFIG_ART true)
set(ENABLE_CPP true)
set(ENABLE_CPP_STATIC true)
set(CONFIG_SE_SERVICE_32BIT true)
set(CONFIG_GATEKEEPER_32BIT true)
set(CONFIG_KEYMASTER_32BIT true)
set(CONFIG_ANTIROOT true)
set(CONFIG_WEAVER true)
set(CONFIG_PERMSRV_64BIT false)
set(CONFIG_PLATDRV_64BIT false)
set(CONFIG_DRV_TIMER_64BIT false)
set(CONFIG_DRV_64BIT false)
set(CONFIG_DX_ENABLE true)
set(CONFIG_GMLIB_IMPORT true)
set(CONFIG_HUK_SERVICE_32BIT true)
set(ENABLE_TA_LOAD_WHITE_BOX_KEY false)

if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 secmem.elf file_encry.elf hivcodec.elf bdkernel.elf)
else()
    list(APPEND PRODUCT_RELEASE_64 secmem.elf file_encry.elf hivcodec.elf bdkernel.elf)
    list(APPEND PRODUCT_RELEASE_32 secmem.elf file_encry.elf hivcodec.elf bdkernel.elf)
endif()

if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
    list(APPEND PRODUCT_APPS_32 secmem.elf file_encry.elf hivcodec.elf bdkernel.elf)
endif()
if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_64 secmem.elf file_encry.elf hivcodec.elf bdkernel.elf)
endif()
