/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: plat_cfg defines
 * Create: 2020-03
 */
#include <autoconf.h>
#include "plat_cfg.h"
#include "plat_cfg_public.h"
#include <plat_features.h>
#include <hisi_platform.h>
#include "uart_register.h"

#ifndef __aarch64__
#error "Only aarch64 is supported!"
#endif

struct platform_info g_plat_cfg = {

    /* value is assigned in boot_kernel_on_current_cpu function */
    .phys_region_start    = 0,
    .phys_region_size     = TEEOS_MEM_SIZE,
    .uart_addr = UART_ADDR,
    .uart_type = UART_DISABLE_FLAG | PL011_TYPE,
    .shmem_offset = SHMEM_OFFSET,
    .shmem_size           = SHMEM_SIZE,
    /* refer to device/hisi/customize/dtsi/arm64/denver/denver_memory.dtsi bl31 memory space */
    .protected_regions = { { PROTECTED_REGION_START1, PROTECTED_REGION_END1 },
                           { PROTECTED_REGION_START2, PROTECTED_REGION_END2 } },

    .gic_config = {
        .version = GIC_V3_VERSION,
        .v3 = {
            .dist = { GIC_V3_DIST_ADDR, GIC_V3_DIST_ADDR + GIC_DIST_PAGENUM * PAGE_SIZE },
            .redist_num = GIC_REDIST_NUM,
            .redist_stride = GIC_REDIST_MEMSIZE,
            .redist = {
                { GIC_V3_REDIST_ADDR, GIC_V3_REDIST_ADDR + GIC_REDIST_PAGENUM * PAGE_SIZE }
            }
        }
    },

    .spi_num_for_notify    = SPI_NUM,

    .plat_features = PLAT_DEF_ENG
#ifdef CONFIG_ARM64_PAN
    | PLAT_ENABLE_PAN
#endif
    ,
    /* at most PLAT_MAX_DEVIO_REGIONS (128) regionsi, the first region should be UART6 */
    .plat_io_regions = {
        /* .start,     .end */
        /* GPIO 0 denver */
        { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR + SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO5_BASE_ADDR, SOC_ACPU_GPIO5_BASE_ADDR + SOC_ACPU_GPIO5_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO9_BASE_ADDR, SOC_ACPU_GPIO9_BASE_ADDR + SOC_ACPU_GPIO9_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO28_BASE_ADDR, SOC_ACPU_GPIO28_BASE_ADDR + SOC_ACPU_GPIO28_BASE_ADDR_SIZE },
        { SOC_CPU_IOMCU_CONFIG_BASE_ADDR, SOC_CPU_IOMCU_CONFIG_BASE_ADDR + SOC_CPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR + SOC_ACPU_AO_IOC_BASE_ADDR_SIZE },
        { SOC_ACPU_IOC_BASE_ADDR, SOC_ACPU_IOC_BASE_ADDR + SOC_ACPU_IOC_BASE_ADDR_SIZE },
        /* GPIO 2 denver */
        { SOC_ACPU_GPIO2_BASE_ADDR, SOC_ACPU_GPIO2_BASE_ADDR + SOC_ACPU_GPIO2_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO22_BASE_ADDR, SOC_ACPU_GPIO22_BASE_ADDR + SOC_ACPU_GPIO22_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO23_BASE_ADDR, SOC_ACPU_GPIO23_BASE_ADDR + SOC_ACPU_GPIO23_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO24_BASE_ADDR, SOC_ACPU_GPIO24_BASE_ADDR + SOC_ACPU_GPIO24_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO27_BASE_ADDR, SOC_ACPU_GPIO27_BASE_ADDR + SOC_ACPU_GPIO27_BASE_ADDR_SIZE },
        /* IOMCU denver */
        { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR + SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_DMAC_BASE_ADDR, SOC_ACPU_IOMCU_DMAC_BASE_ADDR + SOC_ACPU_IOMCU_DMAC_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR + SOC_ACPU_SPI1_BASE_ADDR_SIZE },
        { SOC_ACPU_I2C7_BASE_ADDR, SOC_ACPU_I2C7_BASE_ADDR + SOC_ACPU_I2C7_BASE_ADDR_SIZE },
        { TZPC, TZPC + TZPC_SIZE },
        { AO_TZPC, AO_TZPC + AO_TZPC_SIZE },
        /* SPI3 denver */
        { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR + SOC_ACPU_SPI3_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR + SOC_ACPU_SPI4_BASE_ADDR_SIZE },
        { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR + SOC_ACPU_I3C4_BASE_ADDR_SIZE },
        { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR + SOC_ACPU_SCTRL_BASE_ADDR_SIZE },
        /* TIMER denver */
        { TIMER1_BASE, TIMER1_BASE + TIMER1_BASE_SIZE },
        { TIMER7_BASE, TIMER7_BASE + TIMER7_BASE_SIZE },
        { SOC_ACPU_GPIO1_SE_BASE_ADDR, SOC_ACPU_GPIO1_SE_BASE_ADDR + SOC_ACPU_GPIO1_SE_BASE_ADDR_SIZE },
        { RTC_BASE_ADDR, RTC_BASE_ADDR + RTC_BASE_ADDR_SIZE },
        { REG_BASE_SCTRL, REG_BASE_SCTRL + REG_BASE_SCTRL_SIZE },
        { REG_BASE_PERI_CRG, REG_BASE_PERI_CRG + REG_BASE_PERI_CRG_SIZE },
        { REG_BASE_PCTRL, REG_BASE_PCTRL + REG_BASE_PCTRL_SIZE },
        { HI_SYSCTRL_BASE_ADDR, HI_SYSCTRL_BASE_ADDR + HI_SYSCTRL_BASE_ADDR_SIZE },
        { HI_WDT_BASE_ADDR_VIRT, HI_WDT_BASE_ADDR_VIRT + HI_WDT_BASE_ADDR_VIRT_SIZE },
        /* CAMBRICON denver */
        { CAMBRICON_X1, CAMBRICON_X1 + CAMBRICON_X1_SIZE },
        { CAMBRICON_X2, CAMBRICON_X2 + CAMBRICON_X2_SIZE },
        { DX_BASE_CC, DX_BASE_CC + DX_BASE_CC_SIZE },
        { DX_BASE_ATLANTA, DX_BASE_ATLANTA + DX_BASE_ATL_SIZE },
        /* HISEE_MBOX denver */
        { HISEE_MBOX_BASE_ADDR, HISEE_MBOX_BASE_ADDR + HISEE_MBOX_BASE_ADDR_SIZE },
        { HISEE_IPC_BASE_ADDR, HISEE_IPC_BASE_ADDR + HISEE_IPC_BASE_ADDR_SIZE },
        { HI_IPCM_REGBASE_ADDR, HI_IPCM_REGBASE_ADDR + HI_IPCM_REGBASE_ADDR_SIZE },
        { SOCP_BASE_ADDR, SOCP_BASE_ADDR + SOCP_BASE_ADDR_SIZE },
        { HIFI_CFG_BASE_ADDR, HIFI_CFG_BASE_ADDR + HIFI_CFG_BASE_ADDR_SIZE },
        /* HDCP_ADDR denver */
        { HDCP13_ADDR, HDCP13_ADDR + HDCP13_ADDR_SIZE },
        { HDCP22_ADDR, HDCP22_ADDR + HDCP22_ADDR_SIZE },

        /* DSS Reg Base */
        { DSS_BASE, DSS_BASE + DSS_BASE_SIZE },
        { PCTRL_BASE, PCTRL_BASE + PCTRL_BASE_SIZE },
        { MMBUF_CFG_BASE, MMBUF_CFG_BASE + MMBUF_CFG_BASE_SIZE },
        { NOC_DSS_BASE, NOC_DSS_BASE + NOC_DSS_BASE_SIZE },
        { PMC_BASE, PMC_BASE + PMC_BASE_SIZE },
        /* SOC_ACPU denver */
#ifdef TEE_SUPPORT_FILE_ENCRY
        { SOC_ACPU_UFS_CFG_BASE_ADDR, SOC_ACPU_UFS_CFG_BASE_ADDR + SOC_ACPU_UFS_CFG_BASE_ADDR_SIZE },
#endif
        { SOC_ACPU_PERI_CRG_BASE_ADDR, SOC_ACPU_PERI_CRG_BASE_ADDR + SOC_ACPU_PERI_CRG_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_0_BASE_ADDR, SOC_ACPU_DMC_0_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_1_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR  + SOC_ACPU_DMSS_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_NS_BASE_ADDR, SOC_ACPU_IPC_NS_BASE_ADDR + SOC_ACPU_IPC_NS_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR + SOC_ACPU_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_TIMER10_BASE_ADDR, SOC_ACPU_TIMER10_BASE_ADDR + SOC_ACPU_TIMER10_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_IPC_S_BASE_ADDR, SOC_ACPU_AO_IPC_S_BASE_ADDR + SOC_ACPU_AO_IPC_S_BASE_ADDR_SIZE },
        { SOC_ACPU_ISP_CORE_CFG_BASE_ADDR, SOC_ACPU_ISP_CORE_CFG_BASE_ADDR  + SOC_ACPU_ISP_CORE_CFG_BASE_ADDR_SIZE },
        /* MEDIA_CRG denver */
        { MEDIA_CRG_BASE_ADDR, MEDIA_CRG_BASE_ADDR + MEDIA_CRG_BASE_ADDR_SIZE },
        { SOC_ACPU_VDEC_BASE_ADDR, SOC_ACPU_VDEC_BASE_ADDR + SOC_ACPU_VDEC_BASE_ADDR_SIZE },
        { SMMUV3_SDMA_BASE_ADDR, SMMUV3_SDMA_BASE_ADDR + SMMUV3_SDMA_BASE_ADDR_SIZE },
        { TS_DOORBELL_BASE_ADDR, TS_DOORBELL_BASE_ADDR + TS_DOORBELL_BASE_ADDR_SIZE },
        { TS_SRAM_BASE_ADDR, TS_SRAM_BASE_ADDR + TS_SRAM_BASE_ADDR_SIZE },
        { 0, 0 } /* this is terminator */
    }
};
