list(APPEND TEE_C_FLAGS
    -DTEE_SUPPORT_ATTESTATION_TA
    -DTEE_SUPPORT_TZMP2
    -DTEE_SUPPORT_HIVCODEC
)

if ("${WITH_ENG_VERSION}" STREQUAL "true")
    list(APPEND TEE_C_FLAGS
        -DVCODEC_ENG_VERSION
    )
endif()

set(WITH_MODEM false)
