export CONFIG_TA_64BIT := true
export CONFIG_SSA_64BIT := true
export CONFIG_GTASK_64BIT := true
export ENABLE_CPP := true
export ENABLE_CPP_STATIC := true
export CONFIG_PERMSRV_64BIT := true
export CONFIG_GMLIB_IMPORT := true
export CONFIG_TRNG_ENABLE := true
export CONFIG_TIMER_FREERUNNING_FIQ_DISABLE := true
export ENABLE_TA_LOAD_WHITE_BOX_KEY := true
export CONFIG_HUK_SERVICE_64BIT := true
export CONFIG_CRYPTO_SUPPORT_X509 := true
export CONFIG_CRYPTO_ECC_WRAPPER := true
export CONFIG_CRYPTO_AES_WRAPPER := true
export CONFIG_TA_LOCAL_SIGN := true
export CONFIG_BOOT_ARGS_TRANSFER := true
export CONFIG_TEE_DRV_SERVER_64BIT := true
export CONFIG_DYN_CONF := true
export CONFIG_TEE_MISC_DRIVER_64BIT := true
export CONFIG_NO_PLATCFG_EMBEDDED := true
export CONFIG_NO_VENDOR_LIB_EMBEDDED := true

include $(PLATFORM_DIR)/$(PLATFORM_NAME)/$(PRODUCT_NAME)/$(CHIP_NAME)/modules/modules.mk
