/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: record the register mmap information.
 * Create: 2020-03
 */
#ifndef PLATDRV_IO_MAP_H
#define PLATDRV_IO_MAP_H

#include <plat_cfg.h>
#include <platdrv.h>
#include "hisi_platform.h"

struct ioaddr_t g_ioaddrs[] = {
    { SOC_ACPU_IOMCU_DMAC_BASE_ADDR, SOC_ACPU_IOMCU_DMAC_BASE_ADDR_SIZE },
    { FINGERPRINT_XX, FINGERPRINT_XX_SIZE },
    { SOC_ACPU_GPIO28_BASE_ADDR, SOC_ACPU_GPIO28_BASE_ADDR_SIZE },
    { HIEPS_CDRM_BASE_ADDR, HIEPS_CDRM_ADDR_SIZE },
    { SOC_ACPU_EPS_MMU_BASE_ADDR, SOC_ACPU_EPS_MMU_BASE_SIZE },
    { SOC_ACPU_EPS_PKE2_BASE_ADDR, SOC_ACPU_EPS_PKE2_BASE_SIZE },
    { SOC_ACPU_EPS_PKE_BASE_ADDR, SOC_ACPU_EPS_PKE_BASE_SIZE },
    { SOC_ACPU_EPS_SCE_BASE_ADDR, SOC_ACPU_EPS_SCE_BASE_SIZE },
    { SOC_ACPU_EPS_KM_BASE_ADDR, SOC_ACPU_EPS_KM_BASE_SIZE },
    { SOC_ACPU_EPS_SCE2_BASE_ADDR, SOC_ACPU_EPS_SCE2_BASE_SIZE },
    { SOC_ACPU_EPS_TIMER_BASE_ADDR, SOC_ACPU_EPS_TIMER_BASE_SIZE },
    { SOC_ACPU_EPS_TRNG_BASE_ADDR, SOC_ACPU_EPS_TRNG_BASE_SIZE },
    { SOC_ACPU_EPS_ETZPC_BASE_ADDR, SOC_ACPU_EPS_ETZPC_BASE_SIZE },
    { SOC_ACPU_EPS_CONFIG_BASE_ADDR, SOC_ACPU_EPS_CONFIG_BASE_SIZE },
    { SOC_ACPU_MEDIA2_CRG_BASE_ADDR, SOC_ACPU_MEDIA2_CRG_BASE_SIZE },
    { ACPU_SYS_CNT_BASE_ADDR, ACPU_SYS_CNT_BASE_ADDR_SIZE },
    { SOC_ACPU_IPC_NS_BASE_ADDR, SOC_ACPU_IPC_NS_BASE_ADDR_SIZE },
    { SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR_SIZE },
    { SOC_ACPU_TIMER10_BASE_ADDR, SOC_ACPU_TIMER10_BASE_ADDR_SIZE },
    { SOC_ACPU_AO_IPC_S_BASE_ADDR, SOC_ACPU_AO_IPC_S_BASE_ADDR_SIZE },
    { SOC_ACPU_ACTRL_BASE_ADDR, SOC_ACPU_ACTRL_BASE_ADDR_SIZE },

    { DSS_BASE, DSS_BASE_SIZE },
    { PCTRL_BASE, PCTRL_BASE_SIZE },
    { MMBUF_CFG_BASE, MMBUF_CFG_BASE_SIZE },
    { NOC_DSS_BASE, NOC_DSS_BASE_SIZE },
    { PMC_BASE, PMC_BASE_SIZE },

    /* GPIO28,GPIO1_SE,AO_IOC in "platform/kirin/hi3670/secure_page_table_plat.c" */
    { GPIO_SPI, GPIO_SPI_SIZE },

    /* DRM */
    { SOC_ACPU_VDEC_BASE_ADDR, SOC_ACPU_VDEC_BASE_ADDR_SIZE },

    /* ISP */
    { CRG_BASE, CRG_BASE_SIZE },
    { MEDIA_CRG_BASE_ADDR, MEDIA_CRG_BASE_ADDR_SIZE },

    /* HIFI */
    { HIFI_CFG_BASE_ADDR, HIFI_CFG_BASE_ADDR_SIZE },
    { HIFI_CFG_DMMU_BASE_ADDR, HIFI_CFG_DMMU_BASE_SIZE },

    /* MODEM */
    { HI_IPCM_REGBASE_ADDR, HI_IPCM_REGBASE_ADDR_SIZE },
    { SOCP_BASE_ADDR, SOCP_BASE_ADDR_SIZE },

    /* SECBOOT */
    { HI_SYSCTRL_BASE_ADDR, HI_SYSCTRL_BASE_ADDR_SIZE },
    { HI_WDT_BASE_ADDR_VIRT, HI_WDT_BASE_ADDR_VIRT_SIZE },
    { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR_SIZE },
    { SECBOOT_XX, SECBOOT_XX_SIZE },

    /* Fingerprint */
    { RESET_PIN_GPIO_ADDR, RESET_PIN_GPIO_ADDR_SIZE },

    { DX_BASE_ATLANTA, DX_BASE_ATL_SIZE },

    /* SOC_ACPU_SPI1_BASE_ADDR   4K */
    { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR_SIZE },
    /* SOC_ACPU_IOMCU_SPI2_BASE_ADDR 4K */
    { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
    /* SOC_ACPU_SPI3_BASE_ADDR   4K */
    { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR_SIZE },
    /* SOC_ACPU_SPI4_BASE_ADDR   4K */
    { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR_SIZE },
    /* SOC_ACPU_I3C4_BASE_ADDR   4K */
    { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR_SIZE },
    /* SOC_ACPU_AO_IOC_BASE_ADDR   4K */
    { SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR_SIZE },
    /* SOC_ACPU_IOC_BASE_ADDR   4K */
    { SOC_ACPU_IOC_BASE_ADDR, SOC_ACPU_IOC_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO21_BASE_ADDR   4K */
    { SOC_ACPU_GPIO21_BASE_ADDR, SOC_ACPU_GPIO21_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO1_BASE_ADDR   4K */
    { SOC_ACPU_GPIO1_BASE_ADDR, SOC_ACPU_GPIO1_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO5_BASE_ADDR   4K */
    { SOC_ACPU_GPIO5_BASE_ADDR, SOC_ACPU_GPIO5_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO6_BASE_ADDR   4K */
    { SOC_ACPU_GPIO6_BASE_ADDR, SOC_ACPU_GPIO6_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO0_SE_BASE_ADDR   4K */
    { SOC_ACPU_GPIO0_SE_BASE_ADDR, SOC_ACPU_GPIO0_SE_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO1_SE_BASE_ADDR   4K */
    { SOC_ACPU_GPIO1_SE_BASE_ADDR, SOC_ACPU_GPIO1_SE_BASE_ADDR_SIZE },
    /* tzpc & ao_tzpc */
    { TZPC, TZPC_SIZE },
    /* AO_TZPC   4K */
    { AO_TZPC, AO_TZPC_SIZE },
    /* SOC_ACPU_GPIO22_BASE_ADDR   4K */
    { SOC_ACPU_GPIO22_BASE_ADDR, SOC_ACPU_GPIO22_BASE_ADDR_SIZE },
    /* SOC_ACPU_GPIO0_BASE_ADDR   4K */
    { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
    /* SOC_ACPU_IOMCU_CONFIG_BASE_ADDR   4K */
    { SOC_ACPU_IOMCU_CONFIG_BASE_ADDR, SOC_ACPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
    /* SOC_ACPU_ISP_BASE_ADDR   4K */
    { SOC_ACPU_ISP_CORE_CFG_BASE_ADDR, SOC_ACPU_ISP_CORE_CFG_BASE_ADDR_SIZE },
     /* SOC_ACPU_CSI_WRAPPER_ADDR   4K */
    { SOC_ACPU_CSI_ADAPTER_BASE_ADDR, SOC_ACPU_CSI_ADAPTER_BASE_ADDR_SIZE },
    { SMMUV3_MEDIA1_TCU_BASE_ADDR, SMMUV3_MEDIA1_TCU_ADDR_SIZE },
    { SMMUV3_MEDIA2_TCU_BASE_ADDR, SMMUV3_MEDIA2_TCU_ADDR_SIZE },
    { SMMUV3_NPU_TCU_BASE_ADDR, SMMUV3_NPU_TCU_ADDR_SIZE },
    /* ivp */
    { SOC_IVP_IMAGE_BASE_ADDR_0, SOC_IVP_IMAGE_BASE_ADDR_SIZE },
    { SOC_IVP_IMAGE_BASE_ADDR_1, SOC_IVP_IMAGE_BASE_ADDR_SIZE },
    /* file encry */
#ifdef TEE_SUPPORT_FILE_ENCRY
    { SOC_ACPU_UFS_CFG_BASE_ADDR, SOC_ACPU_UFS_CFG_BASE_ADDR_SIZE },
#endif
    /* RTC */
    { RTC_BASE_ADDR, RTC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMC_0_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMC_2_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMC_3_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE },
    { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR_SIZE },
#ifdef FEATURE_SE
    /* hisee ipc&mailbox */
    { HISEE_IPC_BASE_ADDR, HISEE_IPC_BASE_ADDR_SIZE },
    { HISEE_MBOX_BASE_ADDR, HISEE_MBOX_BASE_ADDR_SIZE },
#endif
    /* HDCP DPTX_WRAP_APB  4K */
    { HDCP_ADDR, HDCP_ADDR_SIZE },
    { HDCP_DSS_ADDR, HDCP_DSS_ADDR_SIZE },

    /* FOR NPU SEC CONFIG */
    { SMMUV3_TS_TBU_BASE_ADDR, SMMUV3_TS_TBU_BASE_SIZE },
    { SOC_ACPU_TSCPU_SYSCTRL_BASE_ADDR, SOC_ACPU_TSCPU_SYSCTRL_BASE_SIZE },
    { SOC_ACPU_TS_SECURE0_BASE_ADDR, SOC_ACPU_TS_SECURE0_BASE_SIZE },
    { SOC_ACPU_AIC0_SMMU_CFG_BASE_ADDR, SOC_ACPU_AIC0_SMMU_CFG_BASE_SIZE },
    { SOC_ACPU_AIC1_SMMU_CFG_BASE_ADDR, SOC_ACPU_AIC1_SMMU_CFG_BASE_SIZE },
    { SOC_ACPU_HWTS_ADDR, SOC_ACPU_HWTS_SIZE },
    { SOC_ACPU_AIC0_BASE_ADDR, SOC_ACPU_AIC0_BASE_SIZE },
    { SOC_ACPU_AIC1_BASE_ADDR, SOC_ACPU_AIC1_BASE_SIZE },
};

#endif
