
set(WITH_MTK_PLATFORM     "1")
set(WITH_CHIP_MT6873      "19")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_MTK_PLATFORM)
set(PLATFORM_NAME "mtk")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "phone")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_MT6873=${WITH_CHIP_MT6873}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_MTK_PLATFORM=${WITH_MTK_PLATFORM}
)


