set(WITH_PRODUCT_PHONE 0)
set(WITH_PRODUCT_2G_PAD 1)
set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_HI6260)
set(GATEKEEPER_ITRATION_TIMES 125)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)
if ("${ap_cust_spec}" STREQUAL "2g_mem")
    set(TRUSTEDCORE_PRODUCT_CHOOSE WITH_PRODUCT_2G_PAD)
    set(TRUSTEDCORE_PHY_TEXT_BASE 0x13C08000)
    set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x14400000)
else()
    set(TRUSTEDCORE_PRODUCT_CHOOSE WITH_PRODUCT_PHONE)
    set(TRUSTEDCORE_PHY_TEXT_BASE 0x15008000)
    set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x15800000)
endif()

if ("${ap_cust_spec}" STREQUAL "2g_mem")
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
        -DCONFIG_AP_CUST_2G_MEM
    )
endif()
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DFEATURE_SE
)
