WITH_PRODUCT_PHONE := 0
WITH_PRODUCT_2G_PAD := 1
TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_HI6260
ifneq ($(findstring 2g_mem, $(ap_cust_spec)), )
TRUSTEDCORE_PRODUCT_CHOOSE := WITH_PRODUCT_2G_PAD
TRUSTEDCORE_PHY_TEXT_BASE := 0x13C08000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x14400000
else
TRUSTEDCORE_PRODUCT_CHOOSE := WITH_PRODUCT_PHONE
TRUSTEDCORE_PHY_TEXT_BASE := 0x15008000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x15800000
endif

ifeq ($(ap_cust_spec),2g_mem)
TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_AP_CUST_2G_MEM
endif
TRUSTEDCORE_PLATFORM_FLAGS += -DFEATURE_SE
GATEKEEPER_ITRATION_TIMES := 125
DERIVE_ROOT_INTERNAL_ITRATIONS := 4
