TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_MIAMICW
TRUSTEDCORE_PHY_TEXT_BASE := 0x14008000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x14800000
TRUSTEDCORE_PLATFORM_FLAGS += -DFEATURE_SE
TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_WATCH_DISABLE_SION
GATEKEEPER_ITRATION_TIMES := 125
DERIVE_ROOT_INTERNAL_ITRATIONS := 4
