set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_MIAMICW)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x26408000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x26C00000)
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DFEATURE_SE
)
set(GATEKEEPER_ITRATION_TIMES 125)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)