set(SUPPORT_HISI_TIMER true)
set(CONFIG_SSA_64BIT false)
set(CONFIG_RPMB_64BIT false)
set(CONFIG_TA_64BIT false)
set(CONFIG_PERMSRV_64BIT false)
set(CONFIG_GTASK_64BIT false)
set(ENABLE_CPP true)
set(ENABLE_CPP_STATIC true)
set(CONFIG_ANTIROOT true)
set(CONFIG_SSA_64BIT false)
set(CONFIG_PLATDRV_64BIT false)
set(CONFIG_DRV_TIMER_64BIT false)
set(CONFIG_DRV_64BIT false)
set(CONFIG_SEM true)
set(CONFIG_KEYMASTER_32BIT true)
set(CONFIG_GATEKEEPER_32BIT true)
set(CONFIG_GMLIB_IMPORT false)
set(CONFIG_DX_ENABLE true)
set(CONFIG_HUK_SERVICE_32BIT true)
set(CONFIG_HUK_PLAT_COMPATIBLE true)

if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 bdkernel.elf secmem.elf gatekeeper.elf)
else()
    list(APPEND PRODUCT_RELEASE_64 bdkernel.elf secmem.elf gatekeeper.elf)
    list(APPEND PRODUCT_RELEASE_32 bdkernel.elf secmem.elf gatekeeper.elf sem.elf)
endif()

if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
    list(APPEND PRODUCT_APPS_32 bdkernel.elf secmem.elf gatekeeper.elf sem.elf)
endif()
if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_64 bdkernel.elf secmem.elf gatekeeper.elf)
endif()

if ("${CONFIG_TUI_32BIT}" STREQUAL "true")
    set(TUI_FEATURE true)
elseif ("${CONFIG_TUI_64BIT}" STREQUAL "true")
    set(TUI_FEATURE true)
endif()
