#ifndef __HISI_DDR_AUTOFSGT_PROXY_SECURE_OS_H__
#define __HISI_DDR_AUTOFSGT_PROXY_SECURE_OS_H__

/*same as vender/hisi/confidential/lpmcu/.../ddr_auto_fsgt.h*/
void uart_printf_func(const char *fmt, ...);
#define WRITE_MASK_SHIFT	(16)


typedef enum {
	DDR_AUTOFSGT_ENABLE = 1,
	DDR_AUTOFSGT_DISABLE,
	DDR_AUTOFSGT_LOGIC_EN,
	DDR_AUTOFSGT_LOGIC_DIS,
} DDR_AUTOFSGT_CMD_ID;

/*should keep same with ap/platform ddr_define.h*/
typedef enum {
	DDR_AUTOFSGT_CLIENT_LPMCU = 0,
	/* bl31 */
	DDR_AUTOFSGT_CLIENT_BL31 = 1,
	DDR_AUTOFSGT_PROXY_CLIENT_FREQDUMP,
	DDR_AUTOFSGT_PROXY_CLIENT_DDRREG,
	DDR_AUTOFSGT_PROXY_CLIENT_KERNEL_CODE,
	DDR_AUTOFSGT_PROXY_CLIENT_XDUMP,
	DDR_AUTOFSGT_PROXY_CLIENT_NPU,
	DDR_AUTOFSGT_PROXY_CLIENT_DDR_PERFDATA,

	/* fastboot */
	DDR_AUTOFSGT_BIT_FASTBOOT,

	/* secure_os */
	DDR_AUTOFSGT_CLIENT_SECURE_OS = 9,
	DDR_AUTOFSGT_PROXY_CLIENT_SETSEC = 9,
	DDR_AUTOFSGT_PROXY_CLIENT_CLRSEC = 9,
	DDR_AUTOFSGT_PROXY_CLIENT_CHECKSEC = 9,

	/* bl2 */
	DDR_AUTOFSGT_CLIENT_BL2,

	/* ap */
	DDR_AUTOFSGT_CLIENT_AP,
	DDR_AUTOFSGT_PROXY_CLIENT_DDRFLUX,
	DDR_AUTOFSGT_PROXY_CLIENT_DMSSPT,
	/*Please add your definition above!!!*/
	DDR_AUTOFSGT_PROXY_CLIENT_BUTT,
} DDR_AUTOFSGT_PROXY_CLIENT_ID;

/* s32 ddr_autofsgt_ctrl(DDR_AUTOFSGT_PROXY_CLIENT_ID client, DDR_AUTOFSGT_CMD_ID cmd) */
extern int ddr_autofsgt_ctrl(unsigned int client, unsigned int cmd);

#endif /* end of hisi_ddr_autofsgt_proxy_secure_os.h */
