
set(WITH_HUANGLONG_PLATFORM     "2")
set(WITH_CHIP_SHAOLINGUN        "30")
set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_HUANGLONG_PLATFORM)
set(PLATFORM_NAME "huanglong")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "TV")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_SHAOLINGUN=${WITH_CHIP_SHAOLINGUN}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_HUANGLONG_PLATFORM=${WITH_HUANGLONG_PLATFORM}
)


