export CONFIG_TA_64BIT := true
export CONFIG_SSA_64BIT := true
export CONFIG_GTASK_64BIT := true
export CONFIG_HUK_SERVICE_64BIT := true
export CONFIG_PERMSRV_64BIT := true
export ENABLE_CPP := true
export ENABLE_CPP_STATIC := true
export CONFIG_GMLIB_IMPORT := true
export CONFIG_TRNG_ENABLE := true
export CONFIG_TIMER_FREERUNNING_FIQ_DISABLE := true
export ENABLE_TA_LOAD_WHITE_BOX_KEY := true
export CONFIG_EXPORT_OPENSSL_SYMBOL := true
export CONFIG_TA_LOCAL_SIGN := true
export CONFIG_NO_VENDOR_LIB_EMBEDDED := true
export CONFIG_LIBFUZZER_SERVICE_64BIT :=false

include $(PLATFORM_DIR)/$(PLATFORM_NAME)/$(PRODUCT_NAME)/$(CHIP_NAME)/modules/modules.mk
