set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_KIRIN990)
if ("${product_type}" STREQUAL "armpc")
    set(TRUSTEDCORE_PHY_TEXT_BASE 0x22808000)
    set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x23000000)
else()
    set(TRUSTEDCORE_PHY_TEXT_BASE 0x13608000)
    set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13e00000)
endif()
set(GATEKEEPER_ITRATION_TIMES 400)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)
if (NOT "${chip_type}" STREQUAL "cs2")
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS -DWITH_KIRIN990_CS)
else()
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS -DWITH_KIRIN990_CS2)
endif()

if ("${product_type}" STREQUAL "armpc")
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS -DCONFIG_PRODUCT_ARMPC)
else()
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS -DTEE_SUPPORT_AI)
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS -DTEE_SUPPORT_AI_STATIC_ION)
endif()

if ("${product_type}" STREQUAL "cdc")
    list(APPEND TRUSTEDCORE_PLATFORM_FLAGS -DCONFIG_CDC)
endif()

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DFEATURE_SE
    -DCONFIG_HISI_SECFLASH
    -DTEE_SUPPORT_FILE_ENCRY
    -DCONFIG_HISEE_14_CHANNEL_IPC
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_SECIDENTIFICATION
)
