
WITH_HIGENERIC_PLATFORM := 7
WITH_CHIP_HI3670 := 3

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_HIGENERIC_PLATFORM
	PLATFORM_NAME := higeneric
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := phone

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI3670=$(WITH_CHIP_HI3670) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_HIGENERIC_PLATFORM=$(WITH_HIGENERIC_PLATFORM)

