
WITH_QEMU_PLATFORM := 8
WITH_CHIP_XINGTIAN := 31

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_QEMU_PLATFORM
	PLATFORM_NAME := qemu
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := qemu

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_XINGTIAN=$(WITH_CHIP_XINGTIAN) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_QEMU_PLATFORM=$(WITH_QEMU_PLATFORM)

