set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_LEXINGTON
set(TRUSTEDCORE_PHY_TEXT_BASE 0x13608000
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13E00000
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DCC_POWER_IN_SECOS
)
set(GATEKEEPER_ITRATION_TIMES 0)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 0)
