
WITH_MTK_PLATFORM := 1
WITH_CHIP_MT6853 := 22

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_MTK_PLATFORM
	PLATFORM_NAME := mtk
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := phone

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_MT6853=$(WITH_CHIP_MT6853) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_MTK_PLATFORM=$(WITH_MTK_PLATFORM)

