/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: plat_cfg defines
 * Create: 2020-03
 */
#include "plat_cfg.h"
#include "plat_cfg_public.h"
#include <plat_features.h>
#include <hisi_platform.h>
#include "uart_register.h"

struct platform_info g_plat_cfg = {
    /* value is assigned in boot_kernel_on_current_cpu function */
    .phys_region_start    = 0,
    .phys_region_size     = TEEOS_MEM_SIZE,
    .uart_addr = UART_ADDR,
    .uart_type = UART_DISABLE_FLAG | PL011_TYPE,
    .shmem_offset = SHMEM_OFFSET,
    .shmem_size           = SHMEM_SIZE,
    /*
     * refer to device/hisi/customize/dtsi/arm64/kirin990/kirin990_memory.dtsi
     * 2019/07/29:deprotect for 4KB bl31 memory space:0x13101000~0x13102000
     */
    .protected_regions = { { PROTECTED_REGION_START1, PROTECTED_REGION_END1 },
                           { PROTECTED_REGION_START2, PROTECTED_REGION_END2 } },

    .gic_config = {
        .version = GIC_V3_VERSION,
        .v3 = {
            .dist = { GIC_V3_DIST_ADDR, GIC_V3_DIST_ADDR + GIC_DIST_PAGENUM * PAGE_SIZE },
            .redist_num = GIC_REDIST_NUM,
            .redist_stride = GIC_REDIST_MEMSIZE,
            .redist = {
                { GIC_V3_REDIST_ADDR, GIC_V3_REDIST_ADDR + GIC_REDIST_PAGENUM * PAGE_SIZE }
            }
        }
    },

    .spi_num_for_notify    = SPI_NUM,

    .plat_features =
#ifdef CONFIG_ARM64_PAN
    PLAT_DEF_ENG | PLAT_ENABLE_PAN,
#else
    PLAT_DEF_ENG,
#endif

    /* at most PLAT_MAX_DEVIO_REGIONS (128) regions, the first region should be UART6 */
    .plat_io_regions = {
        /* .start,     .end */
        { TIMER1_BASE, TIMER1_BASE + TIMER1_BASE_SIZE },
        { TIMER7_BASE, TIMER7_BASE + TIMER7_BASE_SIZE },
        { RTC_BASE_ADDR, RTC_BASE_ADDR + RTC_BASE_ADDR_SIZE },
        { REG_BASE_SCTRL, REG_BASE_SCTRL + REG_BASE_SCTRL_SIZE },
        { REG_BASE_PERI_CRG, REG_BASE_PERI_CRG + REG_BASE_PERI_CRG_SIZE },
        { REG_BASE_PCTRL, REG_BASE_PCTRL + REG_BASE_PCTRL_SIZE },
        { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR + SOC_ACPU_DMSS_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_0_BASE_ADDR, SOC_ACPU_DMC_0_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_1_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_2_BASE_ADDR, SOC_ACPU_DMC_2_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_3_BASE_ADDR, SOC_ACPU_DMC_3_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { DSS_BASE, DSS_BASE + DSS_BASE_SIZE },
        { PCTRL_BASE, PCTRL_BASE + PCTRL_BASE_SIZE },
        { MMBUF_CFG_BASE, MMBUF_CFG_BASE + MMBUF_CFG_BASE_SIZE },
        { NOC_DSS_BASE, NOC_DSS_BASE + NOC_DSS_BASE_SIZE },
        { PMC_BASE, PMC_BASE + PMC_BASE_SIZE },
        { GPIO_SPI, GPIO_SPI + GPIO_SPI_SIZE },
        { TZPC, TZPC + TZPC_SIZE },
        { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR + SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
        { CRG_BASE,   CRG_BASE + CRG_BASE_SIZE },
        { SOC_ACPU_GPIO6_BASE_ADDR, SOC_ACPU_GPIO6_BASE_ADDR + SOC_ACPU_GPIO6_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO25_BASE_ADDR, SOC_ACPU_GPIO25_BASE_ADDR + SOC_ACPU_GPIO25_BASE_ADDR_SIZE },
        { SOC_ACPU_ISP_CORE_CFG_BASE_ADDR, SOC_ACPU_ISP_CORE_CFG_BASE_ADDR + SOC_ACPU_ISP_CORE_CFG_BASE_ADDR_SIZE },
        { MEDIA_CRG_BASE_ADDR, MEDIA_CRG_BASE_ADDR + MEDIA_CRG_BASE_ADDR_SIZE },
        { HIFI_CFG_BASE_ADDR, HIFI_CFG_BASE_ADDR + HIFI_CFG_BASE_ADDR_SIZE },
        { HI_IPCM_REGBASE_ADDR, HI_IPCM_REGBASE_ADDR + HI_IPCM_REGBASE_ADDR_SIZE },
        { HI_SYSCTRL_BASE_ADDR, HI_SYSCTRL_BASE_ADDR + HI_SYSCTRL_BASE_ADDR_SIZE },
        { HI_WDT_BASE_ADDR_VIRT, HI_WDT_BASE_ADDR_VIRT + HI_WDT_BASE_ADDR_VIRT_SIZE },
        { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR + SOC_ACPU_SCTRL_BASE_ADDR_SIZE },
        { SECBOOT_XX, SECBOOT_XX + SECBOOT_XX_SIZE },
        { RESET_PIN_GPIO_ADDR, RESET_PIN_GPIO_ADDR + RESET_PIN_GPIO_ADDR_SIZE },
        { FINGERPRINT_XX, FINGERPRINT_XX + FINGERPRINT_XX_SIZE },
        { SOC_ACPU_CSSYS_APB_BASE_ADDR, SOC_ACPU_CSSYS_APB_BASE_ADDR + SOC_ACPU_CSSYS_APB_BASE_ADDR_SIZE },
        { SOC_ACPU_I2C7_BASE_ADDR, SOC_ACPU_I2C7_BASE_ADDR + SOC_ACPU_I2C7_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR + SOC_ACPU_SPI1_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR + SOC_ACPU_SPI3_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR + SOC_ACPU_SPI4_BASE_ADDR_SIZE },
        { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR + SOC_ACPU_I3C4_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR + SOC_ACPU_AO_IOC_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO1_SE_BASE_ADDR, SOC_ACPU_GPIO1_SE_BASE_ADDR + SOC_ACPU_GPIO1_SE_BASE_ADDR_SIZE },
        { SOC_ACPU_IOC_BASE_ADDR, SOC_ACPU_IOC_BASE_ADDR + SOC_ACPU_IOC_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO23_BASE_ADDR, SOC_ACPU_GPIO23_BASE_ADDR + SOC_ACPU_GPIO23_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO22_BASE_ADDR, SOC_ACPU_GPIO22_BASE_ADDR + SOC_ACPU_GPIO22_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO21_BASE_ADDR, SOC_ACPU_GPIO21_BASE_ADDR + SOC_ACPU_GPIO21_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO20_BASE_ADDR, SOC_ACPU_GPIO20_BASE_ADDR + SOC_ACPU_GPIO20_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO29_BASE_ADDR, SOC_ACPU_GPIO29_BASE_ADDR + SOC_ACPU_GPIO29_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO35_BASE_ADDR, SOC_ACPU_GPIO35_BASE_ADDR + SOC_ACPU_GPIO35_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO1_BASE_ADDR, SOC_ACPU_GPIO1_BASE_ADDR + SOC_ACPU_GPIO1_BASE_ADDR_SIZE },
        { AO_TZPC, AO_TZPC + AO_TZPC_SIZE },
        { HIEPS_CDRM_BASE_ADDR, HIEPS_CDRM_BASE_ADDR + HIEPS_CDRM_ADDR_SIZE },
        { HIEPS_DDR_VIDEO_BASE_ADDR, HIEPS_DDR_VIDEO_BASE_ADDR + HIEPS_DDR_VIDEO_SIZE },
        { SOC_ACPU_EPS_IPC_BASE_ADDR, SOC_ACPU_EPS_IPC_BASE_ADDR + SOC_ACPU_EPS_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_EPS_CONFIG_BASE_ADDR, SOC_ACPU_EPS_CONFIG_BASE_ADDR + SOC_ACPU_EPS_CONFIG_BASE_ADDR_SIZE },
        { MEDIA2_CRG_BASE_ADDR, MEDIA2_CRG_BASE_ADDR + MEDIA2_CRG_BASE_ADDR_SIZE },
        { ACPU_SYS_CNT_BASE_ADDR, ACPU_SYS_CNT_BASE_ADDR + ACPU_SYS_CNT_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_NS_BASE_ADDR, SOC_ACPU_IPC_NS_BASE_ADDR + SOC_ACPU_IPC_NS_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR + SOC_ACPU_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_TIMER10_BASE_ADDR, SOC_ACPU_TIMER10_BASE_ADDR + SOC_ACPU_TIMER10_BASE_ADDR_SIZE },
        { SOC_ACPU_CSI_ADAPTER_BASE_ADDR, SOC_ACPU_CSI_ADAPTER_BASE_ADDR + SOC_ACPU_CSI_ADAPTER_BASE_ADDR_SIZE },
        { HIFI_CFG_DMMU_BASE_ADDR, HIFI_CFG_DMMU_BASE_ADDR + HIFI_CFG_DMMU_BASE_SIZE },
        { CAMBRICON_X1, CAMBRICON_X1 + CAMBRICON_X1_SIZE },
        { CAMBRICON_X2, CAMBRICON_X2 + CAMBRICON_X2_SIZE },
        { DX_BASE_CC, DX_BASE_CC + DX_BASE_CC_SIZE },
        { DX_BASE_ATLANTA, DX_BASE_ATLANTA + DX_BASE_ATL_SIZE },
        { HISEE_MBOX_BASE_ADDR, HISEE_MBOX_BASE_ADDR + HISEE_MBOX_BASE_ADDR_SIZE },
        { HISEE_IPC_BASE_ADDR, HISEE_IPC_BASE_ADDR + HISEE_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_VENC_BASE_ADDR, SOC_ACPU_VENC_BASE_ADDR + SOC_ACPU_VENC_BASE_ADDR_SIZE },
        { SOC_ACPU_VDEC_BASE_ADDR, SOC_ACPU_VDEC_BASE_ADDR + SOC_ACPU_VDEC_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR + SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_CONFIG_BASE_ADDR, SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + SOC_ACPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_DMAC_BASE_ADDR, SOC_ACPU_IOMCU_DMAC_BASE_ADDR + SOC_ACPU_IOMCU_DMAC_BASE_ADDR_SIZE },
#ifdef TEE_SUPPORT_FILE_ENCRY
        { SOC_ACPU_UFS_CFG_BASE_ADDR, SOC_ACPU_UFS_CFG_BASE_ADDR + SOC_ACPU_UFS_CFG_BASE_ADDR_SIZE },
#endif
        /* kirin990 && orlando cs npu register description */
        { TS_DOORBELL_BASE_ADDR, TS_DOORBELL_BASE_ADDR + TS_DOORBELL_BASE_ADDR_SIZE },
        { TS_SRAM_BASE_ADDR, TS_SRAM_BASE_ADDR + TS_SRAM_BASE_ADDR_SIZE },
        /* ivp space for IMAGE */
        { SOC_IVP_IMAGE_BASE_ADDR, SOC_IVP_IMAGE_BASE_ADDR + SOC_IVP_IMAGE_BASE_ADDR_SIZE },
        { HDCP13_ADDR,   HDCP13_ADDR + HDCP13_ADDR_SIZE },
        { HDCP22_ADDR,   HDCP22_ADDR + HDCP22_ADDR_SIZE },
        { SOC_ACPU_GPIO4_BASE_ADDR, SOC_ACPU_GPIO4_BASE_ADDR + SOC_ACPU_GPIO4_BASE_ADDR_SIZE },
        { SENSORHUB_IPC_BASE_ADDR, SENSORHUB_IPC_BASE_ADDR + SENSORHUB_IPC_BASE_ADDR_SIZE },
        { SMMUV3_SDMA_BASE_ADDR, SMMUV3_SDMA_BASE_ADDR + SMMUV3_SDMA_BASE_ADDR_SIZE },
        { SMMUV3_AICORE_BASE_ADDR, SMMUV3_AICORE_BASE_ADDR + SMMUV3_AICORE_BASE_ADDR_SIZE },
#ifdef SMMUV3_AICORE1_BASE_ADDR
        { SMMUV3_AICORE1_BASE_ADDR, SMMUV3_AICORE1_BASE_ADDR + SMMUV3_AICORE1_BASE_ADDR_SIZE },
#endif
        { SOCP_BASE_ADDR, SOCP_BASE_ADDR + SOCP_BASE_ADDR_SIZE },
        /* this is terminator */
        { 0, 0 }
}

};
