#ifndef NXP_ESE_FEATURES_H
#define NXP_ESE_FEATURES_H

#define NFC_NXP_CHIP_TYPE PN81B
#define NFC_NXP_ESE_VER JCOP_VER_5_x
#define ESE_DEBUG_UTILS_INCLUDED true

#define NXP_POWER_SCHEME_SUPPORT true
#define NXP_ESE_P73_ISO_RST false
#define NXP_ESE_END_OF_SESSION true
#define NXP_ESE_WTX_RES_DELAY true
#define NXP_ESE_JCOP_DWNLD_PROTECTION false
#define NXP_ESE_SPI_FW_DOWNLOAD_SYNC true
#define NXP_SECURE_TIMER_SESSION true

#endif
