set(CONFIG_TIMER_EVENT true)
set(CONFIG_EXPORT_OPENSSL_SYMBOL true)
set(CONFIG_CRYPTO_SUPPORT_EC25519 true)
set(CONFIG_CRYPTO_SUPPORT_X509 true)
set(CONFIG_CRYPTO_ECC_WRAPPER true)
set(CONFIG_CRYPTO_AES_WRAPPER true)
set(CONFIG_TA_LOCAL_SIGN true)

list(APPEND PRODUCT_RELEASE_64 drv_timer.elf platdrv.elf)
