/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: record the register mmap information.
 * Create: 2020-03
 */
#ifndef PLATDRV_IO_MAP_H
#define PLATDRV_IO_MAP_H

#include <plat_cfg.h>
#include <platdrv.h>
#include "hisi_platform.h"

struct ioaddr_t g_ioaddrs[] = {
    /* SECBOOT laguna */
    { HI_TSP_REG_BASE, HI_TSP_REG_SIZE },
    { HI_WDT_BASE_ADDR_VIRT, HI_WDT_BASE_ADDR_VIRT_SIZE },
    { REG_BASE_SCTRL, REG_BASE_SCTRL_SIZE }, /* SCTRL 4K */

    { DX_BASE_ATLANTA, DX_BASE_ATL_SIZE },

    /* HIFI laguna */
    { HIFI_CFG_BASE_ADDR, HIFI_CFG_BASE_ADDR_SIZE },

    /* MODEM laguna */
    {HI_IPCM_REGBASE_ADDR, HI_IPCM_REGBASE_ADDR_SIZE},
    {SOCP_BASE_ADDR, SOCP_BASE_ADDR_SIZE},

    {EICC_PERI_REGBASE_ADDR, EICC_PERI_REGBASE_ADDR_SIZE},
    {EICC_MDM0_REGBASE_ADDR, EICC_MDM0_REGBASE_ADDR_SIZE},
    {MDM_LPMCU_TCM_ADDR, MDM_LPMCU_TCM_ADDR_SIZE},
    {SOC_ACPU_LP_PCTRL_BASE_ADDR, SOC_ACPU_PCTRL_BASE_ADDR_SIZE},
    {SOC_ACPU_PMC_BASE_ADDR, SOC_ACPU_PMC_BASE_ADDR_SIZE},

    /* DSS Reg Map laguna */
    {DSS_BASE, DSS_BASE_SIZE},
    {PCTRL_BASE, PCTRL_BASE_SIZE},
    {MMBUF_CFG_BASE, MMBUF_CFG_BASE_SIZE},
    {NOC_DSS_BASE, NOC_DSS_BASE_SIZE},
    {PMC_BASE, PMC_BASE_SIZE},

    /* DSS GPIO Map laguna */
    {SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR_SIZE},

    /* RTC laguna */
    {RTC_BASE_ADDR, RTC_BASE_ADDR_SIZE},
    /* GPIO laguna */
    {SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR_SIZE},
    {SOC_ACPU_IOC_BASE_ADDR, SOC_ACPU_IOC_BASE_ADDR_SIZE},
    {SOC_ACPU_GPIO2_BASE_ADDR, SOC_ACPU_GPIO2_BASE_ADDR_SIZE},
    {SOC_ACPU_GPIO27_BASE_ADDR, SOC_ACPU_GPIO27_BASE_ADDR_SIZE},
    {SOC_ACPU_GPIO22_BASE_ADDR, SOC_ACPU_GPIO22_BASE_ADDR_SIZE},
    {SOC_ACPU_GPIO23_BASE_ADDR, SOC_ACPU_GPIO23_BASE_ADDR_SIZE},
    {SOC_ACPU_GPIO24_BASE_ADDR, SOC_ACPU_GPIO24_BASE_ADDR_SIZE},
    /* SOC_ACPU_SPI1_BASE_ADDR 4K laguna */
    {SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR_SIZE},
    /* SOC_ACPU_I2C7_BASE_ADDR 4K laguna */
    {SOC_ACPU_I2C7_BASE_ADDR, SOC_ACPU_I2C7_BASE_ADDR_SIZE},
    /* SOC_ACPU_IOMCU_SPI2_BASE_ADDR 4K laguna */
    {SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
    /* SOC_ACPU_SPI3_BASE_ADDR 4K laguna */
    {SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR_SIZE},
    /* SOC_ACPU_SPI4_BASE_ADDR 4K laguna */
    {SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR_SIZE},
    /* SOC_ACPU_I3C4_BASE_ADDR 4K laguna */
    {SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR_SIZE},
    {SOC_CPU_IOMCU_CONFIG_BASE_ADDR, SOC_CPU_IOMCU_CONFIG_BASE_ADDR_SIZE},
    {SOC_ACPU_IOMCU_DMAC_BASE_ADDR, SOC_ACPU_IOMCU_DMAC_BASE_ADDR_SIZE},
    /* SPI laguna */
    { SOC_ACPU_GPIO1_SE_BASE_ADDR, SOC_ACPU_GPIO1_SE_BASE_ADDR_SIZE },
    /* file encry laguna */
#ifdef TEE_SUPPORT_FILE_ENCRY
    {SOC_ACPU_UFS_CFG_BASE_ADDR, SOC_ACPU_UFS_CFG_BASE_ADDR_SIZE},
#endif
    {SOC_ACPU_PERI_CRG_BASE_ADDR, SOC_ACPU_PERI_CRG_BASE_ADDR_SIZE},
    {SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_BASE_ADDR_SIZE},
    {SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR_SIZE},
    {SOC_ACPU_IPC_NS_BASE_ADDR, SOC_ACPU_IPC_NS_BASE_ADDR_SIZE},
    {SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR_SIZE},
    {SOC_ACPU_TIMER10_BASE_ADDR, SOC_ACPU_TIMER10_BASE_ADDR_SIZE},
    {SOC_ACPU_AO_IPC_S_BASE_ADDR, SOC_ACPU_AO_IPC_S_BASE_ADDR_SIZE},
    {SOC_ACPU_ISP_CORE_CFG_BASE_ADDR, SOC_ACPU_ISP_CORE_CFG_BASE_ADDR_SIZE},
    {MEDIA_CRG_BASE_ADDR, MEDIA_CRG_BASE_ADDR_SIZE},
    {SOC_ACPU_VDEC_BASE_ADDR, SOC_ACPU_VDEC_BASE_ADDR_SIZE},
    /* tzpc & ao_tzpc laguna */
    {TZPC, TZPC_SIZE},
    {AO_TZPC, AO_TZPC_SIZE},

    {SMMUV3_SDMA_BASE_ADDR, SMMUV3_SDMA_BASE_ADDR_SIZE},
    {TS_DOORBELL_BASE_ADDR, TS_DOORBELL_BASE_ADDR_SIZE},
    {TS_SRAM_BASE_ADDR, TS_SRAM_BASE_ADDR_SIZE},
};

#endif
