
set(WITH_ASCEND_PLATFORM  "6")
set(WITH_CHIP_HI1981      "41")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_ASCEND_PLATFORM)
set(PLATFORM_NAME "ascend")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "mini")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI1981=${WITH_CHIP_HI1981}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_ASCEND_PLATFORM=${WITH_ASCEND_PLATFORM}
)


