
WITH_CT_PLATFORM := 9
WITH_CHIP_HI1213 := 37

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_CT_PLATFORM
	PLATFORM_NAME := ct
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := ct

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI1213=$(WITH_CHIP_HI1213) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_CT_PLATFORM=$(WITH_CT_PLATFORM)

