
WITH_HIGENERIC_PLATFORM := 7
WITH_CHIP_BALTIMORE := 10

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_HIGENERIC_PLATFORM
	PLATFORM_NAME := higeneric
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
ifeq ($(product_type), armpc)
	PRODUCT_NAME  := pc
else
	PRODUCT_NAME  := phone
endif

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_BALTIMORE=$(WITH_CHIP_BALTIMORE) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_HIGENERIC_PLATFORM=$(WITH_HIGENERIC_PLATFORM)

