set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_BALTIMORE)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x13608000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13E00000)
set(GATEKEEPER_ITRATION_TIMES 0)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 0)
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DFEATURE_SE
    -DTEE_SUPPORT_FILE_ENCRY
    -DTEE_SUPPORT_FILE_ENCRY_V3
    -DCONFIG_HISEE_14_CHANNEL_IPC
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_SESRV
    -DTEE_SUPPORT_MSP
    -DHISI_MSP_SECFLASH
    -DTEE_SUPPORT_SECISP
    -DTEE_SUPPORT_SECIVP
    -DTEE_SUPPORT_AI
    -DTEE_SUPPORT_AI_DYN_ION
    -DTEE_SUPPORT_SECIDENTIFICATION
    -DTEE_SUPPORT_VLTMM_SRV
    -DTEE_HIVCODEC_DYNAMIC_TA
    -DCONFIG_FACEID_TOF_AE
    -DTEE_SUPPORT_EID_DYN_ION
)
