set(CONFIG_TUI_32BIT true)
set(CONFIG_TA_64BIT true)
set(CONFIG_SSA_64BIT true)
set(CONFIG_GTASK_64BIT true)
set(CONFIG_RPMB_64BIT true)
set(CONFIG_SEC_FLASH true)
set(CONFIG_SEM true)
set(CONFIG_SE_SERVICE_64BIT true)
set(CONFIG_MSP true)
set(CONFIG_BIO true)
set(CONFIG_ROT true)
set(CONFIG_ART true)
set(ENABLE_CPP true)
set(ENABLE_CPP_STATIC true)
set(CONFIG_GATEKEEPER_64BIT true)
set(CONFIG_KEYMASTER_64BIT true)
set(CONFIG_ANTIROOT true)
set(CONFIG_EPS_FOR_MSP true)
set(CONFIG_HISI_MSPC true)
set(FEATURE_HISI_MSP_ENGINE_LIBCRYPTO true)
set(TEE_SUPPORT_FILE_ENCRY_V3 true)
set(TEE_SUPPORT_MSP true)
set(CONFIG_GENERIC_ROT true)
set(CONFIG_GENERIC_ART true)
set(CONFIG_HISI_BIOMETRIC true)
set(CONFIG_WEAVER true)
set(CONFIG_HISI_MSP_SECFLASH true)
set(CONFIG_VLTMM_SRV true)
set(CONFIG_PERMSRV_64BIT true)
set(CONFIG_PLATDRV_64BIT false)
set(CONFIG_DRV_TIMER_64BIT true)
set(CONFIG_DRV_64BIT false)
set(CONFIG_HISI_PRIVACY_PROTECTION true)
set(CONFIG_HISI_MSPC_IPC_TEST false)
set(CONFIG_GMLIB_IMPORT true)
set(CONFIG_DX_ENABLE true)
set(CONFIG_HUK_SERVICE_64BIT true)
set(CONFIG_HUK_PLAT_COMPATIBLE true)

if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 secmem.elf rot.elf file_encry.elf art.elf biometric.elf secisp.elf hivcodec.elf bdkernel.elf vltmm_service.elf)
else()
    list(APPEND PRODUCT_RELEASE_64 secmem.elf rot.elf file_encry.elf art.elf biometric.elf secisp.elf hivcodec.elf bdkernel.elf vltmm_service.elf)
    list(APPEND PRODUCT_RELEASE_32 secmem.elf rot.elf file_encry.elf art.elf biometric.elf secisp.elf hivcodec.elf bdkernel.elf vltmm_service.elf)
endif()

if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
    list(APPEND PRODUCT_APPS_32 secmem.elf rot.elf file_encry.elf art.elf biometric.elf secisp.elf hivcodec.elf bdkernel.elf vltmm_service.elf)
endif()
if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_64 secmem.elf rot.elf file_encry.elf art.elf biometric.elf secisp.elf hivcodec.elf bdkernel.elf vltmm_service.elf)
endif()

if ("${CONFIG_TUI_32BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_32 thp_afe_baltimore_a32)
elseif ("${CONFIG_TUI_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 thp_afe_baltimore)
endif()
