WITH_ASCEND_PLATFORM := 6
WITH_CHIP_HI1911 := 44

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_ASCEND_PLATFORM
	PLATFORM_NAME := ascend
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := mini

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI1911=$(WITH_CHIP_HI1911) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_ASCEND_PLATFORM=$(WITH_ASCEND_PLATFORM)


