/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: plat_cfg defines
 * Create: 2020-12-29
 */

#include "plat_cfg.h"
#include <autoconf.h>
#include <plat_features.h>
#include "plat_cfg_public.h"
#include "uart_register.h"
#include <mspe_ddr_layout.h>

#ifndef __aarch64__
#error "Only aarch64 is supported!"
#endif

struct platform_info g_plat_cfg = {

    .phys_region_start = 0,

    .phys_region_size = TEEOS_MEM_SIZE,

    .uart_addr = UART_ADDR,

    .uart_type = UART_DISABLE_FLAG | PL011_TYPE,

    .shmem_offset = SHMEM_OFFSET,

    .shmem_size = SHMEM_SIZE,

    /* refer to vendor/hisi/ap/platform/burbank/global_ddr_map.h */
    .protected_regions = { { ATF_RESERVED_BL31_PHYMEM_BASE,
                             ATF_RESERVED_BL31_PHYMEM_BASE + ATF_RESERVED_BL31_PHYMEM_SIZE } },

    .gic_config = {
        .version = GIC_V3_VERSION,
        .v3 = {
            .dist = { GIC_V3_DIST_ADDR, GIC_V3_DIST_ADDR + GIC_DIST_PAGENUM * PAGE_SIZE },
            .redist_num = GIC_REDIST_NUM,
            .redist_stride = GIC_REDIST_MEMSIZE,
            .redist = {
                { GIC_V3_REDIST_ADDR, GIC_V3_REDIST_ADDR + GIC_REDIST_PAGENUM * PAGE_SIZE }
            }
        }
    },

    .spi_num_for_notify = BURBANK_SPI_NUM,

    .plat_features =
#ifdef CONFIG_ARM64_PAN
    PLAT_DEF_ENG | PLAT_ENABLE_PAN,
#else
    PLAT_DEF_ENG,
#endif
        /* at most PLAT_MAX_DEVIO_REGIONS (128) regions */
    .plat_io_regions = {
        /* .start,     .end */
        { SOC_ACPU_TIMER1_BASE_ADDR, SOC_ACPU_TIMER1_BASE_ADDR + TIMER1_BASE_SIZE },
        { SOC_ACPU_TIMER7_BASE_ADDR, SOC_ACPU_TIMER7_BASE_ADDR + TIMER7_BASE_SIZE },
        { RTC_BASE_ADDR, RTC_BASE_ADDR + RTC_BASE_ADDR_SIZE },
        /* modem secboot, TSP reg */
        { HI_TSP_REG_BASE, HI_TSP_REG_BASE + HI_TSP_REG_SIZE },
        { EICC_PERI_REGBASE_ADDR, EICC_PERI_REGBASE_ADDR + EICC_PERI_REGBASE_ADDR_SIZE },
        { EICC_MDM0_REGBASE_ADDR, EICC_MDM0_REGBASE_ADDR + EICC_MDM0_REGBASE_ADDR_SIZE },
        { MDM_LPMCU_TCM_ADDR, MDM_LPMCU_TCM_ADDR + MDM_LPMCU_TCM_ADDR_SIZE },
        { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR + REG_BASE_SCTRL_SIZE },
        { SOC_ACPU_PERI_CRG_BASE_ADDR, SOC_ACPU_PERI_CRG_BASE_ADDR + REG_BASE_PERI_CRG_SIZE },
        { SOC_ACPU_PCTRL_BASE_ADDR, SOC_ACPU_PCTRL_BASE_ADDR + REG_BASE_PCTRL_SIZE },
        { SOC_ACPU_MEDIA1_CRG_BASE_ADDR, SOC_ACPU_MEDIA1_CRG_BASE_ADDR + REG_BASE_MEDIA1_CRG_SIZE },
        { SOC_CPU_CCS_BASE_ADDR, SOC_CPU_CCS_BASE_ADDR + DX_BASE_CC_SIZE },
        { SOC_ACPU_SYS_CNT_BASE_ADDR, SOC_ACPU_SYS_CNT_BASE_ADDR + SOC_ACPU_SYS_CNT_BASE_ADDR_SIZE },
        { SOC_ACPU_PMC_BASE_ADDR, SOC_ACPU_PMC_BASE_ADDR + SOC_ACPU_PMC_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR + SOC_ACPU_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR + SOC_ACPU_DMSS_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_0_BASE_ADDR, SOC_ACPU_DMC_0_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_1_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE },
        { SOC_ACPU_HIEPS_BASE_ADDR, SOC_ACPU_HIEPS_BASE_ADDR + SOC_ACPU_HIEPS_BASE_ADDR_SIZE },
        { MSPE_DDR_REGION_IO_BASE, MSPE_DDR_REGION_IO_BASE + MSPE_DDR_REGION_IO_SIZE },
#ifdef TEE_SUPPORT_FILE_ENCRY
        { SOC_ACPU_UFS_HCI_BASE_ADDR, SOC_ACPU_UFS_HCI_BASE_ADDR + SOC_ACPU_UFS_HCI_BASE_ADDR_SIZE },
#endif
        { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR + SOC_ACPU_SPI1_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR + SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR + SOC_ACPU_SPI3_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR + SOC_ACPU_SPI4_BASE_ADDR_SIZE },
        { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR + SOC_ACPU_I3C4_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR + SOC_ACPU_AO_IOC_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO27_BASE_ADDR, SOC_ACPU_GPIO27_BASE_ADDR + SOC_ACPU_GPIO27_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO28_BASE_ADDR, SOC_ACPU_GPIO28_BASE_ADDR + SOC_ACPU_GPIO28_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO26_BASE_ADDR, SOC_ACPU_GPIO26_BASE_ADDR + SOC_ACPU_GPIO26_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO31_BASE_ADDR, SOC_ACPU_GPIO31_BASE_ADDR + SOC_ACPU_GPIO31_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO32_BASE_ADDR, SOC_ACPU_GPIO32_BASE_ADDR + SOC_ACPU_GPIO32_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_CONFIG_BASE_ADDR, SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + SOC_ACPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_TZPC_BASE_ADDR, SOC_ACPU_AO_TZPC_BASE_ADDR + SOC_ACPU_AO_TZPC_BASE_ADDR_SIZE },
        /* DSS Reg Map */
        { DSS_BASE, DSS_BASE + DSS_BASE_SIZE },
        /* DSS GPIO Map */
        { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR + SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO1_BASE_ADDR, SOC_ACPU_GPIO1_BASE_ADDR + SOC_ACPU_GPIO1_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO2_BASE_ADDR, SOC_ACPU_GPIO2_BASE_ADDR + SOC_ACPU_GPIO2_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO3_BASE_ADDR, SOC_ACPU_GPIO3_BASE_ADDR + SOC_ACPU_GPIO3_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO23_BASE_ADDR, SOC_ACPU_GPIO23_BASE_ADDR + SOC_ACPU_GPIO23_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO25_BASE_ADDR, SOC_ACPU_GPIO25_BASE_ADDR + SOC_ACPU_GPIO25_BASE_ADDR_SIZE },
        { TS_DOORBELL_BASE_ADDR, TS_DOORBELL_BASE_ADDR + TS_DOORBELL_BASE_ADDR_SIZE },
        { TS_SRAM_BASE_ADDR, TS_SRAM_BASE_ADDR + TS_SRAM_BASE_ADDR_SIZE },
        { SMMUV3_SDMA_BASE_ADDR, SMMUV3_SDMA_BASE_ADDR + SMMUV3_SDMA_BASE_ADDR_SIZE },
        { 0, 0 } /* this is terminator */
    }
};
