WITH_OH_PLATFORM := 10
WITH_CHIP_OH_32 := 42

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_OH_PLATFORM
	PLATFORM_NAME := oh
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := oh

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_OH_32=$(WITH_CHIP_OH_32) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_OH_PLATFORM=$(WITH_OH_PLATFORM)
