set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_HI3680)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x12808000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13000000)
set(GATEKEEPER_ITRATION_TIMES 400)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)
set(TRUSTEDCORE_PLATFORM_FLAGS += -DFEATURE_SE
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DCONFIG_HISEE_14_CHANNEL_IPC
    -DTEE_SUPPORT_FILE_ENCRY
    -DTEE_SUPPORT_FILE_ENCRY_PASS_FBE2
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_SECIDENTIFICATION
)
