set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_DENVER)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x12808000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x13000000)
set(GATEKEEPER_ITRATION_TIMES 400)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 4)
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DTEE_SUPPORT_FILE_ENCRY
    -DCC_POWER_IN_SECOS
    -DTEE_SUPPORT_AI
    -DTEE_SUPPORT_AI_STATIC_ION
    -DTEE_SUPPORT_SECIDENTIFICATION
)
