/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Description: SPI regulator config.
 * Create: 2019-12-13
 */
#ifndef __SPI_CONFIG_DENVER_H__
#define __SPI_CONFIG_DENVER_H__

#include "spi_config_common.h"

static struct spi_resource spi_res[] = {
	[0] = {
		.bus_id = 2,
		.base = 0xFA868000,
		.spi_clk_bit = 30,
		.reg_clk_enable = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + 0x010,
		.reg_clk_disable = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + 0x014,
		.reg_clk_status = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + 0x018,
		.spi_clk_gate_bit = 0,
		.reg_clk_gate_enable = 0,
		.spi_reset_bit = 30,
		.reg_reset_enable = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + 0x020,
		.reg_reset_disable = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + 0x024,
		.reg_reset_status = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + 0x028,
		.clk_rate = 90000000,
		.domain = SPI_IOMCU_DOMAIN,
		.tzpc_flag = NO_NEED_SWITCH_SEC_FLAG,
		.tzpc_data.tzpc_info.addr = SOC_ACPU_IOMCU_CONFIG_BASE_ADDR,
		.tzpc_data.tzpc_info.offset = 0x100,
		.tzpc_data.tzpc_info.mask_bit = 5,
		.gpios[0] = {
			.gpio = 183,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M1,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[1] = {
			.gpio = 184,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M1,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[2] = {
			.gpio = 185,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M1,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.spi_hw.hw_valid = SPI_HARDWARE_MUTEX_VALID,
		.spi_hw.lock_id = 30,
		.spi_req_no.is_valid = SPI_DMA_REQ_NO_VALID,
		.spi_req_no.rx_req_no = 14,
		.spi_req_no.tx_req_no = 15,
	},
	[1] = {
		.bus_id = 4,
		.base = 0xFA049000,
		.spi_clk_bit = 4,
		.reg_clk_enable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x040,
		.reg_clk_disable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x044,
		.reg_clk_status = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x048,
		.spi_clk_gate_bit = 13,
		.reg_clk_gate_enable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x0F4,
		.spi_reset_bit = 15,
		.reg_reset_enable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x060,
		.reg_reset_disable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x064,
		.reg_reset_status = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x068,
		.clk_rate = 30000000,
		.domain = SPI_AP_DOMAIN,
		.tzpc_flag = NO_NEED_SWITCH_SEC_FLAG,
		.tzpc_data.tzpc_map.tzpc_idx = TZ_SPI4,
		.gpios[0] = {
			.gpio = 183,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M4,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[1] = {
			.gpio = 184,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M4,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[2] = {
			.gpio = 185,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M4,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.spi_hw.hw_valid = SPI_HARDWARE_MUTEX_VALID,
		.spi_hw.lock_id = 30,
		.spi_req_no.is_valid = SPI_DMA_REQ_NO_INVALID,
	},
	[2] = {
		.bus_id = 3,
		.base = 0xFA89F000,
		.spi_clk_bit = 10,
		.reg_clk_enable = SOC_ACPU_SCTRL_BASE_ADDR + 0x1B0,
		.reg_clk_disable = SOC_ACPU_SCTRL_BASE_ADDR + 0x1B4,
		.reg_clk_status = SOC_ACPU_SCTRL_BASE_ADDR + 0x1B8,
		.spi_clk_gate_bit = 6,
		.reg_clk_gate_enable = SOC_ACPU_SCTRL_BASE_ADDR + 0x270,
		.spi_reset_bit = 9,
		.reg_reset_enable = SOC_ACPU_SCTRL_BASE_ADDR + 0x218,
		.reg_reset_disable = SOC_ACPU_SCTRL_BASE_ADDR + 0x21C,
		.reg_reset_status = SOC_ACPU_SCTRL_BASE_ADDR + 0x220,
		.clk_rate = 74000000,
		.domain = SPI_AP_DOMAIN,
		.tzpc_flag = NO_NEED_SWITCH_SEC_FLAG,
		.tzpc_data.tzpc_map.tzpc_idx = TZ_SPI3,
		.gpios[0] = {
			.gpio = 193,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M1,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[1] = {
			.gpio = 194,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M1,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[2] = {
			.gpio = 195,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M1,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.spi_req_no.is_valid = SPI_DMA_REQ_NO_INVALID,
	},
	[3] = {
		.bus_id = 1,
		.base = 0xFA048000,
		.spi_clk_bit = 9,
		.reg_clk_enable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x020,
		.reg_clk_disable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x024,
		.reg_clk_status = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x028,
		.spi_clk_gate_bit = 13,
		.reg_clk_gate_enable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x0F4,
		.spi_reset_bit = 9,
		.reg_reset_enable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x078,
		.reg_reset_disable = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x07C,
		.reg_reset_status = SOC_ACPU_PERI_CRG_BASE_ADDR + 0x080,
		.clk_rate = 30000000,
		.domain = SPI_AP_DOMAIN,
		.tzpc_flag = NEED_SWITCH_SEC_FLAG,
		.tzpc_data.tzpc_map.tzpc_idx = TZ_SPI1,
		.gpios[0] = {
			.gpio = 188,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M4,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[1] = {
			.gpio = 189,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M4,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.gpios[2] = {
			.gpio = 190,
			.function[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_M4,
			.function[SPI_GPIO_CFG_IDLE] = GPIOMUX_M0,
			.pulltype[SPI_GPIO_CFG_DEFAULT] = GPIOMUX_NOPULL,
			.pulltype[SPI_GPIO_CFG_IDLE] = GPIOMUX_NOPULL,
		},
		.spi_hw.hw_valid = SPI_HARDWARE_MUTEX_VALID,
		.spi_hw.lock_id = 27,
		.spi_req_no.is_valid = SPI_DMA_REQ_NO_INVALID,
	},
};
#endif
