TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_NAPA
TRUSTEDCORE_PHY_TEXT_BASE := 0x13208000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x13A00000
GATEKEEPER_ITRATION_TIMES := 0
DERIVE_ROOT_INTERNAL_ITRATIONS := 0

ifeq ($(es_low_freq), true)
TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_ES_LOW_FREQ
$(warning "the chip is CONFIG_ES_LOW_FREQ")
endif
