/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2019. All rights reserved.
 * Description: drv function file for Hisilicon SSM
 * Author: ssm group
 * Create: 2019/12/11
 * Notes:
 */

#ifndef __TEE_DRV_SSM_POLICY_TABLE_H__
#define __TEE_DRV_SSM_POLICY_TABLE_H__

#include "hi_tee_module_id.h"
#include "hi_tee_ssm.h"

#define BUF_MODULE_READ  (1)
#define BUF_MODULE_WRITE (2)
#define POLICY_MOD_SRC      (1)
#define POLICY_MOD_DST      (2)
#define DRV_SSM_MAX_MOD_NUM (5)


#define BUFFER_TAG_INVALID                (0)
#define BUFFER_TAG_INTERNAL_BUF_DMX       (1)
#define BUFFER_TAG_INTERNAL_BUF_TSCIPHER  (2)
#define BUFFER_TAG_INTERNAL_BUF_MCIPHER   (3)
#define BUFFER_TAG_INTERNAL_BUF_VDEC      (4)
#define BUFFER_TAG_INTERNAL_BUF_AUDDSP    (5)
#define BUFFER_TAG_INTERNAL_BUF_VENC      (6)
#define BUFFER_TAG_INTERNAL_BUF_VPSS      (7)
#define BUFFER_TAG_INTERNAL_BUF_VDP       (8)
#define BUFFER_TAG_INTERNAL_BUF_GPU       (9)
#define BUFFER_TAG_INTERNAL_BUF_HWC       (10)
#define BUFFER_TAG_INTERNAL_BUF_JPEG_DEC  (11)
#define BUFFER_TAG_INTERNAL_BUF_JPEG_ENC  (12)
#define BUFFER_TAG_INTERNAL_BUF_NPU       (13)

#define BUFFER_TAG_DMX_VID_ES_BUF         (21)
#define BUFFER_TAG_DMX_AUD_ES_BUF         (22)
#define BUFFER_TAG_MCIPHER_VID_ES_BUF     (23)
#define BUFFER_TAG_MCIPHER_AUD_ES_BUF     (24)
#define BUFFER_TAG_MCIPHER_TS_BUF         (25)
#define BUFFER_TAG_PVR_RECORD_TS_BUF      (26)
#define BUFFER_TAG_PVR_PLAYBACK_TS_BUF    (27)

#define BUFFER_TAG_VID_FRM_BUF            (28)
#define BUFFER_TAG_VPSS_OUTPUT_BUF        (29)
#define BUFFER_TAG_VDP_OUTPUT_BUF         (30)
#define BUFFER_TAG_SECURE_INFOR_BUF       (31)
#define BUFFER_TAG_JPEG_ENCODE_OUTPUT_BUF (32)
#define BUFFER_TAG_VEDU_OUTPUT_BUF        (33)
#define BUFFER_TAG_GRAPHIC_OUPUT_BUF      (34)
#define BUFFER_TAG_NPU_OUTPUT_BUF         (35)
#define BUFFER_TAG_MAX                    (36)

#define DRV_SSM_SESSION_BUF_TYPE_NUM (BUFFER_TAG_PVR_PLAYBACK_TS_BUF - BUFFER_TAG_DMX_VID_ES_BUF + 1)

typedef struct {
    hi_mod_id  mod_id;
    hi_u32     rw_flag;
} mod_access_info;

typedef struct {
    mod_access_info     src_module[DRV_SSM_MAX_MOD_NUM];
    mod_access_info     dst_module[DRV_SSM_MAX_MOD_NUM];
    hi_u32              src_mod_num;
    hi_u32              dst_mod_num;
    hi_tee_ssm_intent   intent;
} policy_rule;

const policy_rule g_policy_table[BUFFER_TAG_MAX] = {
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_DEMUX, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_DEMUX, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_TSR2RCIPHER, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_TSR2RCIPHER, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_CIPHER, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_CIPHER, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_VDEC, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_VDEC, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_ADEC, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_ADEC, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_VENC, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_VENC, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_VPSS, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_VPSS, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_WIN, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_WIN, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_GPU, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_GPU, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_TDE, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_TDE, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_JPGDEC, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_JPGDEC, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_JPGENC, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_JPGENC, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_MAX, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_MAX, BUF_MODULE_READ |
        BUF_MODULE_WRITE}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{0}}, {{0}}, 0, 0, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_DEMUX, BUF_MODULE_WRITE}}, {{HI_ID_VDEC, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* BUFFER_TAG_DMX_VID_ES_BUF   21 */
    {{{HI_ID_DEMUX, BUF_MODULE_WRITE}}, {{HI_ID_ADEC, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* BUFFER_TAG_DMX_AUD_ES_BUF  22 */
    {{{HI_ID_CIPHER, BUF_MODULE_WRITE}}, {{HI_ID_VDEC, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* BUFFER_TAG_MCIPHER_VID_ES_BUF 23 */
    {{{HI_ID_CIPHER, BUF_MODULE_WRITE}}, {{HI_ID_ADEC, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* BUFFER_TAG_MCIPHER_AUD_ES_BUF 24 */
    {{{HI_ID_CIPHER, BUF_MODULE_WRITE}}, {{HI_ID_DEMUX, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* BUFFER_TAG_MCIPHER_TS_BUF 25 */
    {{{HI_ID_DEMUX, BUF_MODULE_WRITE}}, {{HI_ID_TSR2RCIPHER, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_RECORD}, /* BUFFER_TAG_PVR_RECORD_TS_BUF 26 */
    {{{HI_ID_TSR2RCIPHER, BUF_MODULE_WRITE}}, {{HI_ID_DEMUX, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* BUFFER_TAG_PVR_PLAYBACK_TS_BUF 27 */
    {{{HI_ID_VDEC, BUF_MODULE_WRITE}}, {{HI_ID_VPSS, BUF_MODULE_READ}, {HI_ID_WIN,
        BUF_MODULE_READ}, {HI_ID_GPU, BUF_MODULE_READ}}, 1, 3, HI_TEE_SSM_INTENT_WATCH},
    {{{HI_ID_VPSS, BUF_MODULE_WRITE}},
        {{HI_ID_WIN, BUF_MODULE_READ}, {HI_ID_TDE, BUF_MODULE_READ},
            {HI_ID_JPGENC, BUF_MODULE_READ}, {HI_ID_VENC,
            BUF_MODULE_READ}, {HI_ID_MAX, BUF_MODULE_READ}}, 1, 5, HI_TEE_SSM_INTENT_WATCH}, /* NPU pending */
    {{{HI_ID_WIN, BUF_MODULE_WRITE}}, {{HI_ID_VENC, BUF_MODULE_READ}, {HI_ID_JPGENC,
        BUF_MODULE_READ}, {HI_ID_MAX, BUF_MODULE_READ}}, 1, 3, HI_TEE_SSM_INTENT_WATCH}, /* NPU pending */
    {{{HI_ID_VDEC, BUF_MODULE_READ | BUF_MODULE_WRITE}, {HI_ID_VPSS, BUF_MODULE_READ |
        BUF_MODULE_WRITE}, {HI_ID_WIN, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {
            {HI_ID_VDEC, BUF_MODULE_READ | BUF_MODULE_WRITE},
            {HI_ID_VPSS, BUF_MODULE_READ | BUF_MODULE_WRITE},
            {HI_ID_WIN, BUF_MODULE_READ | BUF_MODULE_WRITE}
        }, 3, 3, HI_TEE_SSM_INTENT_MAX},
    {{{HI_ID_JPGENC, BUF_MODULE_WRITE}}, {{HI_ID_CIPHER, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_EXPORT},
    {{{HI_ID_VENC, BUF_MODULE_WRITE}}, {{HI_ID_CIPHER, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_EXPORT},
    {{{HI_ID_GPU, BUF_MODULE_WRITE}},
        {{HI_ID_WIN, BUF_MODULE_READ}, {HI_ID_TDE, BUF_MODULE_READ | BUF_MODULE_WRITE}},
        1, 2, HI_TEE_SSM_INTENT_WATCH},
    {{{HI_ID_MAX, BUF_MODULE_READ | BUF_MODULE_WRITE}}, {{HI_ID_WIN, BUF_MODULE_READ}},
        1, 1, HI_TEE_SSM_INTENT_WATCH}, /* NPU pending */
};

#endif

