/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Description:about npu spec share
 */
#ifndef __NPU_SPEC_SHARE_H
#define __NPU_SPEC_SHARE_H

/* ******just for ai core bypass mode********* */
#define AI_PAGE_SIZE    4096
#define AI_PAGE_MASK    (~(AI_PAGE_SIZE - 1))

#ifdef PAGE_SHIFT
#undef PAGE_SHIFT
#endif
#define PAGE_SHIFT 12

#define DEVDRV_MAX_SINK_STREAM_ID	16
#define DEVDRV_MAX_NON_SINK_STREAM_ID	16
#define DEVDRV_MAX_STREAM_ID	32
#define DEVDRV_MAX_EVENT_ID		16
#define DEVDRV_MAX_MODEL_ID		64
#define DEVDRV_MAX_TASK_ID		15000
#define DEVDRV_MAX_NOTIFY_ID	256

#define MAX_DAVINCI_NUM_OF_ONE_CHIP       4

#define DEVDRV_SHM_MAPS_SIZE    (4 * 1024 * 1024)

#define DEVDRV_SRAM_TS_SHM_SIZE 0x1000

#define DEVDRV_SQ_SLOT_SIZE	64
#define DEVDRV_CQ_SLOT_SIZE	16
#define DEVDRV_MAX_CQ_SLOT_SIZE    128

#define DEVDRV_CACHELINE_OFFSET	6
#define DEVDRV_CACHELINE_SIZE		64
#define DEVDRV_CACHELINE_MASK		(DEVDRV_CACHELINE_SIZE - 1)

#define DEVDRV_MAX_CQ_DEPTH	1024

#define DEVDRV_MAX_DAVINCI_NUM	1
#define DEVDRV_MAX_SQ_DEPTH 	256

#define DEVDRV_MAX_SQ_NUM	16
#define DEVDRV_MAX_CQ_NUM	1
#define DEVDRV_MAX_DFX_SQ_NUM	4
#define DEVDRV_MAX_DFX_CQ_NUM	10

#define DEVDRV_DOORBELL_FIRST_CALC_CQ_INDEX 64 // must be consistent with doorbell_plat.h on ts side

#define DEVDRV_FUNCTIONAL_SQ_FIRST_INDEX    112
#define DEVDRV_FUNCTIONAL_CQ_FIRST_INDEX    116

#define DEVDRV_MAX_FUNCTIONAL_SQ_NUM        4
#define DEVDRV_MAX_FUNCTIONAL_CQ_NUM        10

#define DEVDRV_MAILBOX_MAX_FEEDBACK  16
#define DEVDRV_MAILBOX_STOP_THREAD   0x0FFFFFFF
#define DEVDRV_BUS_DOWN              0x0F00FFFF

#define DEDVRV_DEV_PROCESS_HANG		0x0F0000FF

#define DEVDRV_HCCL_NAME_SIZE		64
#define DEVDRV_HCCL_MAX_NODE_NUM	128

#define DEVDRV_MAX_INTERRUPT_NUM	32
#define DEVDRV_MAX_MEMORY_DUMP_SIZE (4 * 1024 * 1024)

#define DEVDRV_USER_CONFIG_NAME_LEN 32
#define DEVDRV_USER_CONFIG_VALUE_LEN 128

#define DEVDRV_BB_DEVICE_ID_INFORM	0x66020004
#define CHIP_BASEADDR_PA_OFFSET (0x200000000000ULL)

#define	PMU_EMMC_VCC_CHANNEL	7
#define	PMU_EMMC_VCCQ_CHANNEL	14
#define ADCIN7_SLOT0 7
#define ADCIN8_SLOT1 8

/*
|___SQ___|____INFO_____|__DOORBELL___|___CQ____|___TaskPool___|
*/
#define DEVDRV_VM_TASKPOOL_REAL   (1 * 1024 * 1024)
#define DEVDRV_VM_TASKPOOL_OFFSET (12 * 1024 * 1024)
#define DEVDRV_VM_BLOCK_OFFSET  (32 * 1024 * 1024)
#define DEVDRV_VM_CQ_QUEUE_SIZE (64 * 1024 * 1024)
#define DEVDRV_VM_CQ_SLOT_SIZE  (128 * 1024)

#endif
