/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: plat_cfg defines
 * Create: 2020-03
 */
#include "plat_cfg.h"
#include <autoconf.h>
#include <hisi_platform.h>
#include <plat_features.h>
#include "plat_cfg_public.h"
#include "uart_register.h"

#ifndef __aarch64__
#error "Only aarch64 is supported!"
#endif

struct platform_info g_plat_cfg = {
    /* value is assigned in boot_kernel_on_current_cpu function */
    .phys_region_start = 0,
    .phys_region_size = TEEOS_MEM_SIZE,
    .uart_addr = UART_ADDR,
    .uart_type = UART_DISABLE_FLAG | PL011_TYPE,
    .shmem_offset = SHMEM_OFFSET,
    .shmem_size = SHMEM_SIZE,
    /*
     * refer to device/hisi/customize/dtsi/arm64/baltimore/baltimore_memory.dtsi
     * Last page(4K) of Bl31 memory(MSPC/HISEE memory) is used as the share memory
     * between ATF with TEEOS for MSPC.
     * Unprotect share memory of atf and teeos:0x13101000~0x13102000
    */
    .protected_regions = { { PROTECTED_REGION_START, PROTECTED_REGION_END } },

    .gic_config = {
        .version = GIC_V3_VERSION,
        .v3 = {
            .dist = { GIC_V3_DIST_ADDR, GIC_V3_DIST_ADDR + GIC_DIST_PAGENUM * PAGE_SIZE },
            .redist_num = GIC_REDIST_NUM,
            .redist_stride = GIC_REDIST_MEMSIZE,
            .redist = {
                { GIC_V3_REDIST_ADDR, GIC_V3_REDIST_ADDR + GIC_REDIST_PAGENUM * PAGE_SIZE }
            }
        }
    },

    .spi_num_for_notify = SPI_NUM,

    .plat_features =
#ifdef CONFIG_ARM64_PAN
    PLAT_DEF_ENG | PLAT_ENABLE_PAN,
#else
    PLAT_DEF_ENG,
#endif

    /* at most PLAT_MAX_DEVIO_REGIONS (128) regions, the first region should be UART6 */
    .plat_io_regions = {
        /* .start,     .end */
        { SOC_ACPU_VDEC_BASE_ADDR, SOC_ACPU_VDEC_BASE_ADDR + SOC_ACPU_VDEC_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_DMAC_BASE_ADDR, SOC_ACPU_IOMCU_DMAC_BASE_ADDR + SOC_ACPU_IOMCU_DMAC_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO28_BASE_ADDR, SOC_ACPU_GPIO28_BASE_ADDR + SOC_ACPU_GPIO28_BASE_ADDR_SIZE },
        { FINGERPRINT_XX, FINGERPRINT_XX + FINGERPRINT_XX_SIZE },
        { HIEPS_CDRM_BASE_ADDR, HIEPS_CDRM_BASE_ADDR + HIEPS_CDRM_ADDR_SIZE },
        { SOC_ACPU_EPS_MMU_BASE_ADDR, SOC_ACPU_EPS_MMU_BASE_ADDR + SOC_ACPU_EPS_MMU_BASE_SIZE },
        { SOC_ACPU_EPS_PKE2_BASE_ADDR, SOC_ACPU_EPS_PKE2_BASE_ADDR + SOC_ACPU_EPS_PKE2_BASE_SIZE },
        { SOC_ACPU_EPS_PKE_BASE_ADDR, SOC_ACPU_EPS_PKE_BASE_ADDR + SOC_ACPU_EPS_PKE_BASE_SIZE },
        { SOC_ACPU_EPS_SCE_BASE_ADDR, SOC_ACPU_EPS_SCE_BASE_ADDR + SOC_ACPU_EPS_SCE_BASE_SIZE },
        { SOC_ACPU_EPS_KM_BASE_ADDR, SOC_ACPU_EPS_KM_BASE_ADDR + SOC_ACPU_EPS_KM_BASE_SIZE },
        { SOC_ACPU_EPS_SCE2_BASE_ADDR, SOC_ACPU_EPS_SCE2_BASE_ADDR + SOC_ACPU_EPS_SCE2_BASE_SIZE },
        { SOC_ACPU_EPS_TIMER_BASE_ADDR, SOC_ACPU_EPS_TIMER_BASE_ADDR + SOC_ACPU_EPS_TIMER_BASE_SIZE },
        { SOC_ACPU_EPS_TRNG_BASE_ADDR, SOC_ACPU_EPS_TRNG_BASE_ADDR + SOC_ACPU_EPS_TRNG_BASE_SIZE },
        { SOC_ACPU_EPS_ETZPC_BASE_ADDR, SOC_ACPU_EPS_ETZPC_BASE_ADDR + SOC_ACPU_EPS_ETZPC_BASE_SIZE },
        { SOC_ACPU_EPS_CONFIG_BASE_ADDR, SOC_ACPU_EPS_CONFIG_BASE_ADDR + SOC_ACPU_EPS_CONFIG_BASE_SIZE },
        { SOC_ACPU_MEDIA2_CRG_BASE_ADDR, SOC_ACPU_MEDIA2_CRG_BASE_ADDR + SOC_ACPU_MEDIA2_CRG_BASE_SIZE },
        { ACPU_SYS_CNT_BASE_ADDR, ACPU_SYS_CNT_BASE_ADDR + ACPU_SYS_CNT_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_NS_BASE_ADDR, SOC_ACPU_IPC_NS_BASE_ADDR + SOC_ACPU_IPC_NS_BASE_ADDR_SIZE },
        { SOC_ACPU_IPC_BASE_ADDR, SOC_ACPU_IPC_BASE_ADDR + SOC_ACPU_IPC_BASE_ADDR_SIZE },
        { SOC_ACPU_TIMER10_BASE_ADDR, SOC_ACPU_TIMER10_BASE_ADDR + SOC_ACPU_TIMER10_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_IPC_S_BASE_ADDR, SOC_ACPU_AO_IPC_S_BASE_ADDR + SOC_ACPU_AO_IPC_S_BASE_ADDR_SIZE },
        { SOC_ACPU_ACTRL_BASE_ADDR, SOC_ACPU_ACTRL_BASE_ADDR + SOC_ACPU_ACTRL_BASE_ADDR_SIZE },
        { SOC_ACPU_PCTRL_BASE_ADDR, SOC_ACPU_PCTRL_BASE_ADDR + SOC_ACPU_PCTRL_BASE_ADDR_SIZE },
        { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR + SOC_ACPU_SCTRL_BASE_ADDR_SIZE },
        { SOC_ACPU_DMC_0_BASE_ADDR, SOC_ACPU_DMC_0_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE  },
        { SOC_ACPU_DMC_1_BASE_ADDR, SOC_ACPU_DMC_1_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE  },
        { SOC_ACPU_DMC_2_BASE_ADDR, SOC_ACPU_DMC_2_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE  },
        { SOC_ACPU_DMC_3_BASE_ADDR, SOC_ACPU_DMC_3_BASE_ADDR + SOC_ACPU_DMC_BASE_ADDR_SIZE  },
        { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR + SOC_ACPU_SPI1_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_SPI2_BASE_ADDR, SOC_ACPU_IOMCU_SPI2_BASE_ADDR + SOC_ACPU_IOMCU_SPI2_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR + SOC_ACPU_SPI3_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR + SOC_ACPU_SPI4_BASE_ADDR_SIZE },
        { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR + SOC_ACPU_I3C4_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI1_BASE_ADDR, SOC_ACPU_SPI1_BASE_ADDR + SOC_ACPU_SPI1_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI3_BASE_ADDR, SOC_ACPU_SPI3_BASE_ADDR + SOC_ACPU_SPI3_BASE_ADDR_SIZE },
        { SOC_ACPU_SPI4_BASE_ADDR, SOC_ACPU_SPI4_BASE_ADDR + SOC_ACPU_SPI4_BASE_ADDR_SIZE },
        { SOC_ACPU_I3C4_BASE_ADDR, SOC_ACPU_I3C4_BASE_ADDR + SOC_ACPU_I3C4_BASE_ADDR_SIZE },
        { SOC_ACPU_AO_IOC_BASE_ADDR, SOC_ACPU_AO_IOC_BASE_ADDR + SOC_ACPU_AO_IOC_BASE_ADDR_SIZE },
        { SOC_ACPU_IOC_BASE_ADDR, SOC_ACPU_IOC_BASE_ADDR + SOC_ACPU_IOC_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO21_BASE_ADDR, SOC_ACPU_GPIO21_BASE_ADDR + SOC_ACPU_GPIO21_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO0_SE_BASE_ADDR, SOC_ACPU_GPIO0_SE_BASE_ADDR + SOC_ACPU_GPIO0_SE_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO1_SE_BASE_ADDR, SOC_ACPU_GPIO1_SE_BASE_ADDR + SOC_ACPU_GPIO1_SE_BASE_ADDR_SIZE },
        { AO_TZPC, AO_TZPC + AO_TZPC_SIZE },
        { SOC_ACPU_GPIO22_BASE_ADDR, SOC_ACPU_GPIO22_BASE_ADDR + SOC_ACPU_GPIO22_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO0_BASE_ADDR, SOC_ACPU_GPIO0_BASE_ADDR + SOC_ACPU_GPIO0_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO1_BASE_ADDR, SOC_ACPU_GPIO1_BASE_ADDR + SOC_ACPU_GPIO1_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO5_BASE_ADDR, SOC_ACPU_GPIO5_BASE_ADDR + SOC_ACPU_GPIO5_BASE_ADDR_SIZE },
        { SOC_ACPU_GPIO6_BASE_ADDR, SOC_ACPU_GPIO6_BASE_ADDR + SOC_ACPU_GPIO6_BASE_ADDR_SIZE },
        { SOC_ACPU_IOMCU_CONFIG_BASE_ADDR, SOC_ACPU_IOMCU_CONFIG_BASE_ADDR + SOC_ACPU_IOMCU_CONFIG_BASE_ADDR_SIZE },
        { SOC_ACPU_CSI_ADAPTER_BASE_ADDR, SOC_ACPU_CSI_ADAPTER_BASE_ADDR + SOC_ACPU_CSI_ADAPTER_BASE_ADDR_SIZE },
        { TIMER1_BASE, TIMER1_BASE + TIMER1_BASE_SIZE },
        { TIMER7_BASE, TIMER7_BASE + TIMER7_BASE_SIZE },
        { RTC_BASE_ADDR, RTC_BASE_ADDR + RTC_BASE_ADDR_SIZE },
        { REG_BASE_SCTRL, REG_BASE_SCTRL + REG_BASE_SCTRL_SIZE },
        { REG_BASE_PERI_CRG, REG_BASE_PERI_CRG + REG_BASE_PERI_CRG_SIZE },
        { REG_BASE_PCTRL, REG_BASE_PCTRL + REG_BASE_PCTRL_SIZE },
        { SMMUV3_TS_TBU_BASE_ADDR, SMMUV3_TS_TBU_BASE_ADDR + SMMUV3_TS_TBU_BASE_SIZE },
        { SOC_ACPU_TSCPU_SYSCTRL_BASE_ADDR, SOC_ACPU_TSCPU_SYSCTRL_BASE_ADDR + SOC_ACPU_TSCPU_SYSCTRL_BASE_SIZE },
        { SOC_ACPU_TS_SECURE0_BASE_ADDR, SOC_ACPU_TS_SECURE0_BASE_ADDR + SOC_ACPU_TS_SECURE0_BASE_SIZE },
        { SOC_ACPU_AIC0_SMMU_CFG_BASE_ADDR, SOC_ACPU_AIC0_SMMU_CFG_BASE_ADDR + SOC_ACPU_AIC0_SMMU_CFG_BASE_SIZE },
        { SOC_ACPU_AIC1_SMMU_CFG_BASE_ADDR, SOC_ACPU_AIC1_SMMU_CFG_BASE_ADDR + SOC_ACPU_AIC1_SMMU_CFG_BASE_SIZE },
        { SOC_ACPU_HWTS_ADDR, SOC_ACPU_HWTS_ADDR + SOC_ACPU_HWTS_SIZE },
        { SOC_ACPU_AIC0_BASE_ADDR, SOC_ACPU_AIC0_BASE_ADDR + SOC_ACPU_AIC0_BASE_SIZE },
        { SOC_ACPU_AIC1_BASE_ADDR, SOC_ACPU_AIC1_BASE_ADDR + SOC_ACPU_AIC1_BASE_SIZE },
        { SOC_ACPU_DMSS_BASE_ADDR, SOC_ACPU_DMSS_BASE_ADDR + SOC_ACPU_DMSS_BASE_ADDR_SIZE  },
        { SOC_ACPU_ISP_CORE_CFG_BASE_ADDR, SOC_ACPU_ISP_CORE_CFG_BASE_ADDR + SOC_ACPU_ISP_CORE_CFG_BASE_ADDR_SIZE },
        { DSS_BASE, DSS_BASE + DSS_BASE_SIZE },
        { PCTRL_BASE, PCTRL_BASE + PCTRL_BASE_SIZE },
        { MMBUF_CFG_BASE, MMBUF_CFG_BASE + MMBUF_CFG_BASE_SIZE  },
        { NOC_DSS_BASE, NOC_DSS_BASE + NOC_DSS_BASE_SIZE },
        { PMC_BASE, PMC_BASE + PMC_BASE_SIZE },
        { GPIO_SPI, GPIO_SPI + GPIO_SPI_SIZE },
        { TZPC, TZPC + TZPC_SIZE },
        { AO_TZPC, AO_TZPC + AO_TZPC_SIZE },
        { CRG_BASE, CRG_BASE + CRG_BASE_SIZE },
        { MEDIA_CRG_BASE_ADDR, MEDIA_CRG_BASE_ADDR + MEDIA_CRG_BASE_ADDR_SIZE },
        { HIFI_CFG_BASE_ADDR, HIFI_CFG_BASE_ADDR + HIFI_CFG_BASE_ADDR_SIZE },
        { HIFI_CFG_DMMU_BASE_ADDR, HIFI_CFG_DMMU_BASE_ADDR + HIFI_CFG_DMMU_BASE_SIZE },
        { HI_IPCM_REGBASE_ADDR, HI_IPCM_REGBASE_ADDR + HI_IPCM_REGBASE_ADDR_SIZE },
        { SOCP_BASE_ADDR, SOCP_BASE_ADDR + SOCP_BASE_ADDR_SIZE },
        { HI_SYSCTRL_BASE_ADDR, HI_SYSCTRL_BASE_ADDR + HI_SYSCTRL_BASE_ADDR_SIZE },
        { HI_WDT_BASE_ADDR_VIRT, HI_WDT_BASE_ADDR_VIRT + HI_WDT_BASE_ADDR_VIRT_SIZE },
        { SOC_ACPU_SCTRL_BASE_ADDR, SOC_ACPU_SCTRL_BASE_ADDR + SOC_ACPU_SCTRL_BASE_ADDR_SIZE },
        { SECBOOT_XX, SECBOOT_XX + SECBOOT_XX_SIZE },
        { RESET_PIN_GPIO_ADDR, RESET_PIN_GPIO_ADDR + RESET_PIN_GPIO_ADDR_SIZE },
        { CAMBRICON_X1, CAMBRICON_X1 + CAMBRICON_X1_SIZE },
        { CAMBRICON_X2, CAMBRICON_X2 + CAMBRICON_X2_SIZE },
        { DX_BASE_CC, DX_BASE_CC + DX_BASE_CC_SIZE },
        { DX_BASE_ATLANTA, DX_BASE_ATLANTA + DX_BASE_ATL_SIZE },
        { HISEE_MBOX_BASE_ADDR, HISEE_MBOX_BASE_ADDR + HISEE_MBOX_BASE_ADDR_SIZE },
        { HISEE_IPC_BASE_ADDR, HISEE_IPC_BASE_ADDR + HISEE_IPC_BASE_ADDR_SIZE },
#ifdef TEE_SUPPORT_FILE_ENCRY
        { SOC_ACPU_UFS_CFG_BASE_ADDR, SOC_ACPU_UFS_CFG_BASE_ADDR + SOC_ACPU_UFS_CFG_BASE_ADDR_SIZE },
#endif
        { SMMUV3_MEDIA1_TCU_BASE_ADDR, SMMUV3_MEDIA1_TCU_BASE_ADDR + SMMUV3_MEDIA1_TCU_ADDR_SIZE },
        { SMMUV3_MEDIA2_TCU_BASE_ADDR, SMMUV3_MEDIA2_TCU_BASE_ADDR + SMMUV3_MEDIA2_TCU_ADDR_SIZE },
        { SMMUV3_NPU_TCU_BASE_ADDR, SMMUV3_NPU_TCU_BASE_ADDR + SMMUV3_NPU_TCU_ADDR_SIZE },
        { SOC_IVP_IMAGE_BASE_ADDR_0, SOC_IVP_IMAGE_BASE_ADDR_0 + SOC_IVP_IMAGE_BASE_ADDR_SIZE },
        { SOC_IVP_IMAGE_BASE_ADDR_1, SOC_IVP_IMAGE_BASE_ADDR_1 + SOC_IVP_IMAGE_BASE_ADDR_SIZE },
        { HDCP_ADDR, HDCP_ADDR + HDCP_ADDR_SIZE },
        { HDCP_DSS_ADDR, HDCP_DSS_ADDR + HDCP_DSS_ADDR_SIZE },
        { SENSORHUB_IPC_BASE_ADDR, SENSORHUB_IPC_BASE_ADDR + SENSORHUB_IPC_BASE_ADDR_SIZE },
        { REG_BASE_SCTRL, REG_BASE_SCTRL + REG_BASE_SCTRL_SIZE },
        { REG_BASE_PCTRL, REG_BASE_PCTRL + REG_BASE_PCTRL_SIZE },
        { 0, 0 } /* this is terminator */
}

};
