/*
 * Copyright (C) Hisilicon Technologies Co., Ltd. 2019. All rights reserved.
 * Description: Errcode of the system.
 */

#ifndef __HI_TEE_ERRCODE_H__
#define __HI_TEE_ERRCODE_H__

#include "hi_type_dev.h"
#include "hi_tee_module_id.h"

#define HI_TEE_ERRCODE_DEF(moduleid, errid)     (hi_s32)(0x80000000 | ((moduleid) << 16)  | (errid))

/* Operation Error Define */
#define HI_TEE_ERR_DEVICE                       HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0001)    /* Device Operation Error */
#define HI_TEE_ERR_MEM                          HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0002)    /* Memory Operation Error */
#define HI_TEE_ERR_SEM                          HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0003)    /* Semaphore Operation Error */
#define HI_TEE_ERR_TIMER                        HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0004)    /* Timer Operation error */
#define HI_TEE_ERR_DATABASE                     HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0005)    /* Database Operation Error */
#define HI_TEE_ERR_THREAD                       HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0006)    /* Thread Operation Error */
#define HI_TEE_ERR_FILE                         HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0007)    /* File Operation Error */
#define HI_TEE_ERR_FLASH                        HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0008)    /* Flash Operation Error */
#define HI_TEE_ERR_CHANNEL                      HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x0009)    /* Channel Operation Error */
#define HI_TEE_ERR_LOCK                         HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x000A)    /* Lock Operation Error */
#define HI_TEE_ERR_IOCTRL                       HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x000B)    /* IO Operation Error */
#define HI_TEE_ERR_ENCRYPT                      HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x000C)    /* Encrypt Operation Error */
#define HI_TEE_ERR_DECRYPT                      HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x000D)    /* Decrypt Operation Error */
#define HI_TEE_ERR_VERIFY                       HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x000E)    /* Verify Operation Error */

/* Status Error Define */
#define HI_TEE_ERR_STATUS                       HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1001)    /* Status Error */
#define HI_TEE_ERR_TIMEOUT                      HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1002)    /* Time Out Error */
#define HI_TEE_ERR_INUSE                        HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1003)    /* In use(Something is Busy) */
#define HI_TEE_ERR_EXIST                        HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1004)    /* Already exists */
#define HI_TEE_ERR_NOEXIST                      HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1005)    /* Non-existent */
#define HI_TEE_ERR_INITED                       HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1006)    /* Already initialized */
#define HI_TEE_ERR_UNINITED                     HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1007)    /* Not initialized */
#define HI_TEE_ERR_UNSUPPORTED                  HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1008)    /* Unsupported */
#define HI_TEE_ERR_UNAVAILABLE                  HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x1009)    /* Unavailable */
#define HI_TEE_ERR_OVERFLOW                     HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x100A)    /* Overflow */
#define HI_TEE_ERR_NOPERMISSION                 HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x100B)    /* Have no authority */
#define HI_TEE_ERR_NORESOURCES                  HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x100C)    /* Lack of resources */

/* Other Error Define */
#define HI_TEE_ERR_ILLEGAL_IMAGE                HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2001)    /* Illegal Image */
#define HI_TEE_ERR_ILLEGAL_UUID                 HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2002)    /* Illegal UUID */
#define HI_TEE_ERR_ILLEGAL_KEY                  HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2003)    /* Illegal KEY */
#define HI_TEE_ERR_ILLEGAL_PID                  HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2004)    /* Illegal PID */
#define HI_TEE_ERR_ILLEGAL_VERSION              HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2005)    /* Illegal Version */
#define HI_TEE_ERR_INVALID_HANDLE               HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2006)    /* Invalid Handle */
#define HI_TEE_ERR_INVALID_PTR                  HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2007)    /* Invalid Pointer */
#define HI_TEE_ERR_INVALID_PARAM                HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2008)    /* Invalid Parameter */
#define HI_TEE_ERR_INVALID_ADDR                 HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x2009)    /* Invalid Address */
#define HI_TEE_ERR_INVALID_LENGTH               HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x200A)    /* Invalid Length */
#define HI_TEE_ERR_EXTERNAL                     HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x200B)    /* External Error */
#define HI_TEE_ERR_UNKNOWNED                    HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x200C)    /* Unknown Error */
#define HI_TEE_ERR_INVALID_TAID                 HI_TEE_ERRCODE_DEF(HI_ID_LOG, 0x200D)    /* INVALID TAID */

/* Module Error Define */
#define HI_ERR_DMX_INVALID_PARA                 HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0001)
#define HI_ERR_DMX_NOT_SUPPORT                  HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0002)
#define HI_ERR_DMX_UNMATCH_CHAN                 HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0003)
#define HI_ERR_DMX_NOATTACH_KEY                 HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0004)
#define HI_ERR_DMX_UNMATCH_KEY                  HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0005)
#define HI_ERR_DMX_NOFREE_KEY                   HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0006)
#define HI_ERR_DMX_ATTACHED_KEY                 HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0007)
#define HI_ERR_DMX_OCCUPIED_PID                 HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0008)
#define HI_ERR_DMX_BUSY_CHAN                    HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x0009)
#define HI_ERR_DMX_BUSY_KEY                     HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x000A)
#define HI_ERR_DMX_UUID_FAIL                    HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x000B)
#define HI_ERR_DMX_PLAY_DESC_INVALID            HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x000C)
#define HI_ERR_DMX_REC_DESC_INVALID             HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x000D)
#define HI_ERR_DMX_TS_DESC_INVALID              HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x000E)
#define HI_ERR_DMX_NO_RESOURCE                  HI_TEE_ERRCODE_DEF(HI_ID_DEMUX, 0x000F)

#define HI_ERR_CIPHER_NOT_INIT                  HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0001)
#define HI_ERR_CIPHER_INVALID_HANDLE            HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0002)
#define HI_ERR_CIPHER_INVALID_POINT             HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0003)
#define HI_ERR_CIPHER_INVALID_PARA              HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0004)
#define HI_ERR_CIPHER_FAILED_INIT               HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0005)
#define HI_ERR_CIPHER_FAILED_GETHANDLE          HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0006)
#define HI_ERR_CIPHER_FAILED_RELEASEHANDLE      HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0007)
#define HI_ERR_CIPHER_FAILED_CONFIGAES          HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0008)
#define HI_ERR_CIPHER_FAILED_CONFIGDES          HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0009)
#define HI_ERR_CIPHER_FAILED_ENCRYPT            HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X000A)
#define HI_ERR_CIPHER_FAILED_DECRYPT            HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X000B)
#define HI_ERR_CIPHER_BUSY                      HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X000C)
#define HI_ERR_CIPHER_NO_AVAILABLE_RNG          HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X000D)
#define HI_ERR_CIPHER_FAILED_MEM                HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0010)
#define HI_ERR_CIPHER_UNAVAILABLE               HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0011)
#define HI_ERR_CIPHER_OVERFLOW                  HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0012)
#define HI_ERR_CIPHER_HARD_STATUS               HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0013)
#define HI_ERR_CIPHER_TIMEOUT                   HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0014)
#define HI_ERR_CIPHER_UNSUPPORTED               HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0015)
#define HI_ERR_CIPHER_REGISTER_IRQ              HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0016)
#define HI_ERR_CIPHER_ILLEGAL_UUID              HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0017)
#define HI_ERR_CIPHER_ILLEGAL_KEY               HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0018)
#define HI_ERR_CIPHER_INVALID_ADDR              HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X0019)
#define HI_ERR_CIPHER_INVALID_LENGTH            HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X001A)
#define HI_ERR_CIPHER_ILLEGAL_DATA              HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X001B)
#define HI_ERR_CIPHER_RSA_SIGN                  HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X001C)
#define HI_ERR_CIPHER_RSA_VERIFY                HI_TEE_ERRCODE_DEF(HI_ID_CIPHER, 0X001D)


#define HI_ERR_KLAD_NOT_INIT                    HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0001)
#define HI_ERR_KLAD_NULL_PTR                    HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0002)
#define HI_ERR_KLAD_INVALID_HANDLE              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0003)
#define HI_ERR_KLAD_INVALID_ALG                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0004)
#define HI_ERR_KLAD_INVALID_TARGET              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0005)
#define HI_ERR_KLAD_INVALID_TARGETADDR          HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0006)
#define HI_ERR_KLAD_NO_MEMORY                   HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0007)
#define HI_ERR_KLAD_WAIT_TIMEOUT                HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0008)
#define HI_ERR_KLAD_NOT_FIND_KLAD               HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0009)
#define HI_ERR_KLAD_NOT_FIND_SESSION            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x000A)
#define HI_ERR_KLAD_NOT_SET_ATTR                HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x000B)
#define HI_ERR_KLAD_NOT_FIND_CALLBACK           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x000C)
#define HI_ERR_KLAD_KEY_NOT_READY               HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x000D)
#define HI_ERR_KLAD_ALREADY_SETATTR             HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x000E)
#define HI_ERR_KLAD_NOT_SET_SESSIONKEY          HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x000F)
#define HI_ERR_KLAD_NOT_SET_CONTENTKEY          HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0010)
#define HI_ERR_KLAD_ALREADY_SETTARGET           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0011)
#define HI_ERR_KLAD_NOT_SETTARGET               HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0012)
#define HI_ERR_KLAD_DETACH_ERRTARGET            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0013)
#define HI_ERR_KLAD_INVALID_LEVEL               HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0014)
#define HI_ERR_KLAD_UNAVAILABLE_TARGET          HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0015)
#define HI_ERR_KLAD_FAILED_SETIV                HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0016)
#define HI_ERR_KLAD_INVALID_ENGINE              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0017)
#define HI_ERR_KLAD_INVALID_EVENORODD           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0018)
#define HI_ERR_KLAD_NOT_SUPPORT                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0019)
#define HI_ERR_KLAD_INVALID_IVLENGTH            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x001A)
#define HI_ERR_KLAD_NO_RESOURCE                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x001B)
#define HI_ERR_KLAD_UNKNOWN_CMD                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x001C)
#define HI_ERR_KLAD_OPEN_ERR                    HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x001D)
#define HI_ERR_KLAD_INVALID_PARAM               HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x001E)
#define HI_ERR_KLAD_TASK_ID_MISMATCH            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x001F)
#define HI_ERR_KLAD_CHECK_BASE                  HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0020)
#define HI_ERR_KLAD_CHECK_OTP_CONFIG_DISABLE    HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0021)
#define HI_ERR_KLAD_CHECK_LEVEL                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0022)
#define HI_ERR_KLAD_CHECK_DSC_MODE              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0023)
#define HI_ERR_KLAD_CHECK_PORT                  HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0024)
#define HI_ERR_KLAD_CHECK_ROOTKEY_NOT_READY     HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0025)
#define HI_ERR_KLAD_CHECK_LEVEL1_NOT_READY      HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0026)
#define HI_ERR_KLAD_CHECK_LEVEL2_NOT_READY      HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0027)
#define HI_ERR_KLAD_CHECK_LEVEL3_NOT_READY      HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0028)
#define HI_ERR_KLAD_CHECK_LEVEL4_NOT_READY      HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0029)
#define HI_ERR_KLAD_CHECK_LEVEL5_NOT_READY      HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x002A)
#define HI_ERR_KLAD_CHECK_DCAS_PROFILE          HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x002B)
#define HI_ERR_KLAD_CHECK_TDES_KEY              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x002C)
#define HI_ERR_KLAD_CHECK_C2_TA_HASH            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x002D)
#define HI_ERR_KLAD_CHECK_CLEAR_CW_CONFIG       HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x002E)
#define HI_ERR_KLAD_CHECK_CW                    HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0032)
#define HI_ERR_KLAD_CHECK_TEE_ENABLE            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0034)

#define HI_ERR_KLAD_SECURE_ATTR_UINIT           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0040)
#define HI_ERR_KLAD_REQUIRE_IRQ_FAILED          HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0041)
#define HI_ERR_KLAD_SEC_FAILED                  HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0042)
#define HI_ERR_KLAD_MUTEX                       HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0043)
#define HI_ERR_KLAD_MEM_MAP                     HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0044)
#define HI_ERR_KLAD_IOCTL_CMD_INVALID           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0045)
#define HI_ERR_KLAD_LOCK_FAILED                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0046)
#define HI_ERR_KLAD_IOCTL_FUNC_NULL             HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0047)

#define HI_ERR_KLAD_COM_LOCK_FAILED             HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0050)
#define HI_ERR_KLAD_COM_UNLOCK_FAILED           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0051)
#define HI_ERR_KLAD_TA_LOCK_FAILED              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0052)
#define HI_ERR_KLAD_TA_UNLOCK_FAILED            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0053)
#define HI_ERR_KLAD_CLR_LOCK_FAILED             HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0054)
#define HI_ERR_KLAD_CLR_UNLOCK_FAILED           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0055)
#define HI_ERR_KLAD_FP_LOCK_FAILED              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0056)
#define HI_ERR_KLAD_FP_UNLOCK_FAILED            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0057)
#define HI_ERR_KLAD_NONCE_LOCK_FAILED           HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0058)
#define HI_ERR_KLAD_NONCE_UNLOCK_FAILED         HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0059)
#define HI_ERR_KLAD_UNLOCKED                    HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x005A)
#define HI_ERR_KLAD_LOCKED                      HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x005B)
#define HI_ERR_KLAD_RKP_INVALID_MODULE_ID       HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x005C)
#define HI_ERR_KLAD_ASYNC_UNFINISHED            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x005D)
#define HI_ERR_KLAD_NOT_FIND_MODID              HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x005E)
#define HI_ERR_KLAD_NOT_FIND_RK_SLOT            HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x005F)
#define HI_ERR_KLAD_NOT_CREATED                 HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0060)
#define HI_ERR_KLAD_HAVE_CREATED                HI_TEE_ERRCODE_DEF(HI_ID_KLAD, 0x0061)

#define HI_ERR_OTP_NULL_PTR                     HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0001)
#define HI_ERR_OTP_INVALID_ADDR                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0002)
#define HI_ERR_OTP_INVALID_KEYLEN               HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0003)
#define HI_ERR_OTP_INVALID_CHIPIDLEN            HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0004)
#define HI_ERR_OTP_INVALID_PARA                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0005)
#define HI_ERR_OTP_VERSION_FULL                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0006)
#define HI_ERR_OTP_NOT_INITRDY                  HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0007)
#define HI_ERR_OTP_FAIL_PRMRD                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0008)
#define HI_ERR_OTP_FAIL_RD                      HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0009)
#define HI_ERR_OTP_DISABLE_PROG                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x000a)

#define HI_ERR_OTP_FULL_VERSION                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x000b)
#define HI_ERR_OTP_FAILED_CHECKVERSION          HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x000c)
#define HI_ERR_OTP_FAILED_AUTH                  HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x000d)
#define HI_ERR_OTP_TAID_SETED                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x000f)
#define HI_ERR_OTP_INVALID_TAID                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0010)
#define HI_ERR_OTP_DUPLICATE_TAID               HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0011)
#define HI_ERR_OTP_NO_AVAILABLE_INDEX           HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0012)
#define HI_ERR_OTP_FUSE_LOCKED                  HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0013)
#define HI_ERR_OTP_WAIT_TIMEOUT                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0014)

#define HI_ERR_OTP_HISI_IOCTL                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0015)
#define HI_ERR_OTP_ALREADY_LOCKED               HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0016)
#define HI_ERR_OTP_SET_VERSION                  HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0017)
#define HI_ERR_OTP_INVALID_LENGTH               HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0018)
#define HI_ERR_OTP_READ_REG_FAILED              HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0019)
#define HI_ERR_OTP_SEC_FAILED                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0020)
#define HI_ERR_OTP_INVAILED_OFF_BIT             HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0021)
#define HI_ERR_OTP_PTR_NULL                     HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0022)
#define HI_ERR_OTP_MODULE_REG                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0023)
#define HI_ERR_OTP_PM_REG                       HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0024)
#define HI_ERR_OTP_INVAILED_VERSION             HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0025)
#define HI_ERR_OTP_NO_SUCH_OPTION               HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0026)
#define HI_ERR_OTP_TIMEOUT                      HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0027)
#define HI_ERR_OTP_PROG_PERM                    HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0028)

#define HI_ERR_OTP_NOT_FOUND                    HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x003f)
#define HI_ERR_OTP_NOT_SUPPORT                  HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0040)
#define HI_ERR_OTP_LOCK_UNEXPECT                HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0041)
#define HI_ERR_OTP_KEY_LOCKED                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0042)
#define HI_ERR_OTP_CRC_LOCKED                   HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0043)
#define HI_ERR_OTP_NOT_ENOUGH_MEMORY            HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0044)
#define HI_ERR_OTP_IOREMAP_FAILED               HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0045)
#define HI_ERR_OTP_FAKE_ACCESS_FAILED           HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0046)
#define HI_ERR_OTP_INAVLIED_PRIORITY            HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0047)
#define HI_ERR_OTP_IOCTL_CMD_INVALID            HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0048)
#define HI_ERR_OTP_IOCTL_FUNC_NULL              HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0049)
#define HI_ERR_OTP_NON_FAKE_MODE                HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0050)
#define HI_ERR_OTP_OUT_OF_RANGE                 HI_TEE_ERRCODE_DEF(HI_ID_OTP, 0x0051)

#define HI_ERR_KS_NOT_INIT                      HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0001)
#define HI_ERR_KS_NOT_SUPPORT                   HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0002)
#define HI_ERR_KS_INVALID_PARAM                 HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0003)
#define HI_ERR_KS_PTR_NULL                      HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0004)
#define HI_ERR_KS_CHECK_FAILED                  HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0005)
#define HI_ERR_KS_SYSCALL_FAILED                HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0006)
#define HI_ERR_KS_MALLOC_ERR                    HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0007)
#define HI_ERR_KS_NOT_FOUND                     HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0008)
#define HI_ERR_KS_MEM_MAP                       HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0009)
#define HI_ERR_KS_IOCTL_CMD_INVALID             HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x000A)
#define HI_ERR_KS_LOCK_FAILED                   HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x000B)
#define HI_ERR_KS_IOCTL_FUNC_NULL               HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x000C)
#define HI_ERR_KS_AUTO_LOCK_FAILED              HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x000D)
#define HI_ERR_KS_STAT_TIME_OUT                 HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x000E)
#define HI_ERR_KS_FLUSH_TIME_OUT                HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x000F)
/* LOCKED_CPUX last 4 bit means the cpu type */
#define HI_ERR_KS_LOCKED_CPUX                   HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0010)
#define HI_ERR_KS_MUTEX                         HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0021)
#define HI_ERR_KS_OPEN_ERR                      HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0022)
#define HI_ERR_KS_BUSY                          HI_TEE_ERRCODE_DEF(HI_ID_KEYSLOT, 0x0023)

#define HI_ERR_CERT_NOT_INIT                    HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0001)
#define HI_ERR_CERT_INVALID_HANDLE              HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0002)
#define HI_ERR_CERT_INVALID_PTR                 HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0003)
#define HI_ERR_CERT_INVALID_PARA                HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0004)
#define HI_ERR_CERT_FAILED_INIT                 HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0005)
#define HI_ERR_CERT_UNEXPECTED_STA              HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0006)
#define HI_ERR_CERT_UNEXPECTED_EMI              HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0007)
#define HI_ERR_CERT_KEY_INVALID                 HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0008)
#define HI_ERR_CERT_TIMEOUT                     HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0009)
#define HI_ERR_CERT_LOCKED                      HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x000A)
#define HI_ERR_CERT_UNLOCKED                    HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x000B)
#define HI_ERR_CERT_UNEXPECTED_CW               HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x000C)
#define HI_ERR_CERT_MUTEX_ERR                   HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x000D)
#define HI_ERR_CERT_LOCK_STA_ERR                HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x000E)
#define HI_ERR_CERT_DBG_ALG_ERR                 HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x000F)
#define HI_ERR_CERT_DBG_PRT_SEL_ERR             HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0010)
#define HI_ERR_CERT_DBG_USAGE_ERR               HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0011)
#define HI_ERR_CERT_DBG_OTHER_ERR               HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0012)
#define HI_ERR_CERT_UNKNOWN_CMD                 HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0013)
#define HI_ERR_CERT_UNEXPECTED_PORT             HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0014)
#define HI_ERR_CERT_REQUIRE_IRQ_FAILED          HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0015)
#define HI_ERR_CERT_PV_ACTIVATE                 HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0016)
#define HI_ERR_CERT_NO_KEY_GENERATION           HI_TEE_ERRCODE_DEF(HI_ID_CERT, 0x0017)

#define HI_ERR_NULL_PTR                         HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0001)
#define HI_ERR_INVALID_PARAM                    HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0002)
#define HI_ERR_NO_MEMORY                        HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0003)
#define HI_ERR_NO_DEV                           HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0004)
#define HI_ERR_NOT_SUPPORT                      HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0005)
#define HI_ERR_NOT_INIT                         HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0006)
#define HI_ERR_REE_CHANNEL                      HI_TEE_ERRCODE_DEF(HI_ID_SYS, 0x0007)

#define HI_ERR_SCI_OPEN_ERR                     HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0001)
#define HI_ERR_SCI_CLOSE_ERR                    HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0002)
#define HI_ERR_SCI_NOT_INIT                     HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0003)
#define HI_ERR_SCI_INVALID_PARA                 HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0004)
#define HI_ERR_SCI_NULL_PTR                     HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0005)
#define HI_ERR_SCI_INVALID_OPT                  HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0006)
#define HI_ERR_SCI_SEND_ERR                     HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0007)
#define HI_ERR_SCI_RECEIVE_ERR                  HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0008)
#define HI_ERR_SCI_NO_ATR                       HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x0009)
#define HI_ERR_SCI_PPS_PTYPE_ERR                HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x000A)
#define HI_ERR_SCI_PPS_FACTOR_ERR               HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x000B)
#define HI_ERR_SCI_PPS_NOTSUPPORT_ERR           HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x000C)
#define HI_ERR_SCI_NOTSUPPORT                   HI_TEE_ERRCODE_DEF(HI_ID_SCI, 0x000D)

#define HI_ERR_SSM_NULL_PTR                     HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0001)
#define HI_ERR_SSM_INVALID_INTENT               HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0002)
#define HI_ERR_SSM_INVALID_SESSOION_HANDLE      HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0003)
#define HI_ERR_SSM_FULL_SESSION_NUM             HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0004)
#define HI_ERR_SSM_CREATE_SESSOION_FAIL         HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0005)
#define HI_ERR_SSM_POLICY_INTENT_DISMATCH       HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0006)
#define HI_ERR_SSM_POLICY_MODULE_DISMATCH       HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0007)
#define HI_ERR_SSM_RESOURCE_ADDED               HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0008)
#define HI_ERR_SSM_DISOBEY_RULES                HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0009)
#define HI_ERR_SSM_CANT_FIND_ENTRY              HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x000A)
#define HI_ERR_SSM_CANT_FIND_MOD                HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x000B)
#define HI_ERR_SSM_INVALID_BUF_ID               HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x000C)
#define HI_ERR_SSM_INVALID_BUFFER_TYPE          HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x000D)
#define HI_ERR_SSM_NOT_SESSION_BELONGED_BUF     HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x000E)
#define HI_ERR_SSM_MODULE_HANDLE_NOT_MATCH      HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x000F)
#define HI_ERR_SSM_BUFFER_CHECK_NOT_MATCH       HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0010)
#define HI_ERR_SSM_BUFFER_ATTACHED_BEFORE       HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0011)
#define HI_ERR_SSM_BUFFER_DETACH_NOT_FOUND      HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0012)
#define HI_ERR_SSM_SECURE_INFO_MALLOC_FAIL      HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0013)
#define HI_ERR_SSM_NO_VALID_SECURE_INFO         HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0014)
#define HI_ERR_SSM_INVALID_SECURE_INFO_INDEX    HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0015)
#define HI_ERR_SSM_SECURE_INFO_NOT_FOUND        HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0016)
#define HI_EER_SSM_INVALID_SESSOION_HANDLE      HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0017)
#define HI_ERR_SSM_MODULE_ADDED_BEFORE          HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0018)
#define HI_ERR_SSM_BUF_ID_TYPE_NOT_MATCH        HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x0019)
#define HI_ERR_SSM_SECURE_INFO_INIT_FAIL        HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x001A)
#define HI_ERR_SSM_NO_NEED_SET_TAG_AGAIN        HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x001B)
#define HI_ERR_SSM_UUID_SET_BEFORE              HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x001C)
#define HI_ERR_SSM_UUID_NOT_MATCH               HI_TEE_ERRCODE_DEF(HI_ID_SSM, 0x001D)

#define HI_ERR_HDMITX_INVALID_PARA              HI_TEE_ERRCODE_DEF(HI_ID_HDMITX, 0x0001)
#define HI_ERR_HDMITX_NULL_PTR                  HI_TEE_ERRCODE_DEF(HI_ID_HDMITX, 0x0002)
#define HI_ERR_HDMITX_NOT_SUPPORT               HI_TEE_ERRCODE_DEF(HI_ID_HDMITX, 0x0003)
#define HI_ERR_HDMITX_UUID_FAIL                 HI_TEE_ERRCODE_DEF(HI_ID_HDMITX, 0x0004)

#define HI_ERR_HDMIRX_NULL_PTR                  HI_TEE_ERRCODE_DEF(HI_ID_HDMIRX, 0x0001)
#define HI_ERR_HDMIRX_PARAM_INVALID             HI_TEE_ERRCODE_DEF(HI_ID_HDMIRX, 0x0002)
#define HI_ERR_HDMIRX_MCU_CHK_FAILED            HI_TEE_ERRCODE_DEF(HI_ID_HDMIRX, 0x0003)
#define HI_ERR_HDMIRX_FEATURE_NOT_SUPPORT       HI_TEE_ERRCODE_DEF(HI_ID_HDMIRX, 0x0004)

#define HI_ERR_NPU_INVALID_PARA                 HI_TEE_ERRCODE_DEF(HI_ID_NPU, 0x0001)

#endif

