
WITH_BALONG_PLATFORM := 5
WITH_CHIP_HI6965 := 34
TRUSTEDCORE_PLATFORM_CHOOSE := WITH_BALONG_PLATFORM
	PLATFORM_NAME := balong
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := balong

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI6965=$(WITH_CHIP_HI6965) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_BALONG_PLATFORM=$(WITH_BALONG_PLATFORM)

