TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_CHARLOTTE
TRUSTEDCORE_PHY_TEXT_BASE := 0x13608000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x13E00000
GATEKEEPER_ITRATION_TIMES := 0
DERIVE_ROOT_INTERNAL_ITRATIONS := 0
