set (CONFIG_TUI_32BIT false)
set (CONFIG_TA_64BIT true)
set (CONFIG_SSA_64BIT true)
set (CONFIG_GTASK_64BIT true)
set (CONFIG_RPMB_64BIT true)
set (CONFIG_SEM false)
set (CONFIG_SE_SERVICE_64BIT true)
set (ENABLE_CPP false)
set (ENABLE_CPP_STATIC false)
set (CONFIG_GATEKEEPER_64BIT true)
set (CONFIG_KEYMASTER_64BIT true)
set (CONFIG_ANTIROOT false)
set (CONFIG_WEAVER false)
set (CONFIG_PERMSRV_64BIT true)
set (CONFIG_PLATDRV_64BIT true)
set (CONFIG_DRV_TIMER_64BIT true)
set (CONFIG_DRV_64BIT true)
set (CONFIG_DX_ENABLE false)
set (CONFIG_GMLIB_IMPORT true)
set (CONFIG_HUK_SERVICE_64BIT true)
set (ENABLE_TA_LOAD_WHITE_BOX_KEY true)

list(APPEND PRODUCT_APPS_64
)

list(APPEND PRODUCT_RELEASE_64
)

list(APPEND PRODUCT_APPS_32
)

list(APPEND PRODUCT_RELEASE_32
)

include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/${CHIP_NAME}/modules/modules.cmake)
