
set(WITH_LINGXIAO_PLATFORM     "4")
set(WITH_CHIP_HI5651T          "16")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_LINGXIAO_PLATFORM)
set(PLATFORM_NAME "lingxiao")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "router")

set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI5651T=${WITH_CHIP_HI5651T}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_LINGXIAO_PLATFORM=${WITH_LINGXIAO_PLATFORM}
)

