
WITH_IPC_PLATFORM := 9
WITH_CHIP_HI3516 := 23

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_IPC_PLATFORM
	PLATFORM_NAME := ipc
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
ifeq ($(product_name), demo)
    PRODUCT_NAME  := demo_arm32
else
	PRODUCT_NAME := camera
endif
export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI3516=$(WITH_CHIP_HI3516) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_IPC_PLATFORM=$(WITH_IPC_PLATFORM)

