
set(WITH_IPC_PLATFORM     "9")
set(WITH_CHIP_HI3516      "23")
set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_IPC_PLATFORM)
set(PLATFORM_NAME "ipc")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
if("${product_name}" STREQUAL "demo")
    set(PRODUCT_NAME  "demo_arm32")
else()
    set(PRODUCT_NAME "camera")
endif()
set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI3516=${WITH_CHIP_HI3516}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_IPC_PLATFORM=${WITH_IPC_PLATFORM}
)

