
WITH_HUANGLONG_PLATFORM := 2
WITH_CHIP_HI3716MV430N := 29

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_HUANGLONG_PLATFORM
	PLATFORM_NAME := huanglong
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := STB

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI3716MV430N=$(WITH_CHIP_HI3716MV430N) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_HUANGLONG_PLATFORM=$(WITH_HUANGLONG_PLATFORM)

