WITH_BALONG_PLATFORM := 5
WITH_CHIP_MOSES := 46

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_BALONG_PLATFORM
	PLATFORM_NAME := balong
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := balong

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_MOSES=$(WITH_CHIP_MOSES) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_BALONG_PLATFORM=$(WITH_BALONG_PLATFORM)
