/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
 * Description: process load hifi
 * Create: 2018-5-21
 */

#ifndef __HIFI_RELOAD_H__
#define __HIFI_RELOAD_H__

#define HIFI_SEC_MAX_NUM                100

#if (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_HI3680 || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_KIRIN990 || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_DENVER || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_BALTIMORE || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_BURBANK || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_LAGUNA)
#define HIFI_CMA_IMAGE_SIZE             0xA00000UL
#define HIFI_RUN_SIZE                   0xF00000UL
#else
#if (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_ORLANDO)
#define HIFI_CMA_IMAGE_SIZE             (0x800000UL)
#define HIFI_RUN_SIZE                   (0xD00000UL)
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_HI3670)
#define HIFI_CMA_IMAGE_SIZE             (0x700000UL)
#define HIFI_RUN_SIZE                   (0xB00000UL)
#else
#define HIFI_CMA_IMAGE_SIZE             (0x600000UL)
#define HIFI_RUN_SIZE                   (0xB00000UL)
#endif
#endif

#define HIFI_IMAGE_OCRAMBAK_SIZE        0x30000UL
#define HIFI_SEC_HEAD_SIZE              0x1000UL

#define HIFI_DDR_MAP_BEGIN_ADDR         0xC0000000UL
#if (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_KIRIN990 || TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_BALTIMORE)
#define HIFI_CFG_BASE_ADDR              0xFA54E000UL
#define HIFI_CFG_DMMU_BASE_ADDR         0xFA547000UL
#define HIFI_DMMU_REMAP_BEGIN_ADDR           (HIFI_CFG_DMMU_BASE_ADDR + 0x800UL)
#define HIFI_DMMU_REMAP_END_ADDR             (HIFI_CFG_DMMU_BASE_ADDR + 0x820UL)
#define HIFI_DMMU_REMAP_GID_ADDR                  (HIFI_CFG_DMMU_BASE_ADDR + 0x840UL)
#define HIFI_CFG_DDR_REMAP_EN_3	(HIFI_CFG_BASE_ADDR + 0x124)
#define HIFI_CFG_DDR_REMAP_SRC_3	(HIFI_CFG_BASE_ADDR + 0x128)
#define HIFI_CFG_DDR_REMAP_DES_3	(HIFI_CFG_BASE_ADDR + 0x12C)
#define HIFI_CFG_DDR_REMAP_EN_2	(HIFI_CFG_BASE_ADDR + 0x130)
#define HIFI_CFG_DDR_REMAP_SRC_2	(HIFI_CFG_BASE_ADDR + 0x134)
#define HIFI_CFG_DDR_REMAP_DES_2	(HIFI_CFG_BASE_ADDR + 0x138)
#define HIFI_CFG_DDR_REMAP_EN_1	(HIFI_CFG_BASE_ADDR + 0x13C)
#define HIFI_CFG_DDR_REMAP_SRC_1	(HIFI_CFG_BASE_ADDR + 0x140)
#define HIFI_CFG_DDR_REMAP_DES_1	(HIFI_CFG_BASE_ADDR + 0x144)
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_DENVER || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_BURBANK || \
	TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_LAGUNA)
#define HIFI_CFG_BASE_ADDR              0xFA54E000UL
#else
#define HIFI_CFG_BASE_ADDR              0xE804E000UL
#endif

#define HIFI_CFG_R_DSP_RUNSTALL         (HIFI_CFG_BASE_ADDR + 0x44UL)
#define SECOS_COPY_SIZE                 0x100000UL

#if (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_HI6250)
#define HIFI_IMAGE_TCMBAK_SIZE          0x1E000UL
#define HIFI_UNSEC_BASE_ADDR            0x34F00000UL
#define HIFI_UNSEC_REGION_SIZE          0x380000UL
#define HIFI_SEC_RESERVE_SIZE           0x31000UL

#define HIFI_SEC_BASE_ADDR              (HIFI_UNSEC_BASE_ADDR + HIFI_UNSEC_REGION_SIZE)
#define HIFI_IMAGE_OCRAMBAK_LOCATION    (HIFI_SEC_BASE_ADDR)
#define HIFI_IMAGE_TCMBAK_LOCATION      (HIFI_IMAGE_OCRAMBAK_LOCATION + HIFI_IMAGE_OCRAMBAK_SIZE)
#define HIFI_SEC_HEAD_LOCATION          (HIFI_IMAGE_TCMBAK_LOCATION + HIFI_IMAGE_TCMBAK_SIZE)
#define HIFI_SEC_RESERVE_ADDR           (HIFI_SEC_HEAD_LOCATION + HIFI_SEC_HEAD_SIZE)
#define HIFI_RUN_LOCATION               (HIFI_SEC_RESERVE_ADDR + HIFI_SEC_RESERVE_SIZE)

#define HIFI_POWER_STATUS_OFFSET        0x2C5020
#else
#define HIFI_IMAGE_TCMBAK_SIZE          0x34000UL

#if (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_HI3670)
#define HIFI_RESERVED_PHYMEM_BASE      0x8D500000UL
#define HIFI_RESERVED_PHYMEM_BASE_FAMA 0x5AD500000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x8E300000UL
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_HI6260)
#ifdef CONFIG_AP_CUST_2G_MEM
#define HIFI_RESERVED_PHYMEM_BASE      0x13000000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x10200000UL
#else
#define HIFI_RESERVED_PHYMEM_BASE      0x14400000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x2D500000UL
#endif
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_HI3680 || TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_KIRIN990)
#define HIFI_RESERVED_PHYMEM_BASE      0x2DA00000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x2E980000UL
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_DENVER)
#define HIFI_RESERVED_PHYMEM_BASE      0x34C00000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x19100000UL
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_ORLANDO)
#define HIFI_RESERVED_PHYMEM_BASE      0x17800000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x2D500000UL
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_BALTIMORE)
#define HIFI_RESERVED_PHYMEM_BASE      0x2DA00000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x2F380000UL
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_MIAMICW)
#define HIFI_RESERVED_PHYMEM_BASE      0x15F00000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x13980000UL
#elif (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_LAGUNA || TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_BURBANK)
#define HIFI_RESERVED_PHYMEM_BASE      0x19E00000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x1AE90000UL
#else
#define HIFI_RESERVED_PHYMEM_BASE      0x89200000UL
#define HIFI_RESERVED_PHYMEM_BASE_FAMA 0x5A9200000UL
#define HIFI_RESERVED_DATA_PHYMEM_BASE 0x8B600000UL
#endif

#ifdef CONFIG_HISI_FAMA
#define HIFI_SEC_BASE_ADDR              (HIFI_RESERVED_PHYMEM_BASE_FAMA)
#else
#define HIFI_SEC_BASE_ADDR              (HIFI_RESERVED_PHYMEM_BASE)
#endif
#define HIFI_UNSEC_BASE_ADDR            (HIFI_RESERVED_DATA_PHYMEM_BASE)

#define HIFI_RUN_LOCATION               (HIFI_SEC_BASE_ADDR)
#define HIFI_IMAGE_OCRAMBAK_LOCATION    (HIFI_RUN_LOCATION + HIFI_RUN_SIZE)
#define HIFI_IMAGE_TCMBAK_LOCATION      (HIFI_IMAGE_OCRAMBAK_LOCATION + HIFI_IMAGE_OCRAMBAK_SIZE)
#define HIFI_SEC_HEAD_LOCATION          (HIFI_IMAGE_TCMBAK_LOCATION + HIFI_IMAGE_TCMBAK_SIZE)

#if (TRUSTEDCORE_CHIP_CHOOSE == WITH_CHIP_MIAMICW)
#define HIFI_POWER_STATUS_OFFSET        0x266020
#else
#define HIFI_POWER_STATUS_OFFSET        0x3C5020
#endif
#endif

#define HIFI_POWER_STATUS_ADDR          (HIFI_UNSEC_BASE_ADDR + HIFI_POWER_STATUS_OFFSET)
#define HIFI_POWER_ON                   0x55AA55AA

#endif /* __HIFI_RELOAD_H__ */

