
set(WITH_HIGENERIC_PLATFORM  "7")
set(WITH_CHIP_KIRIN990       "6")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_HIGENERIC_PLATFORM)
set(PLATFORM_NAME "higeneric")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
if ("${product_type}" STREQUAL "armpc")
    set(PRODUCT_NAME  "pc")
else()
    set(PRODUCT_NAME  "phone")
endif()
set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_KIRIN990=${WITH_CHIP_KIRIN990}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_HIGENERIC_PLATFORM=${WITH_HIGENERIC_PLATFORM}
)

