
WITH_HUANGLONG_PLATFORM := 2
WITH_CHIP_SHAOLINAXE := 38

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_HUANGLONG_PLATFORM
	PLATFORM_NAME := huanglong
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := TV

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_SHAOLINAXE=$(WITH_CHIP_SHAOLINAXE) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_HUANGLONG_PLATFORM=$(WITH_HUANGLONG_PLATFORM)

