
WITH_KUNPENG_PLATFORM := 3
WITH_CHIP_HI1620 := 15

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_KUNPENG_PLATFORM
	PLATFORM_NAME := kunpeng
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := kunpeng

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_HI1620=$(WITH_CHIP_HI1620) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_KUNPENG_PLATFORM=$(WITH_KUNPENG_PLATFORM)

