set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_MT6853)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x70008000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x70800000)
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DTEE_SUPPORT_ATTESTATION_TA
)
set(GATEKEEPER_ITRATION_TIMES 0)
set(DERIVE_ROOT_INTERNAL_ITRATIONS 0)