
WITH_QEMU_PLATFORM := 8
WITH_CHIP_XINGTIAN_LITE := 32

TRUSTEDCORE_PLATFORM_CHOOSE := WITH_QEMU_PLATFORM
	PLATFORM_NAME := qemu
	CHIP_NAME     := $(TARGET_BOARD_PLATFORM)
	PRODUCT_NAME  := qemu

export TARGET_BOARD_PLATFORM := $(TARGET_BOARD_PLATFORM)

TRUSTEDCORE_PLATFORM_FLAGS += \
	-DWITH_CHIP_XINGTIAN_LITE=$(WITH_CHIP_XINGTIAN_LITE) \
	-DWITH_CHIP_PLATFORM=$(PLATFORM_NAME) \
	-DWITH_QEMU_PLATFORM=$(WITH_QEMU_PLATFORM)

