
set(WITH_HIGENERIC_PLATFORM     "7")
set(WITH_CHIP_MIAMICW           "12")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_HIGENERIC_PLATFORM)
set(PLATFORM_NAME "higeneric")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
set(PRODUCT_NAME  "watch")


set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_MIAMICW=${WITH_CHIP_MIAMICW}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_HIGENERIC_PLATFORM=${WITH_HIGENERIC_PLATFORM}
)


