GATEKEEPER_ITRATION_TIMES := 0
DERIVE_ROOT_INTERNAL_ITRATIONS := 0
ifeq ($(CONFIG_M_DRIVER), true)
flags += -DTEE_SUPPORT_M_DRIVER
endif

ifeq ($(CONFIG_TUI_MTK_DRIVER), true)
flags += -DTEE_SUPPORT_TUI_MTK_DRIVER
endif
