set(CONFIG_TA_32BIT true)
set(MTK_CC_FEATURE true)
set(CONFIG_MTK_TIMER true)
set(CONFIG_MTK_BOOT_INFO true)
set(CONFIG_CRYPTO_SUPPORT_EC25519 true)
set(CONFIG_CRYPTO_SUPPORT_X509 true)
set(CONFIG_CRYPTO_ECC_WRAPPER true)
set(CONFIG_CRYPTO_AES_WRAPPER true)
set(CONFIG_TA_SIGN_KEY_CBG true)
set(CONFIG_SIGN_KEY_RELEASE_DEBUG_ISOLATION true)

list(APPEND PRODUCT_RELEASE_32 drv_timer.elf platdrv.elf)
list(APPEND PRODUCT_RELEASE_32 sec_flash_client)
list(APPEND PRODUCT_RELEASE_64 sec_flash_client)
list(APPEND BOOTFS_FILES_IN_PREBUILD taloader.elf)

if ("${CONFIG_SUPPORT_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_RELEASE_64 storage.elf attestation_ta.elf)
else()
    list(APPEND PRODUCT_RELEASE_64 storage.elf attestation_ta.elf)
    list(APPEND PRODUCT_RELEASE_32 storage.elf tui.elf attestation_ta.elf)
endif()

if ("${CONFIG_DRV_64BIT}" STREQUAL "false")
    list(APPEND PRODUCT_APPS_32 attestation_ta.elf storage.elf)
endif()
if ("${CONFIG_DRV_64BIT}" STREQUAL "true")
    list(APPEND PRODUCT_APPS_64 attestation_ta.elf storage.elf)
endif()

include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/common/modules/modules.cmake)
