set(CONFIG_TA_32BIT true)
set(CONFIG_CRYPTO_SUPPORT_EC25519 true)
set(CONFIG_CRYPTO_SUPPORT_X509 true)
set(CONFIG_CRYPTO_ECC_WRAPPER true)
set(CONFIG_CRYPTO_AES_WRAPPER true)
set(CONFIG_TIMER_EVENT true)

if ("${CONFIG_DX_ENABLE}" STREQUAL "y")
    list(APPEND PRODUCT_RELEASE_32 dx_cc7)
endif()

list(APPEND BOOTFS_FILES_IN_PREBUILD taloader.elf)

include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/common/modules/modules.cmake)
