/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Description: hisee teeos to ipc mail box map.
 * Create: 2019/9/30
 */

#ifndef __HISEE_MAILBOX_RAM_MAP_H__
#define __HISEE_MAILBOX_RAM_MAP_H__

#include "soc_acpu_baseaddr_interface.h"

#define HISEE_MBXRAM_PHYMEM_ADDR                        SOC_ACPU_HISEE_MAILBOX_BASE_ADDR
#define HISEE_MBXRAM_PHYMEM_SIZE                        0x4000

/* hisee mailbox ram map begin */
/* IPC: +0x0 */
#define HISEE_MBXRAM_IPC_PHYMEM_ADDR                    HISEE_MBXRAM_PHYMEM_ADDR
#define HISEE_MBXRAM_IPC_PHYMEM_SIZE                    0x3800

/* MNTN BUFFER: +0x3800 */
#define HISEE_MBXRAM_MNTN_BUFFER_PHYMEM_ADDR            \
	(HISEE_MBXRAM_IPC_PHYMEM_ADDR + HISEE_MBXRAM_IPC_PHYMEM_SIZE)
#define HISEE_MBXRAM_MNTN_BUFFER_PHYMEM_SIZE            0x7B0

/* PROCESS MTRACE: +0x3FB0 */
#define HISEE_MBXRAM_PROCESS_MTRACE_PHYMEM_ADDR         \
	(HISEE_MBXRAM_MNTN_BUFFER_PHYMEM_ADDR + HISEE_MBXRAM_MNTN_BUFFER_PHYMEM_SIZE)
#define HISEE_MBXRAM_PROCESS_MTRACE_PHYMEM_SIZE         4

/* COSID/OTP PGM STATUS/IS DONE FLAG: +0x3FB4 */
#define HISEE_MBXRAM_COSID_PHYMEM_ADDR                  \
	(HISEE_MBXRAM_PROCESS_MTRACE_PHYMEM_ADDR + HISEE_MBXRAM_PROCESS_MTRACE_PHYMEM_SIZE)
#define HISEE_MBXRAM_COSID_PHYMEM_SIZE                  4

#define HISEE_MBXRAM_OTP_PGM_STATUS_PHYMEM_ADDR         \
	HISEE_MBXRAM_COSID_PHYMEM_ADDR
#define HISEE_MBXRAM_OTP_PGM_STATUS_PHYMEM_SIZE         4

#define HISEE_MBXRAM_IS_DONE_FLAG_PHYMEM_ADDR           \
	HISEE_MBXRAM_COSID_PHYMEM_ADDR
#define HISEE_MBXRAM_IS_DONE_FLAG_PHYMEM_SIZE           4

/* RPMB DEVICE INFO: +0x3FB8 */
#define HISEE_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_ADDR       \
	(HISEE_MBXRAM_COSID_PHYMEM_ADDR + HISEE_MBXRAM_COSID_PHYMEM_SIZE)
#define HISEE_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_SIZE       4

/* SYSRST SAVED FLAG: +0x3FBC */
#define HISEE_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_ADDR      \
	(HISEE_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_ADDR + HISEE_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_SIZE)
#define HISEE_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_SIZE      4

/* SYSTEM RESET STATE/DEBUG ROM READY: +0x3FC0 */
#define HISEE_MBXRAM_SYSRST_STATE_PHYMEM_ADDR           \
	(HISEE_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_ADDR + HISEE_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_SIZE)
#define HISEE_MBXRAM_SYSRST_STATE_PHYMEM_SIZE           4

#define HISEE_MBXRAM_DEBUG_ROM_READY_PHYMEM_ADDR        \
	HISEE_MBXRAM_SYSRST_STATE_PHYMEM_ADDR
#define HISEE_MBXRAM_DEBUG_ROM_READY_PHYMEM_SIZE        4

/* SENSOR CTRL ALARM STATE: +0x3FC4 */
#define HISEE_MBXRAM_SC_ALARM_STATE_PHYMEM_ADDR         \
	(HISEE_MBXRAM_SYSRST_STATE_PHYMEM_ADDR + HISEE_MBXRAM_SYSRST_STATE_PHYMEM_SIZE)
#define HISEE_MBXRAM_SC_ALARM_STATE_PHYMEM_SIZE         4

/* MB SOFT FAULT ID: +0x3FC8 */
#define HISEE_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_ADDR       \
	(HISEE_MBXRAM_SC_ALARM_STATE_PHYMEM_ADDR + HISEE_MBXRAM_SC_ALARM_STATE_PHYMEM_SIZE)
#define HISEE_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_SIZE       4

/* MB SOFT FAULT VALUE: +0x3FCC */
#define HISEE_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_ADDR    \
	(HISEE_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_ADDR + HISEE_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_SIZE)
#define HISEE_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_SIZE    4

/* SYS CLOCK CFG/DEBUG ROM LOOP: +0x3FD0 */
#define HISEE_MBXRAM_SYS_CLOCK_CFG_PHYMEM_ADDR          \
	(HISEE_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_ADDR + HISEE_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_SIZE)
#define HISEE_MBXRAM_SYS_CLOCK_CFG_PHYMEM_SIZE          4

#define HISEE_MBXRAM_DEBUG_ROM_LOOP_PHYMEM_ADDR         \
	HISEE_MBXRAM_SYS_CLOCK_CFG_PHYMEM_ADDR
#define HISEE_MBXRAM_DEBUG_ROM_LOOP_PHYMEM_SIZE         4

/* BOOT MISC FLAG: +0x3FD4 */
#define HISEE_MBXRAM_BOOT_MISC_FLAG_PHYMEM_ADDR         \
	(HISEE_MBXRAM_SYS_CLOCK_CFG_PHYMEM_ADDR + HISEE_MBXRAM_SYS_CLOCK_CFG_PHYMEM_SIZE)
#define HISEE_MBXRAM_BOOT_MISC_FLAG_PHYMEM_SIZE         4

/* PROCESS MAGIC/SMX PROCESS: +0x3FD8 */
#define HISEE_MBXRAM_PROCESS_MAGIC_PHYMEM_ADDR          \
	(HISEE_MBXRAM_BOOT_MISC_FLAG_PHYMEM_ADDR + HISEE_MBXRAM_BOOT_MISC_FLAG_PHYMEM_SIZE)
#define HISEE_MBXRAM_PROCESS_MAGIC_PHYMEM_SIZE          4

#define HISEE_MBXRAM_SMX_PROCESS_PHYMEM_ADDR            \
	HISEE_MBXRAM_PROCESS_MAGIC_PHYMEM_ADDR
#define HISEE_MBXRAM_SMX_PROCESS_PHYMEM_SIZE            4

/* PROCESS FLAG/SECUREDEBUG FLAG/SHUTDOWN SWIPE FLAG: +0x3FDC */
#define HISEE_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR           \
	(HISEE_MBXRAM_PROCESS_MAGIC_PHYMEM_ADDR + HISEE_MBXRAM_PROCESS_MAGIC_PHYMEM_SIZE)
#define HISEE_MBXRAM_PROCESS_FLAG_PHYMEM_SIZE           4

#define HISEE_MBXRAM_SECUREDEBUG_FLAG_PHYMEM_ADDR       \
	HISEE_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR
#define HISEE_MBXRAM_SECUREDEBUG_FLAG_PHYMEM_SIZE       4

#define HISEE_MBXRAM_SHUTDOWN_SWIPE_FLAG_PHYMEM_ADDR    \
	HISEE_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR
#define HISEE_MBXRAM_SHUTDOWN_SWIPE_FLAG_PHYMEM_SIZE    4

/* TABLE: +0x3FE0 */
#define HISEE_MBXRAM_TABLE_PHYMEM_ADDR                  \
	(HISEE_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR + HISEE_MBXRAM_PROCESS_FLAG_PHYMEM_SIZE)
#define HISEE_MBXRAM_TABLE_PHYMEM_SIZE                  32

/* hisee mailbox ram map end */
#if ((HISEE_MBXRAM_TABLE_PHYMEM_ADDR + HISEE_MBXRAM_TABLE_PHYMEM_SIZE) > \
	(HISEE_MBXRAM_PHYMEM_ADDR + HISEE_MBXRAM_PHYMEM_SIZE))
#error "hisee mailbox ram beyond the boundary!!!"
#endif

#endif /* __HISEE_MAILBOX_RAM_MAP_H__ */
