# platform compile rules
# Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.

if(NOT TARGET_BOARD_PLATFORM STREQUAL "")
include(${PLATFORM_DIR}/../cmake/plat/${TARGET_BOARD_PLATFORM}/plat.cmake)

if(PRODUCT_NAME STREQUAL "")
    include(${PLATFORM_DIR}/${PLATFORM_NAME}/${CHIP_NAME}/chip.cmake)
    include(${PLATFORM_DIR}/${PLATFORM_NAME}/common/chip.cmake)
else()
    include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/${CHIP_NAME}/chip.cmake)
    include(${PLATFORM_DIR}/${PLATFORM_NAME}/${PRODUCT_NAME}/common/chip.cmake)
endif()


include(apps_asan)

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DTRUSTEDCORE_PHY_TEXT_BASE=${TRUSTEDCORE_PHY_TEXT_BASE}
    -DTRUSTEDCORE_PHY_IMAGE_LOAD_BASE=${TRUSTEDCORE_PHY_IMAGE_LOAD_BASE}
    -DHMAPPS_COMMIT_ID=${HMAPPS_COMMIT}
    -DTRUSTEDCORE_CHIP_CHOOSE=${TRUSTEDCORE_CHIP_CHOOSE}
    -DTRUSTEDCORE_PLATFORM_CHOOSE=${TRUSTEDCORE_PLATFORM_CHOOSE}
)
endif()
