if ("${HM_PLATFORM}" STREQUAL "kirin")
    list(APPEND TEE_C_FLAGS -DKIRIN)
elseif ("${HM_PLATFORM}" STREQUAL "virt")
    list(APPEND TEE_C_FLAGS -DVIRT)
elseif ("${HM_PLATFORM}" STREQUAL "mtk")
    list(APPEND TEE_C_FLAGS -DMTK)
elseif ("${HM_PLATFORM}" STREQUAL "stb")
    list(APPEND TEE_C_FLAGS -DSTB)
elseif ("${HM_PLATFORM}" STREQUAL "kunpeng")
    list(APPEND TEE_C_FLAGS -DKUNPENG)
elseif ("${HM_PLATFORM}" STREQUAL "lingxiao")
    list(APPEND TEE_C_FLAGS -DLINGXIAO)
elseif ("${HM_PLATFORM}" STREQUAL "balong")
    list(APPEND TEE_C_FLAGS -DBALONG)
elseif ("${HM_PLATFORM}" STREQUAL "ascend")
    list(APPEND TEE_C_FLAGS -DASCEND)
endif()
