TRUSTEDCORE_CHIP_CHOOSE := WITH_CHIP_SHAOLINSWORD
TRUSTEDCORE_PHY_TEXT_BASE := 0x30A08000
TRUSTEDCORE_PHY_IMAGE_LOAD_BASE := 0x31200000
TRUSTEDCORE_PLATFORM_FLAGS += -DFEATURE_SE
TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_ATTESTATION_TA
#TRUSTEDCORE_PLATFORM_FLAGS += -DCONFIG_HISEE_14_CHANNEL_IPC
#TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY
#TRUSTEDCORE_PLATFORM_FLAGS += -DTEE_SUPPORT_FILE_ENCRY_PASS_FBE2
