set(TRUSTEDCORE_CHIP_CHOOSE WITH_CHIP_SHAOLINSWORD)
set(TRUSTEDCORE_PHY_TEXT_BASE 0x30A08000)
set(TRUSTEDCORE_PHY_IMAGE_LOAD_BASE 0x31200000)
list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DFEATURE_SE
    -DTEE_SUPPORT_ATTESTATION_TA
)
