
set(WITH_ASCEND_PLATFORM  "6")
set(WITH_CHIP_HI1951      "18")

set(TRUSTEDCORE_PLATFORM_CHOOSE WITH_ASCEND_PLATFORM)
set(PLATFORM_NAME "ascend")
set(CHIP_NAME     ${TARGET_BOARD_PLATFORM})
if ("${product_name}" STREQUAL "mini")
    set(PRODUCT_NAME  "mini")
else()
    set(PRODUCT_NAME  "mdc")
endif()
set(TARGET_BOARD_PLATFORM ${TARGET_BOARD_PLATFORM})

list(APPEND TRUSTEDCORE_PLATFORM_FLAGS
    -DWITH_CHIP_HI1951=${WITH_CHIP_HI1951}
    -DWITH_CHIP_PLATFORM=${PLATFORM_NAME}
    -DWITH_ASCEND_PLATFORM=${WITH_ASCEND_PLATFORM}
)


