#ifndef __HISI_DDR_AUTOFSGT_PROXY_SECURE_OS_H__
#define __HISI_DDR_AUTOFSGT_PROXY_SECURE_OS_H__

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
/*same as vender/hisi/confidential/lpmcu/.../ddr_auto_fsgt.h*/

typedef enum {
	DDR_AUTOFSGT_ENABLE = 1,
	DDR_AUTOFSGT_DISABLE,
	DDR_AUTOFSGT_LOGIC_EN,
	DDR_AUTOFSGT_LOGIC_DIS,
}
DDR_AUTOFSGT_CMD_ID;
#ifdef CONFIG_ARCH_HI3660
typedef enum {
	DDR_AUTOFSGT_CLIENT_AP = 1,
	DDR_AUTOFSGT_CLIENT_BL31,
	DDR_AUTOFSGT_CLIENT_SECURE_OS,
	DDR_AUTOFSGT_CLIENT_DDR_MESSION,
	DDR_AUTOFSGT_CLIENT_LPMCU,
	DDR_AUTOFSGT_CLIENT_ONOFF,
	DDR_AUTOFSGT_CLIENT_BUTT,
} DDR_AUTOFSGT_CLIENT_ID;


typedef enum {
	DDR_AUTOFSGT_PROXY_CLIENT_SETSEC = 1,
	DDR_AUTOFSGT_PROXY_CLIENT_CLRSEC,
	DDR_AUTOFSGT_PROXY_CLIENT_CHECKSEC,
	DDR_AUTOFSGT_PROXY_CLIENT_BUTT,
} DDR_AUTOFSGT_PROXY_CLIENT_ID;
#else
/*should keep same with ap/platform ddr_define.h*/
typedef enum {
	DDR_AUTOFSGT_CLIENT_LPMCU = 0,
/*bl31*/
	DDR_AUTOFSGT_CLIENT_BL31 = 1,
	DDR_AUTOFSGT_PROXY_CLIENT_FREQDUMP,
	DDR_AUTOFSGT_PROXY_CLIENT_DDRREG,
	DDR_AUTOFSGT_PROXY_CLIENT_SETDDRSEC,
	DDR_AUTOFSGT_PROXY_CLIENT_CLRDDRSEC,
	DDR_AUTOFSGT_PROXY_CLIENT_ISPOPEN,
	DDR_AUTOFSGT_PROXY_CLIENT_ISPCLOSE,
	DDR_AUTOFSGT_PROXY_CLIENT_KERNEL_CODE,
/*secure_os*/
	DDR_AUTOFSGT_CLIENT_SECURE_OS = 9,
	DDR_AUTOFSGT_PROXY_CLIENT_SETSEC = 9,
	DDR_AUTOFSGT_PROXY_CLIENT_CLRSEC = 9,
	DDR_AUTOFSGT_PROXY_CLIENT_CHECKSEC = 9,
/*ap*/
	DDR_AUTOFSGT_CLIENT_AP,
	DDR_AUTOFSGT_PROXY_CLIENT_DDRFLUX,
	DDR_AUTOFSGT_PROXY_CLIENT_DMSSPT,
	/*Please add your definition above!!!*/
	DDR_AUTOFSGT_PROXY_CLIENT_BUTT,
} DDR_AUTOFSGT_PROXY_CLIENT_ID;
#endif
/*s32 ddr_autofsgt_ctrl(DDR_AUTOFSGT_PROXY_CLIENT_ID client, DDR_AUTOFSGT_CMD_ID cmd)*/
extern int ddr_autofsgt_ctrl(unsigned int client, unsigned int cmd);


#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif /* end of hisi_ddr_autofsgt_proxy_secure_os.h */
